### ISSUE TITLE
在 Centos 8下无法启动

### ISSUE THREAD

**Issue by fesiong** [cnk3x/xunlei#1]
● xunlei-from-syno.service - 迅雷群晖提取版
   Loaded: loaded (/etc/systemd/system/xunlei-from-syno.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Fri 2021-12-31 16:58:02 CST; 1s ago
  Process: 131839 ExecStart=/var/packages/pan-xunlei-com/xunlei-from-syno run --port 2345 --download-dir=/data2/Downloads (code=exited, status=1/FAILURE)
 Main PID: 131839 (code=exited, status=1/FAILURE)

12月 31 16:58:01 localhost.localdomain systemd[1]: Started 迅雷群晖提取版.
12月 31 16:58:02 localhost.localdomain xunlei-from-syno[131839]: 2021/12/31 16:58:02 设备名称(不一定有用): U-NAS-迅雷
12月 31 16:58:02 localhost.localdomain xunlei-from-syno[131839]: 2021/12/31 16:58:02 面板端口: 2345
12月 31 16:58:02 localhost.localdomain xunlei-from-syno[131839]: 2021/12/31 16:58:02 下载目录: /data2/Downloads
12月 31 16:58:02 localhost.localdomain xunlei-from-syno[131839]: 2021/12/31 16:58:02 [启动自检]
12月 31 16:58:02 localhost.localdomain xunlei-from-syno[131839]: 2021/12/31 16:58:02 [启动自检] symlink /var/packages/pan-xunlei-com/host/usr/syno/synoman/webman/modules/authe>
12月 31 16:58:02 localhost.localdomain systemd[1]: xunlei-from-syno.service: Main process exited, code=exited, status=1/FAILURE
12月 31 16:58:02 localhost.localdomain systemd[1]: xunlei-from-syno.service: Failed with result 'exit-code'.

**Comment by fesiong** [comment]
成功解决了。

实际问题是没有建立软连接。手动建立下正常

**Comment by cnk3x** [comment]
碰到不能启动，大概率是权限问题，换root或者sudo 就可以了的
