### ISSUE TITLE
小插件跑纳思小心不给钱啊

### ISSUE THREAD

**Issue by huangzpp** [cnk3x/xunlei#101]
缓存有，也有跑量，收益为0

**Comment by cnk3x** [comment]
跑几天了？

**Comment by huangzpp** [comment]
> 跑几天了？

5天，缓存有个6G吧，环境为PVE-OPENWRT-DOCKER-迅雷-小插件纳思小新。同网络环境下PVE-群晖-迅雷-小插件纳思小新是给钱的，很迷。是网心云官方屏蔽第三方小心？

**Comment by mapleafgo** [comment]
楼主现在有收益没？我发现识别不到磁盘大小，可能与此有关？
![Screenshot_2023-06-19-14-30-38-930_com.onethingcloud.android.jpg](https://github.com/cnk3x/xunlei/assets/20534139/5d0f23c1-35df-4602-bba1-5fa63594aef8)

**Comment by weiyideai520** [comment]
我昨天跑了一下，收益1块钱

**Comment by mapleafgo** [comment]
> 我昨天跑了一下，收益1块钱

你那不是的，可以看下收益明细，会有个绑定新设备的奖励，1元。我另外跑了个容器魔方，每天两三毛收益😂

**Comment by weiyideai520** [comment]
> 

啊，还真是，贡献收益为 0

**Comment by MDCY9008** [comment]
> 楼主现在有收益没？我发现识别不到磁盘大小，可能与此有关？ ![Screenshot_2023-06-19-14-30-38-930_com.onethingcloud.android.jpg](https://user-images.githubusercontent.com/20534139/246744639-5d0f23c1-35df-4602-bba1-5fa63594aef8.jpg)

![image](https://github.com/cnk3x/xunlei/assets/54255527/081d105e-7134-46b8-a13d-fba65b5f926d)

把```-v```挂载改为```bind mount```挂载，app里能正常识别磁盘，收益待测试。

![120596E9A17F1919922BE208EB6256C8](https://github.com/cnk3x/xunlei/assets/54255527/607256ae-a80c-4738-a75f-6ccfdf15c8c7)

**Comment by WEIBP** [comment]
目前没有收益，磁盘能识别，有缓存，从路由器里看有上行流量

**Comment by huzige433** [comment]
同样,也是0收益,挂了10天了,1分钱都没有

**Comment by 346673164** [comment]
找了客服，提示下面这样。
您好，经核实后台系统未检测到设备类型；当前NAS合作厂商设备类型有如下：群晖、威联通、绿联、极空间、联想、铁威马、华为等，其它厂商设备（含通过其它设备刷机的类型）暂不支持。

**Comment by liwenjie119** [comment]
> ![image](https://user-images.githubusercontent.com/54255527/250237316-081d105e-7134-46b8-a13d-fba65b5f926d.png)
> 
> 把`-v`挂载改为`bind mount`挂载，app里能正常识别磁盘，收益待测试。
> 
> ![120596E9A17F1919922BE208EB6256C8](https://user-images.githubusercontent.com/54255527/250237584-607256ae-a80c-4738-a75f-6ccfdf15c8c7.jpg)

是否有收益了？

**Comment by sunyh87** [comment]
> ![image](https://private-user-images.githubusercontent.com/54255527/250237316-081d105e-7134-46b8-a13d-fba65b5f926d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxMDQ5MDcsIm5iZiI6MTcxNDEwNDYwNywicGF0aCI6Ii81NDI1NTUyNy8yNTAyMzczMTYtMDgxZDEwNWUtNzEzNC00NmI4LWExM2QtZmJhNjViNWY5MjZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI2VDA0MTAwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyNDFjODZjMDViNTY5MjczOWM1MGZjMjM4YjM2MTZmMzY2ZGI4YmYzNzI4NTdjYmI0N2ZkOTcyZjIyZDY2MjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ESRFzKU1OjqvVkaH38hBXpedXPavormIJrd6RHmRy7s)
> 
> 把`-v`挂载改为`bind mount`挂载，app里能正常识别磁盘，收益待测试。
> 
> ![120596E9A17F1919922BE208EB6256C8](https://private-user-images.githubusercontent.com/54255527/250237584-607256ae-a80c-4738-a75f-6ccfdf15c8c7.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxMDQ5MDcsIm5iZiI6MTcxNDEwNDYwNywicGF0aCI6Ii81NDI1NTUyNy8yNTAyMzc1ODQtNjA3MjU2YWUtYTgwYy00NzM4LWE3NWYtNmNjZmRmMTVjOGM3LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI2VDA0MTAwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzYzI5ZDM2OGFlN2JlMmRlMGE3MTIzYmE1Yzk2ZjdhYWMzOTRjMzg3OGEzZmQxYTY5OTQ0OTFmZmU3NmM4YmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dViyxDEZyZ42xFOXlqRVVpWExh8alpRNmLwzltwSyIQ)

用了这命令还是看不到磁盘，可是跑量正常 就是0元
