### ISSUE TITLE
有什么办法可以限制其上传吗？

### ISSUE THREAD

**Issue by EuropeanWithSSR** [cnk3x/xunlei#104]
跑在软路由上，qos之类的工具似乎没法对其很好地限速（也可能是我没设置对）。没有开网心云的插件，但上传却占用满了。

**Comment by chunfengyao** [comment]
可以试试tc，进行流量限制。
建议镜像作者可以直接加到容器镜像中，然后通过环境变量搞成可配置的上传速度限制。迅雷这做的太绝了，根本没给设置上传速度。而且，疯狂刷上传流量。

**Comment by Vash90** [comment]
也有同样的希望，查了一圈，都没找到好方法。迅雷上传起来真的不要命，机械硬盘扛不住，访问nas卡的要命。

**Comment by marcmk6** [comment]
尝试了在[容器内使用tc的方法](https://stackoverflow.com/a/48758203)，但报`RTNETLINK answers: No such file or directory`
还有一个[相关的项目](https://github.com/lukaszlach/docker-tc)，但项目似乎疏于维护，甚至无法复现用例...
