### ISSUE TITLE
下载目录为网络路径，可以正常写入但是显示的容量大小有误

### ISSUE THREAD

**Issue by meimingziyongle** [cnk3x/xunlei#105]
部署方式为docker，x86，非群晖。部署完登陆后更新最新版，composer映射了外部挂载的smb路径，可以在web界面进行新文件夹建立的操作，内容正常显示，但是容量为部署机的容量，超过这个大小的文件不能下载。小于的文件可以正常下载，下载完添加新文件时可以看到可用容量没有变化，网络共享路径下载的文件正常打开。不知道是不是官方的问题
这是composer文件：
version: "2.1"

services:

  xunlei:

    image: cnk3x/xunlei:latest
    privileged: true
    container_name: xunlei
    hostname: XunLei
    networks:
      mynet:
        ipv4_address: 172.18.0.12
    ports:
      - 2345:2345
    volumes:
      - /home/docker/xunlei:/xunlei/data   # data directory
      - /tmp/nas/disk01:/xunlei/downloads/disk01
      - /tmp/nas/mininas:/xunlei/downloads/mininas   # download directory
    restart: unless-stopped

networks:
  mynet:
    external: true
此虚拟机也部署了qb，容量识别正常。不知道有没有办法跳过容量检测的步骤或者可以识别到网络路径的正确容量大小，非常感谢。

**Comment by laozhang713** [comment]
同样的问题，smb挂载的盘，显示的容量是本地盘的容量。

**Comment by laozhang713** [comment]
我是用的systemd版，今天又遇到一个问题 ，plex或者其他应用在疯狂读区 /xunlei 这个目录的时候会导致本程序挂了
