### ISSUE TITLE
绑定目录 "/dev" -> "/xunlei/dev" 失败

### ISSUE THREAD

**Issue by PangYanze** [cnk3x/xunlei#106]
在ikuai上使用失败。日志内容是：
[syno] 绑定目录 "/dev" -> "/xunlei/dev" 失败: operation not permitted

**Comment by OverS9982** [comment]
开启特权模式运行

**Comment by mazhichang** [comment]
基本对iKuai的docker插件死心了

**Comment by sxyandapp** [comment]
> 基本对iKuai的docker插件死心了

其实ikuai做的没错，特权模式不可能随便给容器开的，开了后容器基本相当于在宿主机运行了
