### ISSUE TITLE
在centos7上使用docker-compose启动，正常启动，但是访问端口报500

### ISSUE THREAD

**Issue by chuwei111** [cnk3x/xunlei#107]
已经在一台虚拟机上部署过，可以正常访问。后又在一台物理机的centos7上部署，网页访问报500。

尝试直接wget，容器内容器外都报500
wget 127.0.0.1:2345
--2023-08-30 09:53:30--  http://127.0.0.1:2345/
正在连接 127.0.0.1:2345... 已连接。
已发出 HTTP 请求，正在等待回应... 307 Temporary Redirect
位置：/webman/3rdparty/pan-xunlei-com/index.cgi/ [跟随至新的 URL]
--2023-08-30 09:53:30--  http://127.0.0.1:2345/webman/3rdparty/pan-xunlei-com/index.cgi/
再次使用存在的到 127.0.0.1:2345 的连接。
已发出 HTTP 请求，正在等待回应... 500 Internal Server Error
2023-08-30 09:53:30 错误 500：Internal Server Error。

其他日志：：
xunlei    | goroutine 1 [running]:
xunlei    | gitlab.xunlei.cn/xlppc/pan-cli/pkg/platformdetect.Platform()
xunlei    | 	/xunlei-pan-cli/pkg/platformdetect/detect.go:47 +0x3e9
xunlei    | main.init.0()
xunlei    | 	/xunlei-pan-cli/package/synology/src/ui/amaze.go:7698 +0xd6a
xunlei    | 2023/08/30 10:23:36 host.go:361: cgi: no headers
xunlei    | 08/30 10:23:40.7 INFO loadenv from /var/packages/pan-xunlei-com/target/ui
xunlei    | 08/30 10:23:40.7 INFO [error={"Op":"open","Path":"/var/packages/pan-xunlei-com/target/ui/envconfig","Err":2}&file=/var/packages/pan-xunlei-com
/target/ui/envconfig]read envconfig failed use defaultxunlei    | 08/30 10:23:40.7 INFO [device_space=&config_path=/data/.drive/]use config
xunlei    | 08/30 10:23:40.7 INFO [device_space=&config_path=/data/.drive/]use config
xunlei    | 08/30 10:23:40.7 INFO [report=true&use_path=/data/.drive/plugins]getPluginPATH
xunlei    | 08/30 10:23:40.7 INFO [device_space=&config_path=/data/.drive/]use config
xunlei    | 08/30 10:23:40.7 INFO setDownloadAlias DriveFileMount :map[]
xunlei    | 08/30 10:23:40.7 INFO config.init getEnvStrArray DownloadPATH:[/迅雷下载] len:1
xunlei    | 08/30 10:23:40.7 INFO config.init init succ: &{isInit:true NasIDKey: NasId: NasSubIdKey: NasSubId: DeviceId: WorkDir: BinPath:/var/packages/pa
n-xunlei-com/target/ui Platform: PathSplit:: DownloadPATHs:[/迅雷下载] TorrentPath: DriveFileMount:map[] PluginTokenDuration:5h0m0s PluginPATH:/data/.drive/plugins AuthTokenPATH: DriveArgs: DrivePlayer: DriveListen:unix:///var/packages/pan-xunlei-com/target/var/pan-xunlei-com.sock DriveLogLevel:info DriveLogFile: DriveLogSize:10MB DriveLogFormat: DriveUpdate: DriveConfigPATH: DrivePIDFile: DriveInfoFile: DrivePublicPort:21603 FreePortRange:[] FreePortRangeUDP:[] LauncherLogFile: LauncherLogSize: LauncherPIDFile: LauncherListen:127.0.0.1:5051 NfoIsDisable: RefreshTokenDuration:1h KvCacheDuration:24h0m0s TaskCfgPath: ScrapeCacheDuration:24h0m0s SyncWatchDogDuration:30m0s CachePATH: DeviceSpace: DeviceName: TLSInsecureSkipVerify:true ImportTask:true SingleTaskMaxMB:100 SingleTaskReserveMB:20 OverallShareMaxMB:200 ThirdAuthURL: PanCliEnv: GeneDBShadowFileDuration:24h DebugPrintFileEvents:[] GossipFile:/data/.drive/gossip.json PluginWithBash:false Webhook:{Modules:map[] URL:} HostXluser:https://xluser-ssl.xunlei.com HostApiPan:https://api-pan.xunlei.com HostShoulei:https://api-shoulei-ssl.xunlei.com HostHighSpeedFlow:https://api-pan.xunlei.com EnableTaskCfg:true}xunlei    | 08/30 10:23:40.7 INFO start detect platform
xunlei    | 08/30 10:23:40.7 ERROR DetectPlatform err:env PLATFORM=lexar:ea94acab567b9cc724e943be3e4ac5c5 not exist name:lexar
xunlei    | 08/30 10:23:40.7 ERROR DetectPlatform err:stat /.dockerenv: no such file or directory name:docker
xunlei    | 08/30 10:23:40.7 ERROR DetectPlatform err:env PLATFORM=zspace:a68b3d890b860d0165a8f6f66acc6d45 not exist name:zspace
xunlei    | 08/30 10:23:40.7 ERROR DetectPlatform err:synology not suport docker name:synology
xunlei    | 08/30 10:23:40.7 ERROR DetectPlatform err:env PLATFORM=hiksemi:985cd73ad6cd84581921672853ef6c5e not exist name:hiksemi
xunlei    | 08/30 10:23:40.7 ERROR DetectPlatform err:env PLATFORM=ugreen:c2fa07c50ad61b50a634a9c25bc40530 not exist name:ugreen
xunlei    | 08/30 10:23:40.7 ERROR DetectPlatform err:env PLATFORM=qnap:71b00dc127a6a78de61e59fd9628efae not exist name:qnap
xunlei    | 08/30 10:23:40.7 ERROR DetectPlatform err:env PLATFORM=terramaster:e3156c4a4774d7efc24bee37564725ea not exist name:terramaster
xunlei    | 08/30 10:23:40.7 ERROR DetectPlatform err:env PLATFORM=lenovo:4c591aaded5306eb667b896eed02e6e6 not exist name:lenovo
xunlei    | 08/30 10:23:40.7 ERROR DetectPlatform err:env PLATFORM=ubuntu:bc519ec4f100ddff5670990978d0e76f not exist name:ubuntu
xunlei    | 08/30 10:23:40.7 ERROR DetectPlatform err:env PLATFORM=huawei:5bdb641fff904f6a2904b6b795504c18 not exist name:huawei
xunlei    | 08/30 10:23:40.7 ERROR DetectPlatform err:env PLATFORM=xcloud:6c9023c15749f4c07f09e8e6a0f78b12 not exist name:xcloud
xunlei    | 08/30 10:23:40.7 ERROR DetectPlatform err:env PLATFORM=macos:973a737d292d1a499a47894e4aa0840d not exist name:macos
xunlei    | 08/30 10:23:40.7 ERROR DetectPlatform err:env PLATFORM=raspbian:5a286a70691e0be2ea2815ff72fbec08 not exist name:raspbian
xunlei    | 08/30 10:23:40.7 ERROR DetectPlatform err:env PLATFORM=linux:afca85945af91c370e2869d3f30ae500 not exist name:linux
xunlei    | 08/30 10:23:40.7 ERROR DetectPlatform err:env PLATFORM=pcxllite:d9813677ef4cd392124cde2fad894953 not exist name:pcxllite
xunlei    | panic: platform not suport:
xunlei    | 
xunlei    | goroutine 1 [running]:
xunlei    | gitlab.xunlei.cn/xlppc/pan-cli/pkg/platformdetect.Platform()
xunlei    | 	/xunlei-pan-cli/pkg/platformdetect/detect.go:47 +0x3e9
xunlei    | main.init.0()
xunlei    | 	/xunlei-pan-cli/package/synology/src/ui/amaze.go:7698 +0xd6a
xunlei    | 2023/08/30 10:23:40 host.go:361: cgi: no headers
xunlei    | 08/30 10:23:44.63 INFO loadenv from /var/packages/pan-xunlei-com/target/ui
xunlei    | 08/30 10:23:44.63 INFO [file=/var/packages/pan-xunlei-com/target/ui/envconfig&error={"Op":"open","Path":"/var/packages/pan-xunlei-com/target/u
i/envconfig","Err":2}]read envconfig failed use defaultxunlei    | 08/30 10:23:44.63 INFO [device_space=&config_path=/data/.drive/]use config
xunlei    | 08/30 10:23:44.63 INFO [device_space=&config_path=/data/.drive/]use config
xunlei    | 08/30 10:23:44.63 INFO [report=true&use_path=/data/.drive/plugins]getPluginPATH
xunlei    | 08/30 10:23:44.63 INFO [device_space=&config_path=/data/.drive/]use config
xunlei    | 08/30 10:23:44.63 INFO setDownloadAlias DriveFileMount :map[]
xunlei    | 08/30 10:23:44.63 INFO config.init getEnvStrArray DownloadPATH:[/迅雷下载] len:1
xunlei    | 08/30 10:23:44.63 INFO config.init init succ: &{isInit:true NasIDKey: NasId: NasSubIdKey: NasSubId: DeviceId: WorkDir: BinPath:/var/packages/p
an-xunlei-com/target/ui Platform: PathSplit:: DownloadPATHs:[/迅雷下载] TorrentPath: DriveFileMount:map[] PluginTokenDuration:5h0m0s PluginPATH:/data/.drive/plugins AuthTokenPATH: DriveArgs: DrivePlayer: DriveListen:unix:///var/packages/pan-xunlei-com/target/var/pan-xunlei-com.sock DriveLogLevel:info DriveLogFile: DriveLogSize:10MB DriveLogFormat: DriveUpdate: DriveConfigPATH: DrivePIDFile: DriveInfoFile: DrivePublicPort:21603 FreePortRange:[] FreePortRangeUDP:[] LauncherLogFile: LauncherLogSize: LauncherPIDFile: LauncherListen:127.0.0.1:5051 NfoIsDisable: RefreshTokenDuration:1h KvCacheDuration:24h0m0s TaskCfgPath: ScrapeCacheDuration:24h0m0s SyncWatchDogDuration:30m0s CachePATH: DeviceSpace: DeviceName: TLSInsecureSkipVerify:true ImportTask:true SingleTaskMaxMB:100 SingleTaskReserveMB:20 OverallShareMaxMB:200 ThirdAuthURL: PanCliEnv: GeneDBShadowFileDuration:24h DebugPrintFileEvents:[] GossipFile:/data/.drive/gossip.json PluginWithBash:false Webhook:{Modules:map[] URL:} HostXluser:https://xluser-ssl.xunlei.com HostApiPan:https://api-pan.xunlei.com HostShoulei:https://api-shoulei-ssl.xunlei.com HostHighSpeedFlow:https://api-pan.xunlei.com EnableTaskCfg:true}xunlei    | 08/30 10:23:44.63 INFO start detect platform
xunlei    | 08/30 10:23:44.63 ERROR DetectPlatform err:env PLATFORM=lexar:ea94acab567b9cc724e943be3e4ac5c5 not exist name:lexar
xunlei    | 08/30 10:23:44.63 ERROR DetectPlatform err:stat /.dockerenv: no such file or directory name:docker
xunlei    | 08/30 10:23:44.63 ERROR DetectPlatform err:env PLATFORM=zspace:a68b3d890b860d0165a8f6f66acc6d45 not exist name:zspace
xunlei    | 08/30 10:23:44.63 ERROR DetectPlatform err:synology not suport docker name:synology
xunlei    | 08/30 10:23:44.63 ERROR DetectPlatform err:env PLATFORM=hiksemi:985cd73ad6cd84581921672853ef6c5e not exist name:hiksemi
xunlei    | 08/30 10:23:44.63 ERROR DetectPlatform err:env PLATFORM=ugreen:c2fa07c50ad61b50a634a9c25bc40530 not exist name:ugreen
xunlei    | 08/30 10:23:44.63 ERROR DetectPlatform err:env PLATFORM=qnap:71b00dc127a6a78de61e59fd9628efae not exist name:qnap
xunlei    | 08/30 10:23:44.63 ERROR DetectPlatform err:env PLATFORM=terramaster:e3156c4a4774d7efc24bee37564725ea not exist name:terramaster
xunlei    | 08/30 10:23:44.63 ERROR DetectPlatform err:env PLATFORM=lenovo:4c591aaded5306eb667b896eed02e6e6 not exist name:lenovo
xunlei    | 08/30 10:23:44.63 ERROR DetectPlatform err:env PLATFORM=ubuntu:bc519ec4f100ddff5670990978d0e76f not exist name:ubuntu
xunlei    | 08/30 10:23:44.63 ERROR DetectPlatform err:env PLATFORM=huawei:5bdb641fff904f6a2904b6b795504c18 not exist name:huawei
xunlei    | 08/30 10:23:44.63 ERROR DetectPlatform err:env PLATFORM=xcloud:6c9023c15749f4c07f09e8e6a0f78b12 not exist name:xcloud
xunlei    | 08/30 10:23:44.63 ERROR DetectPlatform err:env PLATFORM=macos:973a737d292d1a499a47894e4aa0840d not exist name:macos
xunlei    | 08/30 10:23:44.63 ERROR DetectPlatform err:env PLATFORM=raspbian:5a286a70691e0be2ea2815ff72fbec08 not exist name:raspbian
xunlei    | 08/30 10:23:44.63 ERROR DetectPlatform err:env PLATFORM=linux:afca85945af91c370e2869d3f30ae500 not exist name:linux
xunlei    | 08/30 10:23:44.63 ERROR DetectPlatform err:env PLATFORM=pcxllite:d9813677ef4cd392124cde2fad894953 not exist name:pcxllite
xunlei    | panic: platform not suport:
xunlei    | 
xunlei    | goroutine 1 [running]:
xunlei    | gitlab.xunlei.cn/xlppc/pan-cli/pkg/platformdetect.Platform()
xunlei    | 	/xunlei-pan-cli/pkg/platformdetect/detect.go:47 +0x3e9
xunlei    | main.init.0()
xunlei    | 	/xunlei-pan-cli/package/synology/src/ui/amaze.go:7698 +0xd6a
xunlei    | 2023/08/30 10:23:44 host.go:361: cgi: no headers

**Comment by chuwei111** [comment]
version: "3"
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    stdin_open: true
    tty: true
    restart: always
    ports:
      - 9004:8096
    volumes:
      - ./config:/config
      - /nas:/nas
    privileged: true
    extra_hosts:
      - "api.themoviedb.org:52.84.18.87"
      - "image.tmdb.org:84.17.46.53"
      - "www.themoviedb.org:52.84.125.129"
  xunlei:
    image: cnk3x/xunlei:3.4.0
    privileged: true
    container_name: xunlei
    hostname: mynas
##    environment:
##     XL_DEBUG: 1
    ports:
      - 2345:2345
    volumes:
      - ./xunlei:/xunlei/data #data目录
      - /nas:/xunlei/downloads #下载目录
    restart: always
查看日志无果，最后指定了一个3.4.0的版本，成功启动。我用的零几年的2C2G的旧电脑。希望有大佬能帮我一起优化一下配置

**Comment by byl0561** [comment]
自动更新了最新的docker版本，出现了相同的问题。老版本的docker镜像是可用的。
