### ISSUE TITLE
无需 --privileged，添加 SYS_ADMIN 权限即可正常启动，

### ISSUE THREAD

**Issue by wy580477** [cnk3x/xunlei#108]
Podman rootless 环境，加上 --cap-add SYS_ADMIN 即可启动，无需 --privileged 给予范围更广的特权。

理论上 docker 应该也行。

**Comment by cnk3x** [comment]
可以尝试下

**Comment by realabertian** [comment]
除了这个特权模式 ，也没法自定义 用户以及用户组

**Comment by q7091696665** [comment]
在truenas scale下，pod（K8S里的容器）可以在Capabilities下直接添加SYS_ADMIN正常启动，
敏感权限的朋友还是建议虚拟机套娃docker或者干脆换宿主通过SMB之类的挂载下载路径就可以了...
这里记录下作为参考

**Comment by tiny1990** [comment]
podman 和 docker加了 都提示 permission denied

**Comment by sxyandapp** [comment]
ikuai环境，毛权限都加不了
