### ISSUE TITLE
nas小星跑量，但是收益为0

### ISSUE THREAD

**Issue by 346673164** [cnk3x/xunlei#111]
跑量很久，但是没收益。工单回复如下。估计是加了检验。
您好，经核实后台系统未检测到设备类型；当前NAS合作厂商设备类型有如下：群晖、威联通、绿联、极空间、联想、铁威马、华为等，其它厂商设备（含通过其它设备刷机的类型）暂不支持。

**Comment by liwenjie119** [comment]
不知道有没有办法伪装一下 ，伪装成相应设备

**Comment by obanat** [comment]
我跑了两天，收益为零，放弃
简单排查了原因，发现磁盘为空，实际是有>1M的上传下载流量的，所以还是哪个地方适配有问题导致网心云插件没有正确识别到硬盘参数
