### ISSUE TITLE
网页控制台打不开

### ISSUE THREAD

**Issue by Qishi-work** [cnk3x/xunlei#12]
![image](https://user-images.githubusercontent.com/53170479/167822846-6e2a1546-aa34-445d-b3ba-a5559725c509.png)

**Comment by Qishi-work** [comment]
缺少libstdc++.so.6，安装了也不行

**Comment by cnk3x** [comment]
docker 版本还是直装版本？

**Comment by cnk3x** [comment]
已更新，请查看说明重新拉取一下。

https://github.com/cnk3x/xunlei/tree/docker
