### ISSUE TITLE
Docker启动失败

### ISSUE THREAD

**Issue by xxvfx** [cnk3x/xunlei#120]
我的docker运行在arm64上, docker经常启动失败, 大概启动10次, 可能有一次能启动成功, 启动成功后就可以正常使用, 在启动失败时, 我的报错是这样的, 是什么原因引起的

2023/12/22 14:30:11 [忽略] [syno] 源: stat /lib64: no such file or directory
2023/12/22 14:30:11 [忽略] [syno] 源: stat /lib32: no such file or directory
2023/12/22 14:30:11 [忽略] [syno] 源: stat /libx32: no such file or directory
uid=0,gid=0
2023/12/22 14:30:12 [xlp] [启动器] 启动成功: 21
2023/12/22 14:30:12 [xlp] [UI]启动: :2345
2023/12/22 14:30:20 [xlp] [启动器] 结束: signal: killed
2023/12/22 14:30:20 [syno] 卸载目录 "/xunlei/lib64" 失败: no such file or directory
2023/12/22 14:30:20 [syno] 卸载目录 "/xunlei/lib32" 失败: no such file or directory
2023/12/22 14:30:20 [syno] 卸载目录 "/xunlei/libx32" 失败: no such file or directory
2023/12/22 14:30:20 [syno] down: exit status 1

**Comment by sancdvs** [comment]
我也这个问题找不到原因

**Comment by Mrneet** [comment]
我也是这个问题，我家云，装armbian+OMV

**Comment by KnxckbackWili** [comment]
权限要给最高的

**Comment by xxvfx** [comment]
权限已经给到最高了
