### ISSUE TITLE
编译问题

### ISSUE THREAD

**Issue by lxin49** [cnk3x/xunlei#121]
大佬，构建镜像时报错，报错内容如下：
./syno.go:57:18: undefined: SetSysProc
./syno.go:73:12: undefined: Chroot
./syno.go:77:12: undefined: Chdir
./syno.go:97:11: undefined: Mount
./syno.go:104:11: undefined: Unmount
./xlp.go:58:11: undefined: Chdir
./xlp.go:70:18: undefined: SetSysProc
./xlp.go:71:14: undefined: SetUser
GO用的1.18版本，本人GO小白，请教大佬可能是什么原因呢

**Comment by lxin49** [comment]
已通过其他方法解决。如果大佬有时间能对以上问题进行答复，不胜感激。

**Comment by cnk3x** [comment]
你是在windows下编译的吧，需要在Linux下编译。

**Comment by hfpiao** [comment]
xlp/utils_linux.go文件中的第一行unix改成linux就OK了
