### ISSUE TITLE
新部署有问题了，报parent folder not found错误

### ISSUE THREAD

**Issue by PHCSJC** [cnk3x/xunlei#122]
重现步骤：删除docker---删除/opt/xunlei包括隐藏文件---删除下载目录包括隐藏文件---重新部署docker，随便找个magnet，会发现提示parent folder not found错误，等10几秒点重试下载又可以继续下载，再找个magnet还是这样的循环错误

![QQ截图20240118145648](https://github.com/cnk3x/xunlei/assets/22064544/1445ddd4-66d3-4347-9c7e-d68970264b3e)

**Comment by daoyelihuowang** [comment]
一样的情况最新版本还是没有解决默认配置

**Comment by Arufarudo** [comment]
> 一样的情况最新版本还是没有解决默认配置

最后有解决吗？最近从3.7.1升级，结果没想到也碰到了，不是parent folder not found就是not found，但是点击重试就能下载。
