### ISSUE TITLE
大家好，可以使用我编译的更新版本迅雷spk的docker镜像

### ISSUE THREAD

**Issue by stupidloud** [cnk3x/xunlei#126]
我fork的cnk3x的项目
https://github.com/stupidloud/xunlei

镜像地址
https://hub.docker.com/r/kl3x/xunlei

**Comment by zhang-changwei** [comment]
您好，请问如何解决无法显示登录二维码，提示设备校验失败，请重新登陆设备或刷新，拉取的镜像是kl3x/xunlei:latest，感谢！

运行环境：Win11+WSL2+Docker Desktop

**Comment by stupidloud** [comment]
应该是wsl过不了迅雷spk的自检，你在物理服务器或者kvm vps上运行试试，我在三台物理机运行了没有遇到这个问题

**Comment by zhang-changwei** [comment]
好吧，我没有物理linux服务器

**Comment by stupidloud** [comment]
你试试把 privileged: true 改成 false

**Comment by zhang-changwei** [comment]
还是不行，会提示[syno] 绑定目录 "/dev" -> "/xunlei/dev" 失败: operation not permitted

**Comment by yuluod** [comment]
> 我fork的cnk3x的项目 https://github.com/stupidloud/xunlei
> 
> 镜像地址 https://hub.docker.com/r/kl3x/xunlei

感谢，解决了下载失败的问题。

**Comment by yuluod** [comment]
目前发现无法添加超过六七个的链接，并且有时添加两个下载任务之后，会不显示。

**Comment by meimingziyongle** [comment]
你好，请问这个版本有解决nas挂载目录容量识别的问题吗

**Comment by sxyandapp** [comment]
楼主，你的也报这个错：绑定目录 "/dev" -> "/xunlei/dev" 失败: operation not permitted

**Comment by sxyandapp** [comment]
报错：panic: platform not suport  ，使用的x86机器

**Comment by latel** [comment]
如何设置uid和pid啊，我设置了XL_UID和XL_PID，下载下来的文件还是root
