### ISSUE TITLE
玩客云 docker安装迅雷报错 docker: no matching manifest for linux/arm/v7 in the manifest list entries.

### ISSUE THREAD

**Issue by woodhead66** [cnk3x/xunlei#127]
玩客云刷casaos后，从docker 安装迅雷，报错 docker: no matching manifest for linux/arm/v7 in the manifest list entries.

docker run -d --name=xunlei --hostname=mynas --net=host -v /mnt/sdb1/xunlei:/xunlei/data -v /mnt/sdb1/downloads:/xunlei/downloads --restart=unless-stopped --privileged cnk3x/xunlei:latest

**Comment by rainbamboo2020** [comment]
me too, how to resolve it?

**Comment by NiceAshin** [comment]
cnk3x/xunlei  is not support armv7
