### ISSUE TITLE
一定要内测码吗

### ISSUE THREAD

**Issue by 1136623363** [cnk3x/xunlei#13]

**Comment by 1136623363** [comment]
内测码是：迅雷牛通

**Comment by 1136623363** [comment]
![image](https://user-images.githubusercontent.com/72068332/169644203-0a74f8fa-978c-4c79-9c23-ee28f35ad218.png)

**Comment by 1136623363** [comment]
但是无法下载，不知哪里问题

**Comment by cnk3x** [comment]
已更新，请查看说明重新拉取一下。

https://github.com/cnk3x/xunlei/tree/docker
