### ISSUE TITLE
安装和启动都成功了，但是打开网页是空白页

### ISSUE THREAD

**Issue by curryhendry** [cnk3x/xunlei#130]
端口啥的都对，192.168.31.200:2345，空白一片，地址也自动更新到了http://192.168.31.200:2345/webman/3rdparty/pan-xunlei-com/index.cgi/

**Comment by curryhendry** [comment]
选择超级QNAP管理后好了，不过还想请问，我是在QNAP上安装的，已经可以正常下载了。我如何才能把下载路径自定义为NAS的其他目录，好像设定权限什么的都不好使，只能在容器中。

**Comment by cnk3x** [comment]
qnap有官方的应用，何苦还要用这个。

**Comment by curryhendry** [comment]
> qnap有官方的应用，何苦还要用这个。

官方只有x86

**Comment by cnk3x** [comment]
> 选择超级QNAP管理后好了，不过还想请问，我是在QNAP上安装的，已经可以正常下载了。我如何才能把下载路径自定义为NAS的其他目录，好像设定权限什么的都不好使，只能在容器中。

容器内，通过挂载多个路径到容器，迅雷会自动判断自己有权限的挂载点来提供选择下载保存位置。默认的下载保存路径是通过 XL_DIR_DOWNLOAD环境变量来设定，默认为 /xunlei/downloads，你把宿主机上任意一个目录挂载到容器这个位置。 也可以多挂载几个其他目录到容器内，在迅雷有写入权限的情况下，下载时可以选择的。

**Comment by curryhendry** [comment]
> > 选择超级QNAP管理后好了，不过还想请问，我是在QNAP上安装的，已经可以正常下载了。我如何才能把下载路径自定义为NAS的其他目录，好像设定权限什么的都不好使，只能在容器中。
> 
> 容器内，通过挂载多个路径到容器，迅雷会自动判断自己有权限的挂载点来提供选择下载保存位置。默认的下载保存路径是通过 XL_DIR_DOWNLOAD环境变量来设定，默认为 /xunlei/downloads，你把宿主机上任意一个目录挂载到容器这个位置。 也可以多挂载几个其他目录到容器内，在迅雷有写入权限的情况下，下载时可以选择的。

小白用户研究了两天终于搞定了哈哈，主要卡在了我是通过cnk3x/xunlei:latest获取镜像，无法运行，提示不兼容，arm64，后来下载了3.7.1才好。目前目录也搞定了，多谢！！（如果适配能再多一些更好哈）

**Comment by jhyeguang** [comment]
> > > 选择超级QNAP管理后好了，不过还想请问，我是在QNAP上安装的，已经可以正常下载了。我如何才能把下载路径自定义为NAS的其他目录，好像设定权限什么的都不好使，只能在容器中。
> > 
> > 
> > 容器内，通过挂载多个路径到容器，迅雷会自动判断自己有权限的挂载点来提供选择下载保存位置。默认的下载保存路径是通过 XL_DIR_DOWNLOAD环境变量来设定，默认为 /xunlei/downloads，你把宿主机上任意一个目录挂载到容器这个位置。 也可以多挂载几个其他目录到容器内，在迅雷有写入权限的情况下，下载时可以选择的。
> 
> 小白用户研究了两天终于搞定了哈哈，主要卡在了我是通过cnk3x/xunlei:latest获取镜像，无法运行，提示不兼容，arm64，后来下载了3.7.1才好。目前目录也搞定了，多谢！！（如果适配能再多一些更好哈）

请问一下，3.71是怎么下载

**Comment by curryhendry** [comment]
> > > > 选择超级QNAP管理后好了，不过还想请问，我是在QNAP上安装的，已经可以正常下载了。我如何才能把下载路径自定义为NAS的其他目录，好像设定权限什么的都不好使，只能在容器中。
> > > 
> > > 
> > > 容器内，通过挂载多个路径到容器，迅雷会自动判断自己有权限的挂载点来提供选择下载保存位置。默认的下载保存路径是通过 XL_DIR_DOWNLOAD环境变量来设定，默认为 /xunlei/downloads，你把宿主机上任意一个目录挂载到容器这个位置。 也可以多挂载几个其他目录到容器内，在迅雷有写入权限的情况下，下载时可以选择的。
> > 
> > 
> > 小白用户研究了两天终于搞定了哈哈，主要卡在了我是通过cnk3x/xunlei:latest获取镜像，无法运行，提示不兼容，arm64，后来下载了3.7.1才好。目前目录也搞定了，多谢！！（如果适配能再多一些更好哈）
> 
> 请问一下，3.71是怎么下载

我是用的qnap里自带的container station，可以选择版本。 代码什么的获取就是cnk3x/xunlei:3.7.1

**Comment by KirsOus** [comment]
cnk3x/xunlei:3.7.1

**Comment by cnk3x** [comment]
最新的版本已经覆盖更新了，可以重新拉取试试。
