### ISSUE TITLE
安装和启动都成功了，但是打开网页是空白页.

### ISSUE THREAD

**Issue by xiaofeizhu1995** [cnk3x/xunlei#131]
unraid系统，启用了特权，x86机型。日志显示
2024/05/01 03:46:47 [xlp] [启动器] 启动成功: 20
2024/05/01 03:46:47 [xlp] [UI]启动: :4231
uid=0,gid=0
但打开网址失败，跳转到了http://192.168.1.111:4231/webman/3rdparty/pan-xunlei-com/index.cgi/这个地址，失败，网址空白。

**Comment by xiaofeizhu1995** [comment]
删掉数据目录重新起一次就好了。

**Comment by chevy222** [comment]
> 删掉数据目录重新起一次就好了。

哪个目录啊，请问一下。
