### ISSUE TITLE
arm64启动报错

### ISSUE THREAD

**Issue by SheriffChen** [cnk3x/xunlei#135]
version: 3.11.2
time="05/12 17:49:54" level=info msg="exited: unsupported platform: linux arm64"

镜像描述：
"Created": "2024-05-12T01:13:17.3033633Z",
"DockerVersion": "",
        "Architecture": "arm64",
        "Os": "linux",
        "Size": 94978197,
        "VirtualSize": 94978197,

**Comment by frankiezdh** [comment]
@cnk3x 大佬fix一下？

**Comment by yb9210** [comment]
istoreos内一样启动报错，不获取网络

**Comment by cnk3x** [comment]
24/05/22之前的latest确认有问题，现在更新了，可以尝试一下，不过arm64没有设备没测试。

**Comment by konglh80** [comment]
在 arm64 设备上拉取了最新版本，目前遇到的问题是卡在登录页面，一直显示 “二维码加载中...“，过一会会提示错误 “设备校验失败，请重新登录设备或刷新”
<img width="665" alt="Screenshot 2024-05-23 at 16 28 15" src="https://github.com/cnk3x/xunlei/assets/8278967/91a86777-3384-4884-bee4-f31d98bdcf2c">

**Comment by cnk3x** [comment]
可以把容器运行输出的日志贴出来看一下吗

**Comment by konglh80** [comment]
运行日志

stderr: [2m05/24 09:27:21[0m [92mINF[0m run [2mmode=[0mfork
stderr: [2m05/24 09:27:21[0m [92mINF[0m proot init [2mroot=[0m/xunlei
stderr: [2m05/24 09:27:21[0m [93mWRN[0m bind [2msrc=[0m/lib32 [2merr=[0m"stat /lib32: no such file or directory"
stderr: [2m05/24 09:27:21[0m [93mWRN[0m bind [2msrc=[0m/libx32 [2merr=[0m"stat /libx32: no such file or directory"
stderr: [2m05/24 09:27:21[0m [93mWRN[0m bind [2msrc=[0m/lib64 [2merr=[0m"stat /lib64: no such file or directory"
stderr: [2m05/24 09:27:21[0m [92mINF[0m fork [2mroot=[0m/xunlei [2mcommand=[0m/usr/bin/xlp
stderr: [2m05/24 09:27:21[0m [92mINF[0m fork [2mpid=[0m13
stderr: [2m05/24 09:27:21[0m [92mINF[0m run [2mmode=[0mchroot
stderr: [2m05/24 09:27:21[0m [92mINF[0m _  _ _  _ _  _ _    ____  _
stderr: [2m05/24 09:27:21[0m [92mINF[0m  \/  |  | |\ | |    |___  |
stderr: [2m05/24 09:27:21[0m [92mINF[0m _/\_ |__| | \| |___ |___  |
stderr: [2m05/24 09:27:21[0m [92mINF[0m daemon version: v3.11.2
stderr: [2m05/24 09:27:21[0m [92mINF[0m spk version: v3.11.2
stderr: [2m05/24 09:27:21[0m [92mINF[0m 
stderr: [2m05/24 09:27:21[0m [92mINF[0m Config
stderr: [2m05/24 09:27:21[0m [92mINF[0m   - DashboardPort:     2345
stderr: [2m05/24 09:27:21[0m [92mINF[0m   - DashboardUsername: none
stderr: [2m05/24 09:27:21[0m [92mINF[0m   - DashboardPassword: none
stderr: [2m05/24 09:27:21[0m [92mINF[0m   - DownloadPath:      /xunlei/downloads
stderr: [2m05/24 09:27:21[0m [92mINF[0m   - DataPath:          /xunlei/data
stderr: [2m05/24 09:27:21[0m [92mINF[0m   - Debug:             false
stderr: [2m05/24 09:27:21[0m [92mINF[0m   - NewRoot:           /xunlei
stderr: [2m05/24 09:27:21[0m [92mINF[0m Environ
stderr: [2m05/24 09:27:21[0m [92mINF[0m   - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
stderr: [2m05/24 09:27:21[0m [92mINF[0m   - HOSTNAME=e07a0ff4d39a
stderr: [2m05/24 09:27:21[0m [92mINF[0m   - LANG=zh_CN.UTF-8
stderr: [2m05/24 09:27:21[0m [92mINF[0m   - LANGUAGE=zh_CN.UTF-8
stderr: [2m05/24 09:27:21[0m [92mINF[0m   - LC_ALL=C
stderr: [2m05/24 09:27:21[0m [92mINF[0m   - XL_DASHBOARD_PORT=2345
stderr: [2m05/24 09:27:21[0m [92mINF[0m   - XL_DEBUG=false
stderr: [2m05/24 09:27:21[0m [92mINF[0m   - XL_CHROOT=/xunlei
stderr: [2m05/24 09:27:21[0m [92mINF[0m   - HOME=/var/packages/pan-xunlei-com/shares/迅雷/.drive
stderr: [2m05/24 09:27:21[0m [92mINF[0m   - XL_DIR_DOWNLOAD=/xunlei/downloads
stderr: [2m05/24 09:27:21[0m [92mINF[0m   - XL_DIR_DATA=/xunlei/data
stderr: [2m05/24 09:27:21[0m [92mINF[0m   - RUN_WITH_CHROOT=/xunlei
stderr: [2m05/24 09:27:21[0m [92mINF[0m   - SYNOPLATFORM=rtd1296
stderr: [2m05/24 09:27:21[0m [92mINF[0m   - SYNOPKG_PKGNAME=pan-xunlei-com
stderr: [2m05/24 09:27:21[0m [92mINF[0m   - SYNOPKG_PKGVER=3.11.2
stderr: [2m05/24 09:27:21[0m [92mINF[0m   - SYNOPKG_PKGDEST=/var/packages/pan-xunlei-com/target
stderr: [2m05/24 09:27:21[0m [92mINF[0m   - SYNOPKG_DSM_VERSION_MAJOR=7
stderr: [2m05/24 09:27:21[0m [92mINF[0m   - SYNOPKG_DSM_VERSION_MINOR=2
stderr: [2m05/24 09:27:21[0m [92mINF[0m   - SYNOPKG_DSM_VERSION_BUILD=64570
stderr: [2m05/24 09:27:21[0m [92mINF[0m   - DriveListen=unix:///var/packages/pan-xunlei-com/target/var/pan-xunlei-com.sock
stderr: [2m05/24 09:27:21[0m [92mINF[0m   - PLATFORM=群晖
stderr: [2m05/24 09:27:21[0m [92mINF[0m   - OS_VERSION=rtd1296 dsm 7.2-64570
stderr: [2m05/24 09:27:21[0m [92mINF[0m   - ConfigPath=/var/packages/pan-xunlei-com/shares/迅雷/
stderr: [2m05/24 09:27:21[0m [92mINF[0m   - DownloadPATH=/var/packages/pan-xunlei-com/shares/迅雷/下载
stderr: [2m05/24 09:27:21[0m [92mINF[0m   - TLSInsecureSkipVerify=true
stderr: [2m05/24 09:27:21[0m [92mINF[0m   - GIN_MODE=release
stderr: [2m05/24 09:27:21[0m [93mWRN[0m /usr/syno/synoman/webman/modules/authenticate.cgi has exist, ignore write
stderr: [2m05/24 09:27:21[0m [93mWRN[0m /etc/synoinfo.conf has exist, ignore write
stderr: [2m05/24 09:27:21[0m [92mINF[0m syno mock [2maddr=[0m:2345
stderr: [2m05/24 09:27:21[0m [92mINF[0m xunlei-pan-cli-launcher.arm64 start [2mcmd=[0m"/var/packages/pan-xunlei-com/target/bin/bin/xunlei-pan-cli-launcher.arm64 -launcher_listen unix:///var/packages/pan-xunlei-com/target/var/pan-xunlei-com-launcher.sock -pid /var/packages/pan-xunlei-com/target/var/pan-xunlei-com.pid -logfile /var/packages/pan-xunlei-com/shares/迅雷/.drive/log-launcher.log -logsize 1MB"
stderr: [2m05/24 09:27:21[0m [92mINF[0m xunlei-pan-cli-launcher.arm64 started [2mpid=[0m21
stderr: [2m05/24 09:27:21[0m [93mWRN[0m [xunlei-pan-cli-launcher.arm64.2] check process get cmdline: open /proc/23/cmdline: no such file or directory
stderr: [2m05/24 09:27:25[0m [91mERR[0m [xunlei-pan-cli-launcher.arm64.2] loadHistory ReadFile err:open /var/packages/pan-xunlei-com/shares/迅雷/.drive/bin/.history: no such file or directory path:/var/packages/pan-xunlei-com/shares/迅雷/.drive/bin/.history
stderr: [2m05/24 09:27:25[0m [91mERR[0m [xunlei-pan-cli-launcher.arm64.2] killPid process.Signal SIGABRT err:os: process already finished
stderr: [2m05/24 09:27:25[0m [93mWRN[0m [xunlei-pan-cli-launcher.arm64.2] kill process error:os: process already finished
stderr: 05/24 09:27:32.73 INFO loadenv from /var/packages/pan-xunlei-com/target/ui
stderr: 05/24 09:27:32.73 INFO [file=/var/packages/pan-xunlei-com/target/ui/envconfig&error={"Op":"open","Path":"/var/packages/pan-xunlei-com/target/ui/envconfig","Err":2}]read envconfig failed use default
stderr: 05/24 09:27:32.73 INFO getEnvs succ DownloadPATH=/var/packages/pan-xunlei-com/shares/迅雷/下载
stderr: 05/24 09:27:32.73 INFO getEnvs succ DriveListen=unix:///var/packages/pan-xunlei-com/target/var/pan-xunlei-com.sock
stderr: 05/24 09:27:32.74 INFO getEnvs succ PLATFORM=群晖
stderr: 05/24 09:27:32.74 INFO getEnvs succ ConfigPath=/var/packages/pan-xunlei-com/shares/迅雷/
stderr: 05/24 09:27:32.74 INFO getEnvs succ TLSInsecureSkipVerify=true
stderr: 05/24 09:27:32.74 INFO [device_space=&config_path=/var/packages/pan-xunlei-com/shares/迅雷/.drive/]use config
stderr: 05/24 09:27:32.74 INFO [device_space=&config_path=/var/packages/pan-xunlei-com/shares/迅雷/.drive/]use config
stderr: 05/24 09:27:32.74 INFO [report=true&use_path=/var/packages/pan-xunlei-com/shares/迅雷/.drive/plugins]getPluginPATH
stderr: 05/24 09:27:32.74 INFO [device_space=&config_path=/var/packages/pan-xunlei-com/shares/迅雷/.drive/]use config
stderr: 05/24 09:27:32.74 INFO setDownloadAlias DriveFileMount :map[]
stderr: 05/24 09:27:32.74 INFO config.init getEnvStrArray DownloadPATH:[/var/packages/pan-xunlei-com/shares/迅雷/下载] len:1
stderr: 05/24 09:27:32.74 INFO config.init init succ: &{isInit:true NasIDKey: NasId: NasSubIdKey: NasSubId: DeviceId: WorkDir: BinPath:/var/packages/pan-xunlei-com/target/ui Platform:群晖 PathSplit:: DownloadPATHs:[/var/packages/pan-xunlei-com/shares/迅雷/下载] TorrentPath: DriveFileMount:map[] PluginTokenDuration:5h0m0s PluginPATH:/var/packages/pan-xunlei-com/shares/迅雷/.drive/plugins AuthTokenPATH: DriveArgs: DrivePlayer: DriveListen:unix:///var/packages/pan-xunlei-com/target/var/pan-xunlei-com.sock DrivePortFile: DriveLogLevel:info DriveLogFile: DriveLogSize:10MB DriveLogFormat: DriveUpdate: DriveConfigPATH:/var/packages/pan-xunlei-com/shares/迅雷/ DrivePIDFile: DriveInfoFile: DrivePublicPort:21603 FreePortRange:[] FreePortRangeUDP:[] LauncherLogFile: LauncherLogSize: LauncherPIDFile: LauncherListen:127.0.0.1:5051 NfoIsDisable: RefreshTokenDuration:1h KvCacheDuration:24h0m0s TaskCfgPath: ScrapeCacheDuration:24h0m0s SyncWatchDogDuration:30m0s CachePATH: DeviceSpace: DeviceName: TLSInsecureSkipVerify:true ImportTask:true SingleTaskMaxMB:100 SingleTaskReserveMB:20 OverallShareMaxMB:200 ThirdAuthURL: PanCliEnv: GeneDBShadowFileDuration:24h DebugPrintFileEvents:[] GossipFile:/var/packages/pan-xunlei-com/shares/迅雷/.drive/gossip.json PluginWithBash:false Webhook:{Modules:map[] URL:} HostXluser:https://xluser-ssl.xunlei.com HostApiPan:https://api-pan.xunlei.com HostShoulei:https://api-shoulei-ssl.xunlei.com HostHighSpeedFlow:https://api-pan.xunlei.com EnableTaskCfg:true WebhookHealthzToken:}
stderr: 05/24 09:27:32.74 INFO start detect platform
stderr: 05/24 09:27:32.74 INFO Detector.Detect envPlatform:群晖
stderr: 05/24 09:27:32.74 INFO detect platform: synology X9ibISwpIp8jQ4Ya nasid: labels: [withQrcodeLogin withOtherAuthLogin withPlugin withPreviewPrivilege allowUseConfigPathAsCachePath withRootDiskSelect withInstallLocalPlugin withHighSpeedFlowCtrl withFetchFolder withSyncDriveFile withUserResetScrapeResult]
stderr: 05/24 09:27:33.01 INFO loadenv from /var/packages/pan-xunlei-com/target/ui
stderr: 05/24 09:27:33.01 INFO [error={"Op":"open","Path":"/var/packages/pan-xunlei-com/target/ui/envconfig","Err":2}&file=/var/packages/pan-xunlei-com/target/ui/envconfig]read envconfig failed use default
stderr: 05/24 09:27:33.01 INFO getEnvs succ DownloadPATH=/var/packages/pan-xunlei-com/shares/迅雷/下载
stderr: 05/24 09:27:33.01 INFO getEnvs succ DriveListen=unix:///var/packages/pan-xunlei-com/target/var/pan-xunlei-com.sock
stderr: 05/24 09:27:33.01 INFO getEnvs succ PLATFORM=群晖
stderr: 05/24 09:27:33.01 INFO getEnvs succ ConfigPath=/var/packages/pan-xunlei-com/shares/迅雷/
stderr: 05/24 09:27:33.01 INFO getEnvs succ TLSInsecureSkipVerify=true
stderr: 05/24 09:27:33.01 INFO [config_path=/var/packages/pan-xunlei-com/shares/迅雷/.drive/&device_space=]use config
stderr: 05/24 09:27:33.01 INFO [device_space=&config_path=/var/packages/pan-xunlei-com/shares/迅雷/.drive/]use config
stderr: 05/24 09:27:33.02 INFO [report=true&use_path=/var/packages/pan-xunlei-com/shares/迅雷/.drive/plugins]getPluginPATH
stderr: 05/24 09:27:33.02 INFO [device_space=&config_path=/var/packages/pan-xunlei-com/shares/迅雷/.drive/]use config
stderr: 05/24 09:27:33.02 INFO setDownloadAlias DriveFileMount :map[]
stderr: 05/24 09:27:33.02 INFO config.init getEnvStrArray DownloadPATH:[/var/packages/pan-xunlei-com/shares/迅雷/下载] len:1
stderr: 05/24 09:27:33.02 INFO config.init init succ: &{isInit:true NasIDKey: NasId: NasSubIdKey: NasSubId: DeviceId: WorkDir: BinPath:/var/packages/pan-xunlei-com/target/ui Platform:群晖 PathSplit:: DownloadPATHs:[/var/packages/pan-xunlei-com/shares/迅雷/下载] TorrentPath: DriveFileMount:map[] PluginTokenDuration:5h0m0s PluginPATH:/var/packages/pan-xunlei-com/shares/迅雷/.drive/plugins AuthTokenPATH: DriveArgs: DrivePlayer: DriveListen:unix:///var/packages/pan-xunlei-com/target/var/pan-xunlei-com.sock DrivePortFile: DriveLogLevel:info DriveLogFile: DriveLogSize:10MB DriveLogFormat: DriveUpdate: DriveConfigPATH:/var/packages/pan-xunlei-com/shares/迅雷/ DrivePIDFile: DriveInfoFile: DrivePublicPort:21603 FreePortRange:[] FreePortRangeUDP:[] LauncherLogFile: LauncherLogSize: LauncherPIDFile: LauncherListen:127.0.0.1:5051 NfoIsDisable: RefreshTokenDuration:1h KvCacheDuration:24h0m0s TaskCfgPath: ScrapeCacheDuration:24h0m0s SyncWatchDogDuration:30m0s CachePATH: DeviceSpace: DeviceName: TLSInsecureSkipVerify:true ImportTask:true SingleTaskMaxMB:100 SingleTaskReserveMB:20 OverallShareMaxMB:200 ThirdAuthURL: PanCliEnv: GeneDBShadowFileDuration:24h DebugPrintFileEvents:[] GossipFile:/var/packages/pan-xunlei-com/shares/迅雷/.drive/gossip.json PluginWithBash:false Webhook:{Modules:map[] URL:} HostXluser:https://xluser-ssl.xunlei.com HostApiPan:https://api-pan.xunlei.com HostShoulei:https://api-shoulei-ssl.xunlei.com HostHighSpeedFlow:https://api-pan.xunlei.com EnableTaskCfg:true WebhookHealthzToken:}
stderr: 05/24 09:27:33.02 INFO start detect platform
stderr: 05/24 09:27:33.02 INFO Detector.Detect envPlatform:群晖
stderr: 05/24 09:27:33.02 INFO detect platform: synology X9ibISwpIp8jQ4Ya nasid: labels: [withQrcodeLogin withOtherAuthLogin withPlugin withPreviewPrivilege allowUseConfigPathAsCachePath withRootDiskSelect withInstallLocalPlugin withHighSpeedFlowCtrl withFetchFolder withSyncDriveFile withUserResetScrapeResult]
stderr: 05/24 09:27:33.08 INFO loadenv from /var/packages/pan-xunlei-com/target/ui
stderr: 05/24 09:27:33.08 INFO [error={"Op":"open","Path":"/var/packages/pan-xunlei-com/target/ui/envconfig","Err":2}&file=/var/packages/pan-xunlei-com/target/ui/envconfig]read envconfig failed use default
stderr: 05/24 09:27:33.08 INFO getEnvs succ DownloadPATH=/var/packages/pan-xunlei-com/shares/迅雷/下载
stderr: 05/24 09:27:33.08 INFO getEnvs succ DriveListen=unix:///var/packages/pan-xunlei-com/target/var/pan-xunlei-com.sock
stderr: 05/24 09:27:33.08 INFO getEnvs succ PLATFORM=群晖
stderr: 05/24 09:27:33.08 INFO getEnvs succ ConfigPath=/var/packages/pan-xunlei-com/shares/迅雷/
stderr: 05/24 09:27:33.08 INFO getEnvs succ TLSInsecureSkipVerify=true
stderr: 05/24 09:27:33.08 INFO [config_path=/var/packages/pan-xunlei-com/shares/迅雷/.drive/&device_space=]use config
stderr: 05/24 09:27:33.08 INFO [config_path=/var/packages/pan-xunlei-com/shares/迅雷/.drive/&device_space=]use config
stderr: 05/24 09:27:33.08 INFO [report=true&use_path=/var/packages/pan-xunlei-com/shares/迅雷/.drive/plugins]getPluginPATH
stderr: 05/24 09:27:33.08 INFO [device_space=&config_path=/var/packages/pan-xunlei-com/shares/迅雷/.drive/]use config
stderr: 05/24 09:27:33.08 INFO setDownloadAlias DriveFileMount :map[]
stderr: 05/24 09:27:33.08 INFO config.init getEnvStrArray DownloadPATH:[/var/packages/pan-xunlei-com/shares/迅雷/下载] len:1
stderr: 05/24 09:27:33.09 INFO config.init init succ: &{isInit:true NasIDKey: NasId: NasSubIdKey: NasSubId: DeviceId: WorkDir: BinPath:/var/packages/pan-xunlei-com/target/ui Platform:群晖 PathSplit:: DownloadPATHs:[/var/packages/pan-xunlei-com/shares/迅雷/下载] TorrentPath: DriveFileMount:map[] PluginTokenDuration:5h0m0s PluginPATH:/var/packages/pan-xunlei-com/shares/迅雷/.drive/plugins AuthTokenPATH: DriveArgs: DrivePlayer: DriveListen:unix:///var/packages/pan-xunlei-com/target/var/pan-xunlei-com.sock DrivePortFile: DriveLogLevel:info DriveLogFile: DriveLogSize:10MB DriveLogFormat: DriveUpdate: DriveConfigPATH:/var/packages/pan-xunlei-com/shares/迅雷/ DrivePIDFile: DriveInfoFile: DrivePublicPort:21603 FreePortRange:[] FreePortRangeUDP:[] LauncherLogFile: LauncherLogSize: LauncherPIDFile: LauncherListen:127.0.0.1:5051 NfoIsDisable: RefreshTokenDuration:1h KvCacheDuration:24h0m0s TaskCfgPath: ScrapeCacheDuration:24h0m0s SyncWatchDogDuration:30m0s CachePATH: DeviceSpace: DeviceName: TLSInsecureSkipVerify:true ImportTask:true SingleTaskMaxMB:100 SingleTaskReserveMB:20 OverallShareMaxMB:200 ThirdAuthURL: PanCliEnv: GeneDBShadowFileDuration:24h DebugPrintFileEvents:[] GossipFile:/var/packages/pan-xunlei-com/shares/迅雷/.drive/gossip.json PluginWithBash:false Webhook:{Modules:map[] URL:} HostXluser:https://xluser-ssl.xunlei.com HostApiPan:https://api-pan.xunlei.com HostShoulei:https://api-shoulei-ssl.xunlei.com HostHighSpeedFlow:https://api-pan.xunlei.com EnableTaskCfg:true WebhookHealthzToken:}

**Comment by i36lib** [comment]
树莓派5(arm64)运行有一些警告和错误：

启动脚本：
```shell
docker run -v /data/xunlei/config:/xunlei/data -v /data/movies:/xunlei/downloads -p 2345:2345 --privileged cnk3x/xunlei:latest
```

错误日志：
```shell
05/25 12:31:19 WRN bind src=/lib32 err="stat /lib32: no such file or directory"
05/25 12:31:19 WRN bind src=/libx32 err="stat /libx32: no such file or directory"
05/25 12:31:19 WRN bind src=/lib64 err="stat /lib64: no such file or directory"

05/25 12:31:19 ERR [xunlei-pan-cli-launcher.arm64.2] loadHistory ReadFile err:open /var/packages/pan-xunlei-com/shares/迅雷/.drive/bin/.history: no such file or directory path:/var/packages/pan-xunlei-com/shares/迅雷/.drive/bin/.history
05/25 12:31:19 ERR [xunlei-pan-cli-launcher.arm64.2] KillDrivePid ioutil.ReadFile err:open /var/packages/pan-xunlei-com/target/var/pan-xunlei-com.pid.child: no such file or directory
05/25 12:31:19 WRN [xunlei-pan-cli-launcher.arm64.2] kill process error:open /var/packages/pan-xunlei-com/target/var/pan-xunlei-com.pid.child: no such file or directory
```

**Comment by bigmangos** [comment]
同样的问题，加载不出二维码

**Comment by YingcaiDong** [comment]
> 树莓派5(arm64)运行有一些警告和错误：
> 
> 启动脚本：
> 
> ```shell
> docker run -v /data/xunlei/config:/xunlei/data -v /data/movies:/xunlei/downloads -p 2345:2345 --privileged cnk3x/xunlei:latest
> ```
> 
> 错误日志：
> 
> ```shell
> 05/25 12:31:19 WRN bind src=/lib32 err="stat /lib32: no such file or directory"
> 05/25 12:31:19 WRN bind src=/libx32 err="stat /libx32: no such file or directory"
> 05/25 12:31:19 WRN bind src=/lib64 err="stat /lib64: no such file or directory"
> 
> 05/25 12:31:19 ERR [xunlei-pan-cli-launcher.arm64.2] loadHistory ReadFile err:open /var/packages/pan-xunlei-com/shares/迅雷/.drive/bin/.history: no such file or directory path:/var/packages/pan-xunlei-com/shares/迅雷/.drive/bin/.history
> 05/25 12:31:19 ERR [xunlei-pan-cli-launcher.arm64.2] KillDrivePid ioutil.ReadFile err:open /var/packages/pan-xunlei-com/target/var/pan-xunlei-com.pid.child: no such file or directory
> 05/25 12:31:19 WRN [xunlei-pan-cli-launcher.arm64.2] kill process error:open /var/packages/pan-xunlei-com/target/var/pan-xunlei-com.pid.child: no such file or directory
> ```

同样的报错+1

**Comment by konglh80** [comment]
加载不出二维码的问题我这边解决了，网络模式用 host，但这样就不能指定端口了。
```shell
docker run -d --network host -v /mnt/mmcblk0p6/xunlei3200/data:/xunlei/data -v /mnt/mmcblk0p6/xunlei3200/downloads:/xunlei/downloads --name xunlei-3.20.0 --privileged cnk3x/xunlei:latest
```

**Comment by cnk3x** [comment]
> 加载不出二维码的问题我这边解决了，网络模式用 host，但这样就不能指定端口了。
> 
> ```shell
> docker run -d --network host -v /mnt/mmcblk0p6/xunlei3200/data:/xunlei/data -v /mnt/mmcblk0p6/xunlei3200/downloads:/xunlei/downloads --name xunlei-3.20.0 --privileged cnk3x/xunlei:latest
> ```

可以用环境变量 XL_DASHBOARD_PORT 来指定端口

```shell
docker run -d --network host -e XL_DASHBOARD_PORT 5432 -v /mnt/mmcblk0p6/xunlei3200/data:/xunlei/data -v /mnt/mmcblk0p6/xunlei3200/downloads:/xunlei/downloads --name xunlei-3.20.0 --privileged cnk3x/xunlei:latest
```
