### ISSUE TITLE
 'XL_DASHBOARD_USER  #网页访问的用户名 XL_DASHBOARD_PASSWORD  #网页访问的密码

### ISSUE THREAD

**Issue by yb9210** [cnk3x/xunlei#136]
账号密码输入进不去，一直停留在输入密码界面

**Comment by yb9210** [comment]
unraid里面docker运行，x86

**Comment by byl0561** [comment]
看了下最新的镜像，XL_DASHBOARD_USER要改成XL_DASHBOARD_USERNAME

**Comment by byl0561** [comment]
我这边最新的镜像，网页打不开，已经回退到老版本了

**Comment by cnk3x** [comment]
latest 更新了，可以尝试一下

> 看了下最新的镜像，XL_DASHBOARD_USER要改成XL_DASHBOARD_USERNAME

笔误，应该是 XL_DASHBOARD_USERNAME
