### ISSUE TITLE
最新版的dockerhub上的迅雷镜像好像不能使用

### ISSUE THREAD

**Issue by mainhope-main** [cnk3x/xunlei#137]
最新版的dockerhub上的迅雷镜像好像不能使用，部署正常，通过链接访问的时候 HTTP 500.   

使用3.7.1版的镜像正常使用。

**Comment by libai1376666** [comment]
我也出现了这样的情况

**Comment by cnk3x** [comment]
2024/05/22之前3.11.2的拉取确认有问题，已经覆盖更新了，可以重新拉取试试。
