### ISSUE TITLE
新版本在unraid docker中的uid gid权限问题

### ISSUE THREAD

**Issue by ybjopq007** [cnk3x/xunlei#138]
3.11.2在unraid docekr 新版本uid gid 无效 已经更改uid gid 但是下载文件的权限还是root 导致smb用户无法更改删除文件

**Comment by feiyulu** [comment]
It seems to be the case. I was able to mount the Unraid directory into /xunlei/downloads/, but xunlei couldn't read the content of the directory.

**Comment by wzyjscz** [comment]
同样的问题，我uid gid包括0,0 99,100 1000,100，还有UMASK=002 022都试过了，都无法更改删除文件

**Comment by chevy222** [comment]
现在还需要加 -e UID=$(id -u) -e GID=$(id -g) 来run吗

**Comment by cnk3x** [comment]
2024/05/22之前的拉取确认有问题，已经覆盖更新了，可以重新拉取试试。

> 现在还需要加 -e UID=$(id -u) -e GID=$(id -g) 来run吗

添加环境变量 XL_UID/XL_GID代替原来的UID和GID来设置。 原来的也能用，但后面更新可能会去掉。

**Comment by chevy222** [comment]
我看文档里没有，希望添加一下。
![image](https://github.com/cnk3x/xunlei/assets/29728193/956434a1-98ce-4240-91a7-a665f6e5d4ac)

**Comment by cnk3x** [comment]
文档已更新。

**Comment by latel** [comment]
![image](https://github.com/user-attachments/assets/ec508cab-7a47-4019-9450-5f7f678215d6)

设置了环境变了，下载的文件还是root， host网络+特权模式
