### ISSUE TITLE
能否增加其他内核构架？

### ISSUE THREAD

**Issue by mymine** [cnk3x/xunlei#14]
能否增加其他内核构架？
路由器，树莓派。

**Comment by cnk3x** [comment]
本项目只做了群晖的模拟，并不是开发了一个迅雷，其他架构是否支持得看官方NAS迅雷。
目前官方NAS迅雷只支持 linux/amd64(x86_64) 和 linux/arm64/v8平台。

**Comment by mymine** [comment]
> 本项目只做了群晖的模拟，并不是开发了一个迅雷，其他架构是否支持得看官方NAS迅雷。 目前官方NAS迅雷只支持 linux/amd64(x86_64) 和 linux/arm64/v8平台。

好的。谢谢
