### ISSUE TITLE
新版是不是下载路径变了？映射路径要改？

### ISSUE THREAD

**Issue by fanshu93** [cnk3x/xunlei#141]
更新新版后，下载文件没有落到主机路径，下载文件跑到docker  volume里面了。
老版本容器路径/xunlei/downloads，现在变了吗   映射给主机，无效。望解答，谢谢！

**Comment by fanshu93** [comment]
新版容器下载路径/downloads    如果用着以前的模板，下载路径就会出错，老哥要更新一下说明。这个容器太好用了，谢谢！

**Comment by ybjopq007** [comment]
我也有这个问题 把我docker volume直接干爆炸 不要覆盖升级 删除appdata和image镜像重新安装解决的 应该是加了几个变量有变化 删除重新安装吧 并且执行 docker volume prune/ docker image prune

**Comment by fanshu93** [comment]
> 我也有这个问题 把我docker.image直接干爆炸 不要覆盖升级 删除appdata和image镜像重新安装解决的 应该是加了几个变量有变化 删除重新安装吧 并且执行 docker volume prune/ docker image prune

是的  遇到一样的问题，我也这样处理。系统unraid

**Comment by cnk3x** [comment]
已经更新了，映射路径还是 /xunlei/downloads 和 /xunlei/data，可以重新拉取试试。

**Comment by fanshu93** [comment]
> 已经更新了，映射路径还是 /xunlei/downloads 和 /xunlei/data，可以重新拉取试试。

重新拉一切正常，谢谢！

**Comment by Anoyou** [comment]
> > 已经更新了，映射路径还是 /xunlei/downloads 和 /xunlei/data，可以重新拉取试试。
> 
> 重新拉一切正常，谢谢！

你好 请问 重新拉取 unraid 如图配置映射路径吗？谢谢
<img width="1990" alt="iShot_2024-06-07_11 52 30" src="https://github.com/cnk3x/xunlei/assets/13214236/5e45fabb-028f-4834-9278-686298c3f4e8">
