### ISSUE TITLE
无法使用，启动后没办法打开页面，现在正在使用旧版本的，一切完好。

### ISSUE THREAD

**Issue by PQ0000** [cnk3x/xunlei#143]
version: '3.3'
services:
  xunlei:
    image: cnk3x/xunlei:latest
    container_name: xunlei
    volumes:
      - /mnt/sdb1/xunlei/data:/xunlei/data
      - /mnt/sdb1/downloads:/xunlei/downloads
    ports:
      - "2345:2345"
    environment:
      - XL_DASHBOARD_PORT=2345
      - XL_DASHBOARD_HOST=0.0.0.0
      - XL_DASHBOARD_USER=admin
      - XL_DASHBOARD_PASSWORD=password
      - XL_DIR_DOWNLOAD=/xunlei/downloads
      - XL_DIR_DATA=/xunlei/data
      - XL_LOG=console
      - XL_LOGGER_MAXSIZE=10MB
      - XL_LOGGER_COMPRESS=true
    restart: unless-stopped

**Comment by igmkgu** [comment]
我也是 换回旧版了

**Comment by snakwu** [comment]
同样，可以成功运行，但无法打开页面

**Comment by cnk3x** [comment]
先退回旧版本吧。最新发布的确认有问题。

**Comment by unknown-o** [comment]
> 先退回旧版本吧。最新发布的确认有问题。

大佬什么时候发布新版啊？

**Comment by haolig** [comment]
问下旧版选哪个版本呢？我的也是xunlei打不开web页面。。。

**Comment by haolig** [comment]
切回3.7.1的镜像，目前正常。。。还以为istore os有问题。希望大佬抽时间修复3.11.2版的bug。

**Comment by Soulxy1993** [comment]
> 先退回旧版本吧。最新发布的确认有问题。

日志显示不支持arm64，我猜是自动安装了amd64的版本

**Comment by cnk3x** [comment]
已经更新了，可以重新拉取试试。
