### ISSUE TITLE
最新版直接不能用

### ISSUE THREAD

**Issue by NeverOvO** [cnk3x/xunlei#147]
05/23 04:47:08 INF run mode=fork
05/23 04:47:08 INF proot init root=/xunlei
05/23 04:47:08 INF fork root=/xunlei command=/usr/bin/xlp
05/23 04:47:08 INF fork pid=13
05/23 04:47:08 INF run mode=chroot
05/23 04:47:08 INF _  _ _  _ _  _ _    ____  _
05/23 04:47:08 INF  \/  |  | |\ | |    |___  |
05/23 04:47:08 INF _/\_ |__| | \| |___ |___  |
05/23 04:47:08 INF daemon version: v3.11.2
05/23 04:47:08 INF spk version: v3.11.2
05/23 04:47:08 INF 
05/23 04:47:08 INF Config
05/23 04:47:08 INF   - DashboardPort:     2345
05/23 04:47:08 INF   - DashboardUsername: none
05/23 04:47:08 INF   - DashboardPassword: none
05/23 04:47:08 INF   - DownloadPath:      /xunlei/downloads
05/23 04:47:08 INF   - DataPath:          /xunlei/data
05/23 04:47:08 INF   - Debug:             false
05/23 04:47:08 INF   - NewRoot:           /xunlei
05/23 04:47:08 INF Environ
05/23 04:47:08 INF   - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
05/23 04:47:08 INF   - HOSTNAME=6cc14a4f6ce5
05/23 04:47:08 INF   - HOST_CONTAINERNAME=xunlei
05/23 04:47:08 INF   - UID=1001
05/23 04:47:08 INF   - TZ=Asia/Shanghai
05/23 04:47:08 INF   - HOST_OS=Unraid
05/23 04:47:08 INF   - HOST_HOSTNAME=NeverOuO
05/23 04:47:08 INF   - LANG=zh_CN.UTF-8
05/23 04:47:08 INF   - LANGUAGE=zh_CN.UTF-8
05/23 04:47:08 INF   - LC_ALL=C
05/23 04:47:08 INF   - XL_DASHBOARD_PORT=2345
05/23 04:47:08 INF   - XL_DEBUG=false
05/23 04:47:08 INF   - XL_CHROOT=/xunlei
05/23 04:47:08 INF   - HOME=/var/packages/pan-xunlei-com/shares/迅雷/.drive
05/23 04:47:08 INF   - XL_DIR_DOWNLOAD=/xunlei/downloads
05/23 04:47:08 INF   - XL_DIR_DATA=/xunlei/data
05/23 04:47:08 INF   - XL_UID=1001
05/23 04:47:08 INF   - RUN_WITH_CHROOT=/xunlei
05/23 04:47:08 INF   - SYNOPLATFORM=apollolake
05/23 04:47:08 INF   - SYNOPKG_PKGNAME=pan-xunlei-com
05/23 04:47:08 INF   - SYNOPKG_PKGVER=3.11.2
05/23 04:47:08 INF   - SYNOPKG_PKGDEST=/var/packages/pan-xunlei-com/target
05/23 04:47:08 INF   - SYNOPKG_DSM_VERSION_MAJOR=7
05/23 04:47:08 INF   - SYNOPKG_DSM_VERSION_MINOR=2
05/23 04:47:08 INF   - SYNOPKG_DSM_VERSION_BUILD=64570
05/23 04:47:08 INF   - DriveListen=unix:///var/packages/pan-xunlei-com/target/var/pan-xunlei-com.sock
05/23 04:47:08 INF   - PLATFORM=群晖
05/23 04:47:08 INF   - OS_VERSION=apollolake dsm 7.2-64570
05/23 04:47:08 INF   - ConfigPath=/var/packages/pan-xunlei-com/shares/迅雷/
05/23 04:47:08 INF   - DownloadPATH=/var/packages/pan-xunlei-com/shares/迅雷/下载
05/23 04:47:08 INF   - TLSInsecureSkipVerify=true
05/23 04:47:08 INF   - GIN_MODE=release
05/23 04:47:08 INF syno mock addr=:2345
05/23 04:47:08 INF xunlei-pan-cli-launcher.amd64 start cmd="/var/packages/pan-xunlei-com/target/bin/bin/xunlei-pan-cli-launcher.amd64 -launcher_listen unix:///var/packages/pan-xunlei-com/target/var/pan-xunlei-com-launcher.sock -pid /var/packages/pan-xunlei-com/target/var/pan-xunlei-com.pid -logfile /var/packages/pan-xunlei-com/shares/迅雷/.drive/log-launcher.log -logsize 1MB"
05/23 04:47:08 INF xunlei-pan-cli-launcher.amd64 started pid=22
05/23 04:47:08 ERR [xunlei-pan-cli-launcher.amd64.2] KillDrivePid ioutil.ReadFile err:open /var/packages/pan-xunlei-com/target/var/pan-xunlei-com.pid.child: no such file or directory
05/23 04:47:08 WRN [xunlei-pan-cli-launcher.amd64.2] kill process error:open /var/packages/pan-xunlei-com/target/var/pan-xunlei-com.pid.child: no such file or directory
05/23 04:47:08 ERR [xunlei-pan-cli-launcher.amd64.2] [panCliPid=37]Launcher.startVersion cmd.Run exit error err:exit status 2 panCliPath:/var/packages/pan-xunlei-com/shares/迅雷/.drive/bin/xunlei-pan-cli.3.21.0.amd64 StdErr:panic: runtime error: invalid memory address or nil pointer dereference
05/23 04:47:08 ERR [xunlei-pan-cli-launcher.amd64.2] start new version 3.21.0=>3.21.0 err:exit status 2
05/23 04:47:08 WRN [xunlei-pan-cli-launcher.amd64.2] launcher version error exit status 2 retry 1
05/23 04:47:09 ERR [xunlei-pan-cli-launcher.amd64.2] [report=true&panCliPid=37]CheckProcess Signal err:os: process already finished
05/23 04:47:12.92 INFO loadenv from /var/packages/pan-xunlei-com/target/ui
05/23 04:47:12.92 INFO [error={"Op":"open","Path":"/var/packages/pan-xunlei-com/target/ui/envconfig","Err":2}&file=/var/packages/pan-xunlei-com/target/ui/envconfig]read envconfig failed use default
05/23 04:47:12.92 INFO getEnvs succ DownloadPATH=/var/packages/pan-xunlei-com/shares/迅雷/下载
05/23 04:47:12.92 INFO getEnvs succ DriveListen=unix:///var/packages/pan-xunlei-com/target/var/pan-xunlei-com.sock
05/23 04:47:12.92 INFO getEnvs succ PLATFORM=群晖
05/23 04:47:12.92 INFO getEnvs succ ConfigPath=/var/packages/pan-xunlei-com/shares/迅雷/
05/23 04:47:12.92 INFO getEnvs succ TLSInsecureSkipVerify=true
05/23 04:47:12.92 INFO [device_space=&config_path=/var/packages/pan-xunlei-com/shares/迅雷/.drive/]use config
05/23 04:47:12.92 INFO [device_space=&config_path=/var/packages/pan-xunlei-com/shares/迅雷/.drive/]use config
05/23 04:47:12.92 INFO [report=true&use_path=/var/packages/pan-xunlei-com/shares/迅雷/.drive/plugins]getPluginPATH
05/23 04:47:12.92 INFO [config_path=/var/packages/pan-xunlei-com/shares/迅雷/.drive/&device_space=]use config
05/23 04:47:12.92 INFO setDownloadAlias DriveFileMount :map[]
05/23 04:47:12.92 INFO config.init getEnvStrArray DownloadPATH:[/var/packages/pan-xunlei-com/shares/迅雷/下载] len:1
05/23 04:47:12.92 INFO config.init init succ: &{isInit:true NasIDKey: NasId: NasSubIdKey: NasSubId: DeviceId: WorkDir: BinPath:/var/packages/pan-xunlei-com/target/ui Platform:群晖 PathSplit:: DownloadPATHs:[/var/packages/pan-xunlei-com/shares/迅雷/下载] TorrentPath: DriveFileMount:map[] PluginTokenDuration:5h0m0s PluginPATH:/var/packages/pan-xunlei-com/shares/迅雷/.drive/plugins AuthTokenPATH: DriveArgs: DrivePlayer: DriveListen:unix:///var/packages/pan-xunlei-com/target/var/pan-xunlei-com.sock DrivePortFile: DriveLogLevel:info DriveLogFile: DriveLogSize:10MB DriveLogFormat: DriveUpdate: DriveConfigPATH:/var/packages/pan-xunlei-com/shares/迅雷/ DrivePIDFile: DriveInfoFile: DrivePublicPort:21603 FreePortRange:[] FreePortRangeUDP:[] LauncherLogFile: LauncherLogSize: LauncherPIDFile: LauncherListen:127.0.0.1:5051 NfoIsDisable: RefreshTokenDuration:1h KvCacheDuration:24h0m0s TaskCfgPath: ScrapeCacheDuration:24h0m0s SyncWatchDogDuration:30m0s CachePATH: DeviceSpace: DeviceName: TLSInsecureSkipVerify:true ImportTask:true SingleTaskMaxMB:100 SingleTaskReserveMB:20 OverallShareMaxMB:200 ThirdAuthURL: PanCliEnv: GeneDBShadowFileDuration:24h DebugPrintFileEvents:[] GossipFile:/var/packages/pan-xunlei-com/shares/迅雷/.drive/gossip.json PluginWithBash:false Webhook:{Modules:map[] URL:} HostXluser:https://xluser-ssl.xunlei.com HostApiPan:https://api-pan.xunlei.com HostShoulei:https://api-shoulei-ssl.xunlei.com HostHighSpeedFlow:https://api-pan.xunlei.com EnableTaskCfg:true WebhookHealthzToken:}
05/23 04:47:12.92 INFO start detect platform
05/23 04:47:12.92 INFO Detector.Detect envPlatform:群晖
05/23 04:47:12.92 INFO detect platform: synology X9ibISwpIp8jQ4Ya nasid: labels: [withQrcodeLogin withOtherAuthLogin withPlugin withPreviewPrivilege allowUseConfigPathAsCachePath withRootDiskSelect withInstallLocalPlugin withHighSpeedFlowCtrl withFetchFolder withSyncDriveFile withUserResetScrapeResult]
2024/05/23 04:47:12 Failed to dial: dial unix /var/packages/pan-xunlei-com/target/var/pan-xunlei-com.sock: connect: no such file or directory
2024/05/23 04:47:12 http: proxy error: dial unix /var/packages/pan-xunlei-com/target/var/pan-xunlei-com.sock: connect: no such file or directory
[WARN] 环境变量参数"UID"已过期,请使用"XL_UID"替代
05/23 04:47:28 ERR [xunlei-pan-cli-launcher.amd64.2] killPid process.Signal SIGABRT err:os: process already finished
05/23 04:47:28 WRN [xunlei-pan-cli-launcher.amd64.2] kill process error:os: process already finished
05/23 04:47:29 ERR [xunlei-pan-cli-launcher.amd64.2] [panCliPid=70]Launcher.startVersion cmd.Run exit error err:exit status 2 panCliPath:/var/packages/pan-xunlei-com/shares/迅雷/.drive/bin/xunlei-pan-cli.3.21.0.amd64 StdErr:panic: runtime error: invalid memory address or nil pointer dereference
05/23 04:47:29 ERR [xunlei-pan-cli-launcher.amd64.2] start new version 3.21.0=>3.21.0 err:exit status 2
05/23 04:47:29 WRN [xunlei-pan-cli-launcher.amd64.2] launcher version error exit status 2 retry 2
05/23 04:47:29 ERR [xunlei-pan-cli-launcher.amd64.2] [report=true&panCliPid=70]CheckProcess Signal err:os: process already finished

**Comment by ArthurXL2G** [comment]
+1

**Comment by wzyjscz** [comment]
unraid里的日志给的错误信息给的是这个ERR exited! err="exit status 2"

**Comment by SilkL2G** [comment]
就在刚刚更新了一下直接炸了，环境是unraid，按dockerhub配置的，昨天还好好的

**Comment by Soulxy1993** [comment]
我是启动成功，但是默认界面404

用这个链接能访问
http://192.168.100.1:2345/webman/3rdparty/pan-xunlei-com/index.cgi/#/home

**Comment by ArthurXL2G** [comment]
> 我是启动成功，但是默认界面404
> 
> 用这个链接能访问 http://192.168.100.1:2345/webman/3rdparty/pan-xunlei-com/index.cgi/#/home

unraid完全是无法启动，删除配置文件夹也不会生成新配置

**Comment by flame9468** [comment]
05/23 08:44:33 ERR exited! err="exit status 2"
05/23 08:44:49 INF run mode=fork
05/23 08:44:49 INF proot init root=/xunlei
05/23 08:44:49 INF fork root=/xunlei command=/usr/bin/xlp
05/23 08:44:49 INF fork pid=15
05/23 08:44:49 INF run mode=chroot
05/23 08:44:49 INF _  _ _  _ _  _ _    ____  _
05/23 08:44:49 INF  \/  |  | |\ | |    |___  |
05/23 08:44:49 INF _/\_ |__| | \| |___ |___  |
05/23 08:44:49 INF daemon version: v3.11.2
05/23 08:44:49 INF spk version: v3.11.2
05/23 08:44:49 INF 
05/23 08:44:49 INF Config
05/23 08:44:49 INF   - DashboardPort:     2345
05/23 08:44:49 INF   - DashboardUsername: none
05/23 08:44:49 INF   - DashboardPassword: none
05/23 08:44:49 INF   - DownloadPath:      /xunlei/downloads
05/23 08:44:49 INF   - DataPath:          /xunlei/data
05/23 08:44:49 INF   - Debug:             false
05/23 08:44:49 INF   - NewRoot:           /xunlei
05/23 08:44:49 INF Environ
05/23 08:44:49 INF   - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
05/23 08:44:49 INF   - HOSTNAME=Z370
05/23 08:44:49 INF   - TCP_PORT_2345=2345
05/23 08:44:49 INF   - TZ=Asia/Shanghai
05/23 08:44:49 INF   - HOST_OS=Unraid
05/23 08:44:49 INF   - HOST_HOSTNAME=Z370
05/23 08:44:49 INF   - HOST_CONTAINERNAME=Xunlei
05/23 08:44:49 INF   - XL_UID=1000
05/23 08:44:49 INF   - XL_GID=100
05/23 08:44:49 INF   - LANG=zh_CN.UTF-8
05/23 08:44:49 INF   - LANGUAGE=zh_CN.UTF-8
05/23 08:44:49 INF   - LC_ALL=C
05/23 08:44:49 INF   - XL_DASHBOARD_PORT=2345
05/23 08:44:49 INF   - XL_DEBUG=false
05/23 08:44:49 INF   - XL_CHROOT=/xunlei
05/23 08:44:49 INF   - HOME=/var/packages/pan-xunlei-com/shares/迅雷/.drive
05/23 08:44:49 INF   - XL_DIR_DOWNLOAD=/xunlei/downloads
05/23 08:44:49 INF   - XL_DIR_DATA=/xunlei/data
05/23 08:44:49 INF   - RUN_WITH_CHROOT=/xunlei
05/23 08:44:49 INF   - SYNOPLATFORM=apollolake
05/23 08:44:49 INF   - SYNOPKG_PKGNAME=pan-xunlei-com
05/23 08:44:49 INF   - SYNOPKG_PKGVER=3.11.2
05/23 08:44:49 INF   - SYNOPKG_PKGDEST=/var/packages/pan-xunlei-com/target
05/23 08:44:49 INF   - SYNOPKG_DSM_VERSION_MAJOR=7
05/23 08:44:49 INF   - SYNOPKG_DSM_VERSION_MINOR=2
05/23 08:44:49 INF   - SYNOPKG_DSM_VERSION_BUILD=64570
05/23 08:44:49 INF   - DriveListen=unix:///var/packages/pan-xunlei-com/target/var/pan-xunlei-com.sock
05/23 08:44:49 INF   - PLATFORM=群晖
05/23 08:44:49 INF   - OS_VERSION=apollolake dsm 7.2-64570
05/23 08:44:49 INF   - ConfigPath=/var/packages/pan-xunlei-com/shares/迅雷/
05/23 08:44:49 INF   - DownloadPATH=/var/packages/pan-xunlei-com/shares/迅雷/下载
05/23 08:44:49 INF   - TLSInsecureSkipVerify=true
05/23 08:44:49 INF   - GIN_MODE=release
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x6c990d]

goroutine 1 [running]:
github.com/cnk3x/xunlei/xlp.lookupUg({0xc000012047?, 0x4?}, {0xc000012057, 0x3})
        github.com/cnk3x/xunlei/xlp/sys_linux.go:84 +0x1ed
github.com/cnk3x/xunlei/xlp.(*Daemon).run(0xc000122090, {0x7edb78, 0xc000028840})
        github.com/cnk3x/xunlei/xlp/xlp.go:197 +0xa25
github.com/cnk3x/xunlei/xlp.(*Daemon).chrootRun(0xc000122090, {0x7edb78, 0xc000028840})
        github.com/cnk3x/xunlei/xlp/xlp.go:144 +0x119
github.com/cnk3x/xunlei/xlp.(*Daemon).Run.func1({0x7edb78, 0xc000028840}, 0xc000122090)
        github.com/cnk3x/xunlei/xlp/xlp.go:101 +0x24a
github.com/cnk3x/xunlei/xlp.(*Daemon).Run(0xc000122090, {0x7edb78, 0xc000028840})
        github.com/cnk3x/xunlei/xlp/xlp.go:106 +0x1cd
main.main()
        github.com/cnk3x/xunlei/cmd/xlp/main.go:35 +0x2ec
05/23 08:44:49 ERR exited! err="exit status 2"

**Comment by ArthurXL2G** [comment]
Unraid环境

日志：
2024/05/23 10:06:55 Failed to dial: dial unix /var/packages/pan-xunlei-com/target/var/pan-xunlei-com.sock: connect: connection refused
2024/05/23 10:06:55 http: proxy error: dial unix /var/packages/pan-xunlei-com/target/var/pan-xunlei-com.sock: connect: connection refused
2024/05/23 10:06:55 Failed to dial: dial unix /var/packages/pan-xunlei-com/target/var/pan-xunlei-com.sock: connect: connection refused
2024/05/23 10:06:55 http: proxy error: dial unix /var/packages/pan-xunlei-com/target/var/pan-xunlei-com.sock: connect: connection refused
……
![image](https://github.com/cnk3x/xunlei/assets/62242396/a307832d-c1fe-4cc7-9a8e-c702007066ac)

**Comment by flame9468** [comment]
![Screenshot_2024-05-23-18-13-40-75_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/cnk3x/xunlei/assets/7872399/efa264c2-3355-4a51-a8de-ccd2f14cd58d)

**Comment by cnk3x** [comment]
> Unraid环境
> 
> 日志： 2024/05/23 10:06:55 Failed to dial: dial unix /var/packages/pan-xunlei-com/target/var/pan-xunlei-com.sock: connect: connection refused 2024/05/23 10:06:55 http: proxy error: dial unix /var/packages/pan-xunlei-com/target/var/pan-xunlei-com.sock: connect: connection refused 2024/05/23 10:06:55 Failed to dial: dial unix /var/packages/pan-xunlei-com/target/var/pan-xunlei-com.sock: connect: connection refused 2024/05/23 10:06:55 http: proxy error: dial unix /var/packages/pan-xunlei-com/target/var/pan-xunlei-com.sock: connect: connection refused …… 05/23 10:10:32 ERR [xunlei-pan-cli-launcher.amd64.2] killPid process.Signal SIGABRT err:os: process already finished 05/23 10:10:32 WRN [xunlei-pan-cli-launcher.amd64.2] kill process error:os: process already finished 05/23 10:10:32 ERR [xunlei-pan-cli-launcher.amd64.2] [panCliPid=5815]Launcher.startVersion cmd.Run exit error err:exit status 2 panCliPath:/var/packages/pan-xunlei-com/shares/迅雷/.drive/bin/xunlei-pan-cli.3.21.0.amd64 StdErr:panic: runtime error: invalid memory address or nil pointer dereference 05/23 10:10:32 ERR [xunlei-pan-cli-launcher.amd64.2] start new version 3.21.0=>3.21.0 err:exit status 2 05/23 10:10:32 WRN [xunlei-pan-cli-launcher.amd64.2] launcher version error exit status 2 retry 1 05/23 10:10:33 ERR [xunlei-pan-cli-launcher.amd64.2] [panCliPid=5815&report=true]CheckProcess Signal err:os: process already finished ![image](https://private-user-images.githubusercontent.com/62242396/333140317-a307832d-c1fe-4cc7-9a8e-c702007066ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0NjIyNDksIm5iZiI6MTcxNjQ2MTk0OSwicGF0aCI6Ii82MjI0MjM5Ni8zMzMxNDAzMTctYTMwNzgzMmQtYzFmZS00Y2M3LTlhOGUtYzcwMjAwNzA2NmFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIzVDEwNTkwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg3YTIxZjEwYWRlYWZlN2JjZjM5ZDVlY2Y4Yjk4M2NiY2IyOTNlOWJlMGVlYWE1OTNkY2VjNTkyOGI5YzE5OGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zoFJ_B9c7ABftx9h33CdvU2EbHG9g6A3805DCa_wQ1s)

目前在线更新存在问题，暂时不要更新，用镜像内置的包。等迅雷出了arm64的3.21.0的包，我一并更新。

**Comment by cnk3x** [comment]
> ![Screenshot_2024-05-23-18-13-40-75_40deb401b9ffe8e1df2f1cc5ba480b12](https://private-user-images.githubusercontent.com/7872399/333142296-efa264c2-3355-4a51-a8de-ccd2f14cd58d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0NjIyNDksIm5iZiI6MTcxNjQ2MTk0OSwicGF0aCI6Ii83ODcyMzk5LzMzMzE0MjI5Ni1lZmEyNjRjMi0zMzU1LTRhNTEtYThkZS1jY2QyZjE0Y2Q1OGQuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjNUMTA1OTA5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODRkNmU3YjRkYmRiNzkxZGNlNWMxM2U1YjYyZTBiN2MxZGZkMzIxMmQxMmJkY2Y3ZjgyZmIzNWE4OWVkNzFmMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.4uKuCGANl6s5lXXABT8ddC7WVxgyIUJqxebjBfdXdG8)

你确认一下重新拉取的包，运行后会有一行版本号显示： daemon version: v3.11.2-1，才是最新的。

**Comment by zindsia** [comment]
> > ![Screenshot_2024-05-23-18-13-40-75_40deb401b9ffe8e1df2f1cc5ba480b12](https://private-user-images.githubusercontent.com/7872399/333142296-efa264c2-3355-4a51-a8de-ccd2f14cd58d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0NjIyNDksIm5iZiI6MTcxNjQ2MTk0OSwicGF0aCI6Ii83ODcyMzk5LzMzMzE0MjI5Ni1lZmEyNjRjMi0zMzU1LTRhNTEtYThkZS1jY2QyZjE0Y2Q1OGQuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjNUMTA1OTA5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODRkNmU3YjRkYmRiNzkxZGNlNWMxM2U1YjYyZTBiN2MxZGZkMzIxMmQxMmJkY2Y3ZjgyZmIzNWE4OWVkNzFmMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.4uKuCGANl6s5lXXABT8ddC7WVxgyIUJqxebjBfdXdG8)
> 
> 你确认一下重新拉取的包，运行后会有一行版本号显示： daemon version: v3.11.2-1，才是最新的。

我的可以使用
![微信截图_20240523192030](https://github.com/cnk3x/xunlei/assets/32201229/eae8fdae-257f-4695-a21d-3359c88ade18)

**Comment by wzyjscz** [comment]
> > > ![Screenshot_2024-05-23-18-13-40-75_40deb401b9ffe8e1df2f1cc5ba480b12](https://private-user-images.githubusercontent.com/7872399/333142296-efa264c2-3355-4a51-a8de-ccd2f14cd58d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0NjIyNDksIm5iZiI6MTcxNjQ2MTk0OSwicGF0aCI6Ii83ODcyMzk5LzMzMzE0MjI5Ni1lZmEyNjRjMi0zMzU1LTRhNTEtYThkZS1jY2QyZjE0Y2Q1OGQuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjNUMTA1OTA5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODRkNmU3YjRkYmRiNzkxZGNlNWMxM2U1YjYyZTBiN2MxZGZkMzIxMmQxMmJkY2Y3ZjgyZmIzNWE4OWVkNzFmMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.4uKuCGANl6s5lXXABT8ddC7WVxgyIUJqxebjBfdXdG8)
> > 
> > 
> > 你确认一下重新拉取的包，运行后会有一行版本号显示： daemon version: v3.11.2-1，才是最新的。
> 
> 用作者的版本可以使用，但在线网页更新确实不能，网页在线更新停在90%，日志提示refused ![微信截图_20240523192030](https://private-user-images.githubusercontent.com/32201229/333162767-eae8fdae-257f-4695-a21d-3359c88ade18.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0NjYyMDMsIm5iZiI6MTcxNjQ2NTkwMywicGF0aCI6Ii8zMjIwMTIyOS8zMzMxNjI3NjctZWFlOGZkYWUtMjU3Zi00Njk1LWEyMWQtMzM1OWM4OGFkZTE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIzVDEyMDUwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVkYmU4OGMzYWFjN2FiMTNlMDk0NDI3OGYyYzMxMmI2OWY3NjhiOTYwNWQyOGYyM2QwNjlkNjEzMjM3MWQzMTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UGB1XQgMenbEQgQauTfiCJYiIbLmy2XFeinorgB6xyI)

unraid下，我尝试“强制更新”迅雷docker，强制重新拉取了镜像，现在可以跑起来了，好消息是UID和GID设置好后，下载文件有权限改名和删除了，坏消息是网页更新也是一样的情况卡在90%，然后就提示更新失败

**Comment by zindsia** [comment]
> > > > ![Screenshot_2024-05-23-18-13-40-75_40deb401b9ffe8e1df2f1cc5ba480b12](https://private-user-images.githubusercontent.com/7872399/333142296-efa264c2-3355-4a51-a8de-ccd2f14cd58d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0NjIyNDksIm5iZiI6MTcxNjQ2MTk0OSwicGF0aCI6Ii83ODcyMzk5LzMzMzE0MjI5Ni1lZmEyNjRjMi0zMzU1LTRhNTEtYThkZS1jY2QyZjE0Y2Q1OGQuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjNUMTA1OTA5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODRkNmU3YjRkYmRiNzkxZGNlNWMxM2U1YjYyZTBiN2MxZGZkMzIxMmQxMmJkY2Y3ZjgyZmIzNWE4OWVkNzFmMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.4uKuCGANl6s5lXXABT8ddC7WVxgyIUJqxebjBfdXdG8)
> > > 
> > > 
> > > 你确认一下重新拉取的包，运行后会有一行版本号显示： daemon version: v3.11.2-1，才是最新的。
> > 
> > 
> > 用作者的版本可以使用，但在线网页更新确实不能，网页在线更新停在90%，日志提示refused ![微信截图_20240523192030](https://private-user-images.githubusercontent.com/32201229/333162767-eae8fdae-257f-4695-a21d-3359c88ade18.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0NjYyMDMsIm5iZiI6MTcxNjQ2NTkwMywicGF0aCI6Ii8zMjIwMTIyOS8zMzMxNjI3NjctZWFlOGZkYWUtMjU3Zi00Njk1LWEyMWQtMzM1OWM4OGFkZTE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIzVDEyMDUwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVkYmU4OGMzYWFjN2FiMTNlMDk0NDI3OGYyYzMxMmI2OWY3NjhiOTYwNWQyOGYyM2QwNjlkNjEzMjM3MWQzMTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UGB1XQgMenbEQgQauTfiCJYiIbLmy2XFeinorgB6xyI)
> 
> unraid下，我尝试“强制更新”迅雷docker，强制重新拉取了镜像，现在可以跑起来了，好消息是UID和GID设置好后，下载文件有权限改名和删除了，坏消息是网页更新也是一样的情况卡在90%，然后就提示更新失败

作者大大肝不要了，又又又又又又更新了，已经可更新到最新版了daemon version: v3.11.2-3，这个版本已经是最新版了
![111 (2)](https://github.com/cnk3x/xunlei/assets/32201229/928c173b-58d8-4dd6-b956-aa6256265d88)
![微信截图_20240523201755](https://github.com/cnk3x/xunlei/assets/32201229/dc964c0e-c391-4832-8403-339cec7b6163)
