### ISSUE TITLE
最新版下载会显示等待中

### ISSUE THREAD

**Issue by Dreamsky00824** [cnk3x/xunlei#149]
![image](https://github.com/cnk3x/xunlei/assets/158264145/af93dd15-3cc9-4fa5-b352-13715421c0b1)
![image](https://github.com/cnk3x/xunlei/assets/158264145/8667af39-f40a-4118-a9be-d48804ccc874)

**Comment by cnk3x** [comment]
信息不够，无法判断什么原因。
