### ISSUE TITLE
X86的Openwrt的docker容器跑xunlei如何设置下载目录为挂载的硬盘？

### ISSUE THREAD

**Issue by cheneylaw** [cnk3x/xunlei#15]
想把迅雷的下载目录设置为Openwrt挂载的硬盘的目录/mnt/sda1/xunlei，请问该如何设置呢？
该docker的目录是在Openwrt的/opt/docker/
我尝试了：
-v=/mnt/sda1/xunlei/:/downloads 
然后下载的时候弹出来的对话框还是该容器默认的/downloads，这个目录才10m的容量，能否修改到挂载的硬盘呢？

**Comment by cnk3x** [comment]
我不太清楚openwrt是如何处理的，但容器文件目录的挂载是发生在挂载时的情况，如果你/mnt/sda1挂载发生在容器挂载之后，那么容器内挂载的目录可能就不是你的硬盘了。

下载弹出来的路径是/downloads是正常的。 容器绑定成功的话，容器内这个路径指向的就是 /mnt/sda1/xunlei/

**Comment by else05** [comment]
-v=/mnt/sda1/xunlei/:/downloads 就是使用这个挂载就可以了，我用的就是openwrt , 用usb3.0接了个4T的3.5寸硬盘盒子，都可以正常使用。还挂了其它pt

**Comment by cnk3x** [comment]
我特地装了个op试试，你参考一下：https://www.bilibili.com/video/BV1FB4y1q7Cp

**Comment by cheneylaw** [comment]
谢谢，搞定了

**Comment by wjp919497158** [comment]
> 我不太清楚openwrt是如何处理的，但容器文件目录的挂载是发生在挂载时的情况，如果你/mnt/sda1挂载发生在容器挂载之后，那么容器内挂载的目录可能就不是你的硬盘了。
> 
> 下载弹出来的路径是/downloads是正常的。容器绑定成功的话，容器内这个路径指向的就是 /mnt/sda1/xunlei/

能不能支持热挂载下载目录啊，外面可以写个脚本热挂载U盘，我想把迅雷的目录映射到新挂载上的U盘能不能实现呢。搜了一圈只看到一个热识别U盘加密狗的。纯小白求教
