### ISSUE TITLE
 下载目录只能有一个

### ISSUE THREAD

**Issue by laifuer** [cnk3x/xunlei#150]
之前的可以通过卷映射，让 xunlei 识别到多个目录自由选择，我的主机挂了 2 个硬盘，现在只能识别到xunlei/downloads映射的目录

是需要添加什么参数吗

**Comment by wzyjscz** [comment]
我也是，刚刚才发现，只显示一个默认下载文件夹

**Comment by poseidon2750** [comment]
+1，如果能分别挂载多个目录就完美了，因为有两个目录要挂载但是又不想开放他们的上层目录给迅雷

**Comment by cnk3x** [comment]
环境变量 XL_DIR_DOWNLOAD        
多个文件夹用英文（半角）冒号:分隔，第一个为下载保存默认文件夹，默认情况下只指定了一个 /xunlei/downloads

比如: XL_DIR_DOWNLOAD=/xunlei/downloads:/mydir/software:/mydir/movie
