### ISSUE TITLE
下载文件本地无法管理问题

### ISSUE THREAD

**Issue by wmq7777** [cnk3x/xunlei#155]
大佬 用这个下载好的文件 在本地重命名或者删除，提示权限不够怎么解决？？

**Comment by SeanChengN** [comment]
UID和GID设置一下

**Comment by 877490920** [comment]
> UID和GID设置一下

请问具体如何操作？这个问题也困扰我好久了，望回复谢谢

**Comment by cnk3x** [comment]
环境变量添加 XL_UID 和 XL_GID 指定用户和用户组
