### ISSUE TITLE
新版本 3.11.2，用变量设置的路径问题求教

### ISSUE THREAD

**Issue by Anoyou** [cnk3x/xunlei#157]
用变量设置路径后，下载的文件在宿主机内找不到（小白，不懂，求解，谢谢）？

于是又添加了俩旧版本的映射路径参数，无法下载，提示：保存种子失败114007

有 UNRAID 下新版配置成功的朋友吗？求解，谢谢
<img width="1990" alt="iShot_2024-06-07_11 52 30" src="https://github.com/cnk3x/xunlei/assets/13214236/43457b71-6c76-4571-abab-ce686bac3ef1">

**Comment by cnk3x** [comment]
UNRAID 没用过，不过你确定一下，你指定了XL_UID和XL_GID, 你指定的程序数据目录需要对这个可用可写。
