### ISSUE TITLE
作者能弄个不需要特权模式的版本吗

### ISSUE THREAD

**Issue by sxyandapp** [cnk3x/xunlei#159]
特权模式不是每个环境都支持的，而且特权模式确实太危险了

**Comment by cnk3x** [comment]
可以支持非特权模式，但对你运行环境有要求的。
比如我把默认的overlay2存储驱动改成 overlayfs，可以支持非特权运行

非特权模式只需添加环境变量 `XL_CHROOT=/` 就可以了。

```
$ docker info -f '{{.Driver}}: {{ .DriverStatus }}'
overlayfs: [[driver-type io.containerd.snapshotter.v1]]
```

**Comment by sxyandapp** [comment]
在爱快里试了，XL_CHROOT=/  ，容器运行失败

**Comment by cnk3x** [comment]
你没有给出日志，我猜测应该是你爱快的docker存储模式还是传统的 overlay2，在这种情况下是不支持非特权的。
