### ISSUE TITLE
重启系统后docker容器启动失败

### ISSUE THREAD

**Issue by Generalize** [cnk3x/xunlei#16]
日志显示 `2022/06/25 12:53:05 错误: [daemon] 设置下载目录失败: file exists
`

docker日志:

> 2022/06/25 12:53:05 [syno] 开始构建运行环境
2022/06/25 12:53:05 [syno] 复制必要文件
2022/06/25 12:53:05 [syno] 复制文件 "/etc/resolv.conf" 到 "/xunlei/etc/resolv.conf": 成功
2022/06/25 12:53:05 [syno] 复制文件 "/etc/hosts" 到 "/xunlei/etc/hosts": 成功
2022/06/25 12:53:05 [syno] 复制文件 "/etc/localtime" 到 "/xunlei/etc/localtime": 成功
2022/06/25 12:53:05 [syno] 复制文件 "/etc/timezone" 到 "/xunlei/etc/timezone": 成功
2022/06/25 12:53:05 [syno] 复制文件 "/etc/ssl/certs/ca-certificates.crt" 到 "/xunlei/etc/ssl/certs/ca-certificates.crt": 成功
2022/06/25 12:53:05 [syno] 绑定必须目录
2022/06/25 12:53:05 [syno] 绑定目录 "/dev" -> "/xunlei/dev": 成功
2022/06/25 12:53:05 [syno] 绑定目录 "/sys" -> "/xunlei/sys": 成功
2022/06/25 12:53:05 [syno] 绑定目录 "/var/packages/pan-xunlei-com/target" -> "/xunlei/var/packages/pan-xunlei-com/target": 成功
2022/06/25 12:53:05 [syno] 绑定目录 "/data" -> "/xunlei/data": 成功
2022/06/25 12:53:05 [syno] 绑定目录 "/downloads" -> "/xunlei/downloads": 成功
2022/06/25 12:53:05 [syno] 绑定可选目录
2022/06/25 12:53:05 [syno] 绑定目录 "/run" -> "/xunlei/run": 成功
2022/06/25 12:53:05 [syno] 绑定目录 "/lib" -> "/xunlei/lib": 成功
2022/06/25 12:53:05 [syno] 绑定目录 "/lib64" -> "/xunlei/lib64": 成功
2022/06/25 12:53:05 [syno] 绑定目录 "/lib32" -> "/xunlei/lib32": 成功
2022/06/25 12:53:05 [syno] 绑定目录 "/libx32" -> "/xunlei/libx32": 成功
2022/06/25 12:53:05 [syno] 绑定目录 "/usr" -> "/xunlei/usr": 成功
2022/06/25 12:53:05 [syno] 绑定目录 "/bin" -> "/xunlei/bin": 成功
2022/06/25 12:53:05 [syno] 绑定目录 "/mnt" -> "/xunlei/mnt": 成功
2022/06/25 12:53:05 [syno] 运行环境处理完成
2022/06/25 12:53:05 [syno] 开始运行: /xunlei/xlp daemon
2022/06/25 12:53:05 [daemon] 切换主目录: /xunlei
2022/06/25 12:53:05 [daemon] 切换数据目录: /xunlei
2022/06/25 12:53:05 错误: [daemon] 设置下载目录失败: file exists
2022/06/25 12:53:05 [syno] 卸载目录 "/xunlei/run" 成功
2022/06/25 12:53:05 [syno] 卸载目录 "/xunlei/lib" 成功
2022/06/25 12:53:05 [syno] 卸载目录 "/xunlei/lib64" 成功
2022/06/25 12:53:05 [syno] 卸载目录 "/xunlei/lib32" 成功
2022/06/25 12:53:05 [syno] 卸载目录 "/xunlei/libx32" 成功
2022/06/25 12:53:05 [syno] 卸载目录 "/xunlei/usr" 成功
2022/06/25 12:53:05 [syno] 卸载目录 "/xunlei/bin" 成功
2022/06/25 12:53:05 [syno] 卸载目录 "/xunlei/mnt" 成功
2022/06/25 12:53:05 [syno] 卸载目录 "/xunlei/dev" 成功
2022/06/25 12:53:05 [syno] 卸载目录 "/xunlei/sys" 成功
2022/06/25 12:53:05 [syno] 卸载目录 "/xunlei/var/packages/pan-xunlei-com/target" 成功
2022/06/25 12:53:05 [syno] 卸载目录 "/xunlei/data" 成功
2022/06/25 12:53:05 [syno] 卸载目录 "/xunlei/downloads" 成功
2022/06/25 12:53:05 错误: [syno] down: exit status 1

**Comment by ArthurXL2G** [comment]
我也遇到，一模一样的情况

**Comment by cnk3x** [comment]
已经修复这个问题了。删掉数据目录，重新拉取最新的镜像。
映射规则有些变动
注意一下：
原来的下载目录绑定 /downloads 改为绑定 /xunlei/downloads
原来的数据目录 /data 改为 /xunlei/data
