### ISSUE TITLE
是我cpu太弱了吗? r3568速度只有10+m 如果换成n5105会好点吗?

### ISSUE THREAD

**Issue by skyheaton** [cnk3x/xunlei#164]
是我cpu太弱了吗? 像是被限速了
r3568正常种子只有10+M的速度,永远不过15M 70%的占用率 很恶心啊台式机都是50 60M的速度.
如果换成n5105黑群晖会好吗? 
如果好很多的话就换了 让他安心去做路由器吧

**Comment by cnk3x** [comment]
应该不至于吧，迅雷应该只是比较吃内存，你将迅雷的网络开放试试（容器内运行把网络设置为host）

**Comment by skyheaton** [comment]
![Snipaste_2024-07-01_17-16-51](https://github.com/cnk3x/xunlei/assets/63988573/cb1f4e33-c1d4-4601-829f-6095e5dba81f)
只有一个容器并且设置为host点击编辑后
![Snipaste_2024-07-01_17-15-50](https://github.com/cnk3x/xunlei/assets/63988573/9e27518b-e38a-4fe7-9fd6-352b0bc99f9f)
显示这个

**Comment by An-ding-S** [comment]
能在termux中运行吗？

**Comment by bigmangos** [comment]
一样的问题，使用arm设备，cpu占用35%，速度上不去，最多跑到15MB/s

**Comment by skyheaton** [comment]
> 一样的问题，使用arm设备且host模式，cpu占用35%，速度上不去，最多跑到15MB/s

迅雷的问题 我换了黑裙晖 n100+24G内存 一样的 和电脑速度根本不能比 但是有的种子速度快一点 估计迅雷有限制吧
