### ISSUE TITLE
最新版本下载会提示9102代码

### ISSUE THREAD

**Issue by flame9468** [cnk3x/xunlei#165]
下载错误，提示9102

**Comment by cnk3x** [comment]
不太明白

**Comment by cnk3x** [comment]
在我的测试机上，日志会输出这行错误，但不影响下载。

**Comment by DUYA112233** [comment]
同unraid，前两天可以正常下载，今天报9102，所有文件均无法下载
![QQ_1720527549102](https://github.com/cnk3x/xunlei/assets/33391055/6ce88a9b-5fe6-42b0-bfb5-0c240d2023f7)
日志如下，部分信息用*代替
```
07/09 19:57:15 INF [main] mount...
07/09 19:57:15 WRN [chroot] /usr/syno/synoman/webman/modules/authenticate.cgi has exist, ignore write
07/09 19:57:15 WRN [chroot] /etc/synoinfo.conf has exist, ignore write
07/09 19:57:15 INF [main] _  _ _  _ _  _ _    ____  _
07/09 19:57:15 INF [main]  \/  |  | |\ | |    |___  |
07/09 19:57:15 INF [main] _/\_ |__| | \| |___ |___  |
07/09 19:57:15 INF [main] daemon version: v3.20.0
07/09 19:57:15 INF [main] spk version: 3.21.0
07/09 19:57:15 INF [main] port: 2345
07/09 19:57:15 INF [main] ip: <nil>
07/09 19:57:15 INF [main] dashboard username: 
07/09 19:57:15 INF [main] dashboard password: 
07/09 19:57:15 INF [main] dir download: /xunlei/downloads
07/09 19:57:15 INF [main] dir data: /xunlei/data
07/09 19:57:15 INF [main] uid: 1000
07/09 19:57:15 INF [main] gid: 100
07/09 19:57:15 INF [main] prevent update: true
07/09 19:57:15 INF [main] chroot: /xunlei
07/09 19:57:15 INF [main] debug: false
07/09 19:57:15 INF [main] args: "--dashboard_port" "2345" "--dir_download" "/xunlei/downloads" "--dir_data" "/xunlei/data" "--uid" "1000" "--gid" "100" "--prevent_update" "--chroot" "/xunlei"
07/09 19:57:15 INF [mock] web started listen=[::]:2345
07/09 19:57:15 INF [xunlei-pan-cli] start cmd="/var/packages/pan-xunlei-com/target/bin/bin/xunlei-pan-cli-launcher.amd64 -launcher_listen unix:///var/packages/pan-xunlei-com/target/var/pan-xunlei-com-launcher.sock -pid /var/packages/pan-xunlei-com/target/var/pan-xunlei-com.pid -update_url http://127.0.0.1:2345/webman/3rdparty/pan-xunlei-com/version"
07/09 19:57:15 INF [xunlei-pan-cli] started pid=31
07/09 19:57:16 ERR [xunlei-pan-cli] loadHistory ReadFile err:open /xunlei/data/.drive/bin/.history: no such file or directory path:/xunlei/data/.drive/bin/.history
07/09 19:57:16 ERR [xunlei-pan-cli] killPid process.Signal SIGABRT err:os: process already finished
07/09 19:57:16 WRN [xunlei-pan-cli] kill process error:os: process already finished
07/09 19:57:16 ERR [xunlei-pan-cli] download/download_cgo.go:89 [TaskCfgPath=/xunlei/data/.drive/.TaskConfig&ret=9102] > init download_sdk TaskCfgPath error
07/09 19:57:17 ERR [xunlei-pan-cli] agent/agent.go:239  > directWakeup err wakupMessage agent is empty invalid character '<' looking for beginning of value <html>
07/09 19:57:17 ERR [xunlei-pan-cli] - <head><title>404 Not Found</title></head>
07/09 19:57:17 ERR [xunlei-pan-cli] - <body>
07/09 19:57:17 ERR [xunlei-pan-cli] - <center><h1>404 Not Found</h1></center>
07/09 19:57:17 ERR [xunlei-pan-cli] - <hr><center>nginx</center>
07/09 19:57:17 ERR [xunlei-pan-cli] - </body>
07/09 19:57:17 ERR [xunlei-pan-cli] - </html>
07/09 19:57:17 ERR [xunlei-pan-cli] - 
07/09 19:57:18 ERR [xunlei-pan-cli] "},"type":{"in":"user#runner"}}&trace_id=eUjoAjcO] > Client.Request finish
07/09 19:57:18 WRN [xunlei-pan-cli] download_runner/register_runner.go:64 [device_space=] > reload device config buffer size err 设置任务用于下载的内部缓存大小错误(9102)
07/09 19:57:18 WRN [xunlei-pan-cli] runner/runner.go:837 [target=device_id#0d17d3901d1ee7cfec171d1800f7e0af&sync=true&package_name=pan.xunlei.cli.synology&phase=PHASE_TYPE_RUNNING&platform=synology&round=2&user_id=*&pid=40&task_id=VO0sKyDTq-BG607OHa9FQ4r8A1&access=user#app,user#download,user#download-url,user#nfo&device_config={"device_space":"","speed_limit":-1,"runner_count":5,"download_infos":null,"download_paths":["/xunlei/downloads/"],"access_task_type":null,"file_mount":{},"single_task_max_mb":100,"single_task_reserve_mb":20,"overall_share_max_mb":200}&sleeper=:10m0s<10m0s<20m0s&client_id=X9ibISwpIp8jQ4Ya&downloads=[{"name":"","path":"/xunlei/downloads/","usage":4409941438464,"limit":7999426170880,"errmsg":"","is_root_path":false},{"name":"","path":"/usr/bin/","usage":4529942528,"limit":21474836480,"errmsg":"","is_root_path":true},{"name":"","path":"/usr/lib/","usage":4529942528,"limit":21474836480,"errmsg":"","is_root_path":true},{"name":"","path":"/run/","usage":4529942528,"limit":21474836480,"errmsg":"","is_root_path":true},{"name":"","path":"/tmp/","usage":4529942528,"limit":21474836480,"errmsg":"","is_root_path":true},{"name":"","path":"/usr/lib64/","usage":4529942528,"limit":21474836480,"errmsg":"","is_root_path":true}]&type=user#runner&accept=true&func_name=DeviceRunner.start&version=3.21.0&plm=syn&client_version=3.21.0&product_name=群晖&func_st=07/09 19:57:17&os=linux&space=&start_at=2024/07/03 19:25:44&name=群晖-mynas&device_model=geminilake dsm 7.2-64570&arch=amd64&trace_id=N02FmWnQ&ip=*] > start runner
07/09 19:57:19 ERR [xunlei-pan-cli] "},"type":{"in":"user#download-url,user#download"}}&limit=100&page_token=&space=device_id#0d17d3901d1ee7cfec171d1800f7e0af&type=&func_name=getRespBodyFromRemote&trace_id=lId0IL3G&lookup=addr:api-pan.xunlei.com ip:101.91.143.206,101.91.143.102,180.163.71.176,2408:4002:1f20::1de,] > Client.Request finish
07/09 19:57:19 ERR [xunlei-pan-cli] connect to [2408:4002:1f10::95]:443 &net.Peer{Id:"2408:4002:1f10::95", Option:net.PeerOpt{}, Weight:100, CurrentWeight:99, PreWeight:0, LastError:error(nil), Failed:0, TotalFailed:0, TotalCount:1, PreFailed:0, Object:net.IP{0x24, 0x8, 0x40, 0x2, 0x1f, 0x10, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x95}} err: dial tcp [2408:4002:1f10::95]:443: connect: network is unreachable
07/09 19:57:19 ERR [xunlei-pan-cli] "},"type":{"in":"user#download-url,user#download"}}&limit=100&page_token=&space=device_id#0d17d3901d1ee7cfec171d1800f7e0af&type=&pid=40&duration=0.0369&func_name=getRespBodyFromRemote&trace_id=LZeKlNxe&lookup=addr:api-pan.xunlei.com ip:101.91.143.102,101.91.143.206,180.163.71.176,2408:4002:1f20::1de,&resp_code=200&report_type=request&func_st=07/09 19:57:19&reqMethod=GET&resp_data_len=11945] > Client.Request finish
07/09 19:57:19 ERR [xunlei-pan-cli] connect to [2408:4002:1f10::2]:443 &net.Peer{Id:"2408:4002:1f10::2", Option:net.PeerOpt{}, Weight:100, CurrentWeight:99, PreWeight:0, LastError:error(nil), Failed:0, TotalFailed:0, TotalCount:1, PreFailed:0, Object:net.IP{0x24, 0x8, 0x40, 0x2, 0x1f, 0x10, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x2}} err: dial tcp [2408:4002:1f10::2]:443: connect: network is unreachable
07/09 19:57:19 ERR [xunlei-pan-cli] "},"type":{"in":"user#download-url,user#download"}}&limit=100&page_token=&space=device_id#0d17d3901d1ee7cfec171d1800f7e0af&type=&report_type=request&pid=40&func_st=07/09 19:57:19] > Client.Request finish
07/09 19:57:19 ERR [xunlei-pan-cli] download_runner/upload.go:299  > uploadWatcher SetUploadSwitch err:设置上传错误(9102)
07/09 19:57:20 ERR [xunlei-pan-cli] "},"type":{"in":"user#download-url,user#download"}}&limit=100&page_token=&space=device_id#0d17d3901d1ee7cfec171d1800f7e0af&type=&duration=0.0485&resp_data_len=11809&func_name=getRespBodyFromRemote&pid=40&func_st=07/09 19:57:20&trace_id=S5bFCLBs&resp_code=200&reqMethod=GET&report_type=request] > Client.Request finish
07/09 19:57:21 ERR [xunlei-pan-cli] commands/runner.go:77 [stacks=["gitlab.xunlei.cn/xlppc/pan-cli/download.SetPipeLimit /xunlei-pan-cli/download/download_cgo.go:152"]&errors=设置下载和上传的连接数错误(9102)] > catch unuse error
07/09 19:57:21 ERR [xunlei-pan-cli] commands/runner.go:77 [errors=设置速度错误(9102)&stacks=["gitlab.xunlei.cn/xlppc/pan-cli/download.SetSpeed /xunlei-pan-cli/download/download_cgo.go:119"]] > catch unuse error
07/09 19:57:21 ERR [xunlei-pan-cli] download_runner/download.go:681  > moveDownloadSDKTmpFile ReadDir err:open /xunlei/downloads/download/*: no such file or directory btFilePath:/xunlei/downloads/download/*
07/09 19:57:21 ERR [xunlei-pan-cli] download/download_cgo.go:1166  > download.DownloadBt create_download err:下载(9102)
07/09 19:57:21 ERR [xunlei-pan-cli] download/download_cgo.go:752  > downloadBt err:下载(9102) url:*btfilepath:/xunlei/downloads/.bt/cb0ac0c2f9eed4985f6fbd576b1b4b9b.torrent
07/09 19:57:21 ERR [xunlei-pan-cli] download/download_cgo.go:816  > download_cgo.Task.Create downloadBt err:下载(9102) url:* filename:* basepath:/xunlei/downloads/download/ btFileBasePath:/xunlei/downloads/.bt token:
07/09 19:57:21 ERR [xunlei-pan-cli] download_runner/download.go:337  > DownloadRunner.runDownloadURL Download err:下载(9102) url:* fname:* basepath:/xunlei/downloads/download/ btFilePath:/xunlei/downloads/.bt
07/09 19:57:21 ERR [xunlei-pan-cli] download_runner/download.go:79 [user_id=*&real_path=/xunlei/downloads/download/*&error=下载(9102)&ip=*&mime_type=&task_id=VO1MLjjYnjfsxazAn14yZZnWA1&file_id=&package_name=pan.xunlei.cli.synology&name=*&sub_file_index=0&parent_folder_id=f2b23c4fccea37357b26cd1fb98fd70d&device_space=&basepath=/xunlei/downloads/download/&device_model=geminilake dsm 7.2-64570&status={"phase":"error"}&url=*&space=device_id#0d17d3901d1ee7cfec171d1800f7e0af&phase=PHASE_TYPE_ERROR&client_version=3.21.0&target=device_id#0d17d3901d1ee7cfec171d1800f7e0af&total_file_count=1&client_id=X9ibISwpIp8jQ4Ya&filename=*&platform=synology&type=user#download-url] > runCommonDownload create download error 下载(9102)
07/09 19:57:21 ERR [xunlei-pan-cli] runner/baserunner.go:331 [device_space=] > handler task error 下载(9102)
07/09 19:57:21 ERR [xunlei-pan-cli] ","space":"device_id#0d17d3901d1ee7cfec171d1800f7e0af"}
07/09 19:57:21 ERR [xunlei-pan-cli] runner/worker.go:213 [package_name=pan.xunlei.cli.synology&user_id=*&parent_folder_id=f2b23c4fccea37357b26cd1fb98fd70d&device_model=geminilake dsm 7.2-64570&ip=*&real_path=/xunlei/downloads/download/*&sub_file_index=0&client_version=3.21.0&mime_type=&file_id=&space=device_id#0d17d3901d1ee7cfec171d1800f7e0af&name=*&target=device_id#0d17d3901d1ee7cfec171d1800f7e0af&client_id=X9ibISwpIp8jQ4Ya&error=下载(9102)&task_id=VO1MLjjYnjfsxazAn14yZZnWA1&phase=PHASE_TYPE_ERROR&platform=synology&total_file_count=1&status={"phase":"error"}&url=*&type=user#download-url] > handler error 下载(9102)
```

**Comment by DUYA112233** [comment]
> 同unraid，前两天可以正常下载，今天报9102，所有文件均无法下载 ![QQ_1720527549102](https://private-user-images.githubusercontent.com/33391055/346953269-6ce88a9b-5fe6-42b0-bfb5-0c240d2023f7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1Mzk5MDMsIm5iZiI6MTcyMDUzOTYwMywicGF0aCI6Ii8zMzM5MTA1NS8zNDY5NTMyNjktNmNlODhhOWItNWZlNi00MmIwLWJmYjUtMGMyNDBkMjAyM2Y3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA5VDE1NDAwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJhOTY4ZmFmNDg3MDg0Y2QzOGQwNTQwYzMyMDQwOTdlNDIzZmM5MDNkYTk3YjNkOGM3NTA0NzgwYzVhOGEzNjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oEBVD_bTDpnlAXtA4wLmrklvot52d-KyhKt8dr2UJLM) 日志如下，部分信息用*代替
> 
> ```
> 07/09 19:57:15 INF [main] mount...
> 07/09 19:57:15 WRN [chroot] /usr/syno/synoman/webman/modules/authenticate.cgi has exist, ignore write
> 07/09 19:57:15 WRN [chroot] /etc/synoinfo.conf has exist, ignore write
> 07/09 19:57:15 INF [main] _  _ _  _ _  _ _    ____  _
> 07/09 19:57:15 INF [main]  \/  |  | |\ | |    |___  |
> 07/09 19:57:15 INF [main] _/\_ |__| | \| |___ |___  |
> 07/09 19:57:15 INF [main] daemon version: v3.20.0
> 07/09 19:57:15 INF [main] spk version: 3.21.0
> 07/09 19:57:15 INF [main] port: 2345
> 07/09 19:57:15 INF [main] ip: <nil>
> 07/09 19:57:15 INF [main] dashboard username: 
> 07/09 19:57:15 INF [main] dashboard password: 
> 07/09 19:57:15 INF [main] dir download: /xunlei/downloads
> 07/09 19:57:15 INF [main] dir data: /xunlei/data
> 07/09 19:57:15 INF [main] uid: 1000
> 07/09 19:57:15 INF [main] gid: 100
> 07/09 19:57:15 INF [main] prevent update: true
> 07/09 19:57:15 INF [main] chroot: /xunlei
> 07/09 19:57:15 INF [main] debug: false
> 07/09 19:57:15 INF [main] args: "--dashboard_port" "2345" "--dir_download" "/xunlei/downloads" "--dir_data" "/xunlei/data" "--uid" "1000" "--gid" "100" "--prevent_update" "--chroot" "/xunlei"
> 07/09 19:57:15 INF [mock] web started listen=[::]:2345
> 07/09 19:57:15 INF [xunlei-pan-cli] start cmd="/var/packages/pan-xunlei-com/target/bin/bin/xunlei-pan-cli-launcher.amd64 -launcher_listen unix:///var/packages/pan-xunlei-com/target/var/pan-xunlei-com-launcher.sock -pid /var/packages/pan-xunlei-com/target/var/pan-xunlei-com.pid -update_url http://127.0.0.1:2345/webman/3rdparty/pan-xunlei-com/version"
> 07/09 19:57:15 INF [xunlei-pan-cli] started pid=31
> 07/09 19:57:16 ERR [xunlei-pan-cli] loadHistory ReadFile err:open /xunlei/data/.drive/bin/.history: no such file or directory path:/xunlei/data/.drive/bin/.history
> 07/09 19:57:16 ERR [xunlei-pan-cli] killPid process.Signal SIGABRT err:os: process already finished
> 07/09 19:57:16 WRN [xunlei-pan-cli] kill process error:os: process already finished
> 07/09 19:57:16 ERR [xunlei-pan-cli] download/download_cgo.go:89 [TaskCfgPath=/xunlei/data/.drive/.TaskConfig&ret=9102] > init download_sdk TaskCfgPath error
> 07/09 19:57:17 ERR [xunlei-pan-cli] agent/agent.go:239  > directWakeup err wakupMessage agent is empty invalid character '<' looking for beginning of value <html>
> 07/09 19:57:17 ERR [xunlei-pan-cli] - <head><title>404 Not Found</title></head>
> 07/09 19:57:17 ERR [xunlei-pan-cli] - <body>
> 07/09 19:57:17 ERR [xunlei-pan-cli] - <center><h1>404 Not Found</h1></center>
> 07/09 19:57:17 ERR [xunlei-pan-cli] - <hr><center>nginx</center>
> 07/09 19:57:17 ERR [xunlei-pan-cli] - </body>
> 07/09 19:57:17 ERR [xunlei-pan-cli] - </html>
> 07/09 19:57:17 ERR [xunlei-pan-cli] - 
> 07/09 19:57:18 ERR [xunlei-pan-cli] "},"type":{"in":"user#runner"}}&trace_id=eUjoAjcO] > Client.Request finish
> 07/09 19:57:18 WRN [xunlei-pan-cli] download_runner/register_runner.go:64 [device_space=] > reload device config buffer size err 设置任务用于下载的内部缓存大小错误(9102)
> 07/09 19:57:18 WRN [xunlei-pan-cli] runner/runner.go:837 [target=device_id#0d17d3901d1ee7cfec171d1800f7e0af&sync=true&package_name=pan.xunlei.cli.synology&phase=PHASE_TYPE_RUNNING&platform=synology&round=2&user_id=*&pid=40&task_id=VO0sKyDTq-BG607OHa9FQ4r8A1&access=user#app,user#download,user#download-url,user#nfo&device_config={"device_space":"","speed_limit":-1,"runner_count":5,"download_infos":null,"download_paths":["/xunlei/downloads/"],"access_task_type":null,"file_mount":{},"single_task_max_mb":100,"single_task_reserve_mb":20,"overall_share_max_mb":200}&sleeper=:10m0s<10m0s<20m0s&client_id=X9ibISwpIp8jQ4Ya&downloads=[{"name":"","path":"/xunlei/downloads/","usage":4409941438464,"limit":7999426170880,"errmsg":"","is_root_path":false},{"name":"","path":"/usr/bin/","usage":4529942528,"limit":21474836480,"errmsg":"","is_root_path":true},{"name":"","path":"/usr/lib/","usage":4529942528,"limit":21474836480,"errmsg":"","is_root_path":true},{"name":"","path":"/run/","usage":4529942528,"limit":21474836480,"errmsg":"","is_root_path":true},{"name":"","path":"/tmp/","usage":4529942528,"limit":21474836480,"errmsg":"","is_root_path":true},{"name":"","path":"/usr/lib64/","usage":4529942528,"limit":21474836480,"errmsg":"","is_root_path":true}]&type=user#runner&accept=true&func_name=DeviceRunner.start&version=3.21.0&plm=syn&client_version=3.21.0&product_name=群晖&func_st=07/09 19:57:17&os=linux&space=&start_at=2024/07/03 19:25:44&name=群晖-mynas&device_model=geminilake dsm 7.2-64570&arch=amd64&trace_id=N02FmWnQ&ip=*] > start runner
> 07/09 19:57:19 ERR [xunlei-pan-cli] "},"type":{"in":"user#download-url,user#download"}}&limit=100&page_token=&space=device_id#0d17d3901d1ee7cfec171d1800f7e0af&type=&func_name=getRespBodyFromRemote&trace_id=lId0IL3G&lookup=addr:api-pan.xunlei.com ip:101.91.143.206,101.91.143.102,180.163.71.176,2408:4002:1f20::1de,] > Client.Request finish
> 07/09 19:57:19 ERR [xunlei-pan-cli] connect to [2408:4002:1f10::95]:443 &net.Peer{Id:"2408:4002:1f10::95", Option:net.PeerOpt{}, Weight:100, CurrentWeight:99, PreWeight:0, LastError:error(nil), Failed:0, TotalFailed:0, TotalCount:1, PreFailed:0, Object:net.IP{0x24, 0x8, 0x40, 0x2, 0x1f, 0x10, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x95}} err: dial tcp [2408:4002:1f10::95]:443: connect: network is unreachable
> 07/09 19:57:19 ERR [xunlei-pan-cli] "},"type":{"in":"user#download-url,user#download"}}&limit=100&page_token=&space=device_id#0d17d3901d1ee7cfec171d1800f7e0af&type=&pid=40&duration=0.0369&func_name=getRespBodyFromRemote&trace_id=LZeKlNxe&lookup=addr:api-pan.xunlei.com ip:101.91.143.102,101.91.143.206,180.163.71.176,2408:4002:1f20::1de,&resp_code=200&report_type=request&func_st=07/09 19:57:19&reqMethod=GET&resp_data_len=11945] > Client.Request finish
> 07/09 19:57:19 ERR [xunlei-pan-cli] connect to [2408:4002:1f10::2]:443 &net.Peer{Id:"2408:4002:1f10::2", Option:net.PeerOpt{}, Weight:100, CurrentWeight:99, PreWeight:0, LastError:error(nil), Failed:0, TotalFailed:0, TotalCount:1, PreFailed:0, Object:net.IP{0x24, 0x8, 0x40, 0x2, 0x1f, 0x10, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x2}} err: dial tcp [2408:4002:1f10::2]:443: connect: network is unreachable
> 07/09 19:57:19 ERR [xunlei-pan-cli] "},"type":{"in":"user#download-url,user#download"}}&limit=100&page_token=&space=device_id#0d17d3901d1ee7cfec171d1800f7e0af&type=&report_type=request&pid=40&func_st=07/09 19:57:19] > Client.Request finish
> 07/09 19:57:19 ERR [xunlei-pan-cli] download_runner/upload.go:299  > uploadWatcher SetUploadSwitch err:设置上传错误(9102)
> 07/09 19:57:20 ERR [xunlei-pan-cli] "},"type":{"in":"user#download-url,user#download"}}&limit=100&page_token=&space=device_id#0d17d3901d1ee7cfec171d1800f7e0af&type=&duration=0.0485&resp_data_len=11809&func_name=getRespBodyFromRemote&pid=40&func_st=07/09 19:57:20&trace_id=S5bFCLBs&resp_code=200&reqMethod=GET&report_type=request] > Client.Request finish
> 07/09 19:57:21 ERR [xunlei-pan-cli] commands/runner.go:77 [stacks=["gitlab.xunlei.cn/xlppc/pan-cli/download.SetPipeLimit /xunlei-pan-cli/download/download_cgo.go:152"]&errors=设置下载和上传的连接数错误(9102)] > catch unuse error
> 07/09 19:57:21 ERR [xunlei-pan-cli] commands/runner.go:77 [errors=设置速度错误(9102)&stacks=["gitlab.xunlei.cn/xlppc/pan-cli/download.SetSpeed /xunlei-pan-cli/download/download_cgo.go:119"]] > catch unuse error
> 07/09 19:57:21 ERR [xunlei-pan-cli] download_runner/download.go:681  > moveDownloadSDKTmpFile ReadDir err:open /xunlei/downloads/download/*: no such file or directory btFilePath:/xunlei/downloads/download/*
> 07/09 19:57:21 ERR [xunlei-pan-cli] download/download_cgo.go:1166  > download.DownloadBt create_download err:下载(9102)
> 07/09 19:57:21 ERR [xunlei-pan-cli] download/download_cgo.go:752  > downloadBt err:下载(9102) url:*btfilepath:/xunlei/downloads/.bt/cb0ac0c2f9eed4985f6fbd576b1b4b9b.torrent
> 07/09 19:57:21 ERR [xunlei-pan-cli] download/download_cgo.go:816  > download_cgo.Task.Create downloadBt err:下载(9102) url:* filename:* basepath:/xunlei/downloads/download/ btFileBasePath:/xunlei/downloads/.bt token:
> 07/09 19:57:21 ERR [xunlei-pan-cli] download_runner/download.go:337  > DownloadRunner.runDownloadURL Download err:下载(9102) url:* fname:* basepath:/xunlei/downloads/download/ btFilePath:/xunlei/downloads/.bt
> 07/09 19:57:21 ERR [xunlei-pan-cli] download_runner/download.go:79 [user_id=*&real_path=/xunlei/downloads/download/*&error=下载(9102)&ip=*&mime_type=&task_id=VO1MLjjYnjfsxazAn14yZZnWA1&file_id=&package_name=pan.xunlei.cli.synology&name=*&sub_file_index=0&parent_folder_id=f2b23c4fccea37357b26cd1fb98fd70d&device_space=&basepath=/xunlei/downloads/download/&device_model=geminilake dsm 7.2-64570&status={"phase":"error"}&url=*&space=device_id#0d17d3901d1ee7cfec171d1800f7e0af&phase=PHASE_TYPE_ERROR&client_version=3.21.0&target=device_id#0d17d3901d1ee7cfec171d1800f7e0af&total_file_count=1&client_id=X9ibISwpIp8jQ4Ya&filename=*&platform=synology&type=user#download-url] > runCommonDownload create download error 下载(9102)
> 07/09 19:57:21 ERR [xunlei-pan-cli] runner/baserunner.go:331 [device_space=] > handler task error 下载(9102)
> 07/09 19:57:21 ERR [xunlei-pan-cli] ","space":"device_id#0d17d3901d1ee7cfec171d1800f7e0af"}
> 07/09 19:57:21 ERR [xunlei-pan-cli] runner/worker.go:213 [package_name=pan.xunlei.cli.synology&user_id=*&parent_folder_id=f2b23c4fccea37357b26cd1fb98fd70d&device_model=geminilake dsm 7.2-64570&ip=*&real_path=/xunlei/downloads/download/*&sub_file_index=0&client_version=3.21.0&mime_type=&file_id=&space=device_id#0d17d3901d1ee7cfec171d1800f7e0af&name=*&target=device_id#0d17d3901d1ee7cfec171d1800f7e0af&client_id=X9ibISwpIp8jQ4Ya&error=下载(9102)&task_id=VO1MLjjYnjfsxazAn14yZZnWA1&phase=PHASE_TYPE_ERROR&platform=synology&total_file_count=1&status={"phase":"error"}&url=*&type=user#download-url] > handler error 下载(9102)
> ```

升级到3.20.1后暂时没有出现这个问题了

**Comment by flame9468** [comment]
cnk3x/xunlei:3.20.1 又出现了9102错误
WRN [xunlei-pan-cli] [status={"phase":"error"}&error=下载(9102)&type=user#download-url&spec={"phase":"running"}&target=device_id#84348fb7856de29b6cc6d5cfb47f5afc&space=device_id#84348fb7856de29b6cc6d5cfb47f5afc&mime_type=&ip=xxxxxxxxxxxxxxxx&sub_file_index=3&user_id=140336196&client_version=3.21.0&name=xxxxxxxxxxxxxxxxxxx_path=/downloads/xxxxxxxxxxxxxxxxxxx&task_id=VO4rg2tRClWGCbmL86DS-8RnA1&total_file_count=undefined&phase=PHASE_TYPE_ERROR&file_id=&package_name=pan.xunlei.cli.synology&device_model=geminilake dsm 7.2-64570&platform=synology] > handler error 下载(9102)

**Comment by flame9468** [comment]
[device_space=] > reload device config buffer size err 设置任务用于下载的内部缓存大小错误(9102)

**Comment by AemonCao** [comment]
经常会遇到这个问题，我目前的解决方式是在「更多」-「设置」里修改一下同时下载的任务数，例如从5改成1，然后重启容器，就能恢复正常。

**Comment by gotokpkuang** [comment]
3.21.1还是会报这个错误

**Comment by stingalways** [comment]
> 经常会遇到这个问题，我目前的解决方式是在「更多」-「设置」里修改一下同时下载的任务数，例如从5改成1，然后重启容器，就能恢复正常。

我也显示9102，按你的改成1，重启容器，依然如故

**Comment by winefox** [comment]
同样的9102错误。。。
爬楼看了，貌似没有好的解法
