### ISSUE TITLE
最新的版本，后台日志一直报ERR

### ISSUE THREAD

**Issue by endless1651** [cnk3x/xunlei#167]
确认
 我的版本是最新版本，我的版本号与 [version](https://github.com/cnk3x/xunlei/releases) 相同。
 我已经 [issue](https://github.com/cnk3x/xunlei/issues) 中搜索过，确认我的问题没有被提出过。
 我已经修改标题，将标题中的 描述 替换为我遇到的问题。
当前程序版本
v3.20.0 (https://github.com/cnk3x/xunlei/releases/tag/v3.20.0)

问题类型
后台日志报错

问题描述
后台一直报这种错误，无限循环

xunlei           | 07/08 10:10:54 ERR [xunlei-pan-cli] "},"type":{"in":"user#download-url,user#download"}}&limit=100&page_token=&space=device_id#bd4a89bb8ff9af7b443490884afd9381&type=&reqMethod=GET&trace_id=y34a4q1f&duration=0.1592] > Client.Request finish
xunlei           | 07/08 10:11:00 ERR [xunlei-pan-cli] "},"type":{"in":"user#download-url,user#download"}}&limit=100&page_token=&space=device_id#bd4a89bb8ff9af7b443490884afd9381&type=&resp_code=200&lookup=addr:api-pan.xunlei.com ip:140.206.220.164,140.206.225.227,2408:4002:1f20::1de,&func_name=getRespBodyFromRemote&trace_id=PAKL6Pqx&resp_data_len=57957] > Client.Request finish
xunlei           | 07/08 10:11:06 ERR [xunlei-pan-cli] "},"type":{"in":"user#download-url,user#download"}}&limit=100&page_token=&space=device_id#bd4a89bb8ff9af7b443490884afd9381&type=&reqMethod=GET&func_name=getRespBodyFromRemote&resp_data_len=57957&pid=53&trace_id=4us66HCg&lookup=addr:api-pan.xunlei.com ip:140.206.220.164,140.206.225.227,2408:4002:1f20::1de,] > Client.Request finish
xunlei           | 07/08 10:11:12 ERR [xunlei-pan-cli] "},"type":{"in":"user#download-url,user#download"}}&limit=100&page_token=&space=device_id#bd4a89bb8ff9af7b443490884afd9381&type=&func_st=07/08 10:11:12&lookup=addr:api-pan.xunlei.com ip:140.206.225.227,140.206.220.164,2408:4002:1f20::1de,&duration=0.1561&trace_id=MuB0H6Qx&resp_code=200&resp_data_len=57957] > Client.Request finish
xunlei           | 07/08 10:11:18 ERR [xunlei-pan-cli] "},"type":{"in":"user#download-url,user#download"}}&limit=100&page_token=&space=device_id#bd4a89bb8ff9af7b443490884afd9381&type=&resp_data_len=57957&lookup=addr:api-pan.xunlei.com ip:140.206.220.164,140.206.225.227,2408:4002:1f20::1de,&resp_code=200&duration=0.1482] > Client.Request finish
xunlei           | 07/08 10:11:24 ERR [xunlei-pan-cli] "},"type":{"in":"user#download-url,user#download"}}&limit=100&page_token=&space=device_id#bd4a89bb8ff9af7b443490884afd9381&type=&resp_data_len=57957] > Client.Request finish

**Comment by wzyjscz** [comment]
我查看了日志，也是一大堆ERR报错，和楼主差不多，我就不贴图了

**Comment by cnk3x** [comment]
这些ERR是迅雷程序报的，应该不影响
