### ISSUE TITLE
3.20.0 x64版本无法启动

### ISSUE THREAD

**Issue by witallwang** [cnk3x/xunlei#169]
无法启动，命令行和log如下：

root@omv:/srv/dev-disk-by-uuid-27a56845-c8f5-471c-bf93-0d3a333b3c95# docker run --network host  --privileged -v /srv/dev-disk-by-uuid-27a56845-c8f5-471c-bf93-0d3a333b3c95/data:/xunlei/data -v /srv/dev-disk-by-uuid-27a56845-c8f5-471c-bf93-0d3a333b3c95/downloads:/xunlei/downloads -p 2345:2345 cnk3x/xunlei
WARNING: Published ports are discarded when using host network mode
07/09 11:14:49 INF [main] mount...
07/09 11:14:49 INF [main] can't find package version, repair it
07/09 11:15:02 INF [main] _  _ _  _ _  _ _    ____  _
07/09 11:15:02 INF [main]  \/  |  | |\ | |    |___  |
07/09 11:15:02 INF [main] _/\_ |__| | \| |___ |___  |
07/09 11:15:02 INF [main] daemon version: v3.20.0
07/09 11:15:02 INF [main] spk version: 3.21.0
07/09 11:15:02 INF [main] port: 2345
07/09 11:15:02 INF [main] ip: <nil>
07/09 11:15:02 INF [main] dashboard username: 
07/09 11:15:02 INF [main] dashboard password: 
07/09 11:15:02 INF [main] dir download: /xunlei/downloads
07/09 11:15:02 INF [main] dir data: /xunlei/data
07/09 11:15:02 INF [main] uid: 
07/09 11:15:02 INF [main] gid: 
07/09 11:15:02 INF [main] prevent update: true
07/09 11:15:02 INF [main] chroot: /xunlei
07/09 11:15:02 INF [main] debug: false
07/09 11:15:02 INF [main] args: "--dashboard_port" "2345" "--dir_download" "/xunlei/downloads" "--dir_data" "/xunlei/data" "--prevent_update" "--chroot" "/xunlei"
07/09 11:15:02 INF [mock] web started listen=[::]:2345
07/09 11:15:02 INF [xunlei-pan-cli] start cmd="/var/packages/pan-xunlei-com/target/bin/bin/xunlei-pan-cli-launcher.amd64 -launcher_listen unix:///var/packages/pan-xunlei-com/target/var/pan-xunlei-com-launcher.sock -pid /var/packages/pan-xunlei-com/target/var/pan-xunlei-com.pid -update_url http://127.0.0.1:2345/webman/3rdparty/pan-xunlei-com/version"
07/09 11:15:02 INF [xunlei-pan-cli] started pid=31
07/09 11:15:05 ERR [xunlei-pan-cli] KillDrivePid ioutil.ReadFile err:open /var/packages/pan-xunlei-com/target/var/pan-xunlei-com.pid.child: no such file or directory
07/09 11:15:05 WRN [xunlei-pan-cli] kill process error:open /var/packages/pan-xunlei-com/target/var/pan-xunlei-com.pid.child: no such file or directory
07/09 11:15:05 ERR [xunlei-pan-cli] oauth2client/client.go:250 [device_space=] > client.Request GetCredentials err:access token is expired
07/09 11:15:05 ERR [xunlei-pan-cli] drive/events.go:93 [req={"space":"","filters":"{\"type\":{\"in\":\"TYPE_PLAY\"}}","limit":30,"page_token":""}] > GetEvents RawRequest err:{"error":"unauthenticated","error_description":"either credentials or access token not found(access token is expired)","error_uri":"https://api-pan.xunlei.com/drive/v1/events?filters={"type":{"in":"TYPE_PLAY"}}\u0026limit=30\u0026page_token=\u0026space=","HttpStatus":401}
07/09 11:15:05 ERR [xunlei-pan-cli] oauth2client/client.go:250 [device_space=] > client.Request GetCredentials err:access token is expired
07/09 11:15:05 ERR [xunlei-pan-cli] drive/client.go:664 [pid=38&func_name=Client.UpdateUserInfo&func_st=07/09 11:15:05&trace_id=0jZ9uVbh] > UpdateUserInfo Request err:{"error":"unauthenticated","error_description":"either credentials or access token not found(access token is expired)","error_uri":"https://xluser-ssl.xunlei.com/v1/user/me","HttpStatus":401} url:https://xluser-ssl.xunlei.com/v1/user/me
07/09 11:15:05 ERR [xunlei-pan-cli] runner/device_runners.go:63  > CreateTasksRunner UpdateUserInfo err:{"error":"unauthenticated","error_description":"either credentials or access token not found(access token is expired)","error_uri":"https://xluser-ssl.xunlei.com/v1/user/me","HttpStatus":401} deviceSpace:

**Comment by cnk3x** [comment]
日志到这一步应该是启动成功了。你说的无法启动是容器退出了吗？还是2345端口无法访问？

**Comment by witallwang** [comment]
我以为有Error就是启动失败
07/09 11:15:05 ERR [xunlei-pan-cli] KillDrivePid ioutil.ReadFile err:open /var/packages/pan-xunlei-com/target/var/pan-xunlei-com.pid.child: no such file or directory

今天下班后再试下看看网页正常不正常，到时候反馈，谢谢！

**Comment by witallwang** [comment]
打开网页，下载任务都正常。这个带ERR能正常运行的确刷新了我的认知，谢谢帮助！
