### ISSUE TITLE
重启后报错，这个是啥原因呢？

### ISSUE THREAD

**Issue by shentar** [cnk3x/xunlei#171]
07/15 11:22:46 INF [main] _  _ _  _ _  _ _    ____  _
07/15 11:22:46 INF [main]  \/  |  | |\ | |    |___  |
07/15 11:22:46 INF [main] _/\_ |__| | \| |___ |___  |
07/15 11:22:46 INF [main] daemon version: v3.20.0
07/15 11:22:46 INF [main] spk version: 3.21.0
07/15 11:22:46 INF [main] port: 2345
07/15 11:22:46 INF [main] ip: <nil>
07/15 11:22:46 INF [main] dashboard username: shentar
07/15 11:22:46 INF [main] dashboard password: rQSbC@N#^2FUUv
07/15 11:22:46 INF [main] dir download: /xunlei/downloads
07/15 11:22:46 INF [main] dir data: /xunlei/data
07/15 11:22:46 INF [main] uid: 
07/15 11:22:46 INF [main] gid: 
07/15 11:22:46 INF [main] prevent update: true
07/15 11:22:46 INF [main] chroot: /xunlei
07/15 11:22:46 INF [main] debug: false
07/15 11:22:46 INF [main] args: "--dashboard_port" "" "--dashboard_username" "" "--dashboard_password" "" "--dir_download" "/xunlei/downloads" "--dir_data" "/xunlei/data" "--prevent_update" "--chroot" "/xunlei"
07/15 11:22:46 INF [mock] web started listen=[::]:2345
07/15 11:22:46 INF [xunlei-pan-cli] start cmd="/var/packages/pan-xunlei-com/target/bin/bin/xunlei-pan-cli-launcher.amd64 -launcher_listen unix:///var/packages/pan-xunlei-com/target/var/pan-xunlei-com-launcher.sock -pid /var/packages/pan-xunlei-com/target/var/pan-xunlei-com.pid -update_url http://127.0.0.1:2345/webman/3rdparty/pan-xunlei-com/version"
07/15 11:22:46 INF [xunlei-pan-cli] started pid=31
07/15 11:22:47 ERR [xunlei-pan-cli] Lockfile TryLock err:Locked by other process
07/15 11:22:47 ERR [xunlei-pan-cli] - panic: Locked by other process
07/15 11:22:47 ERR [xunlei-pan-cli] - 
07/15 11:22:47 ERR [xunlei-pan-cli] - goroutine 1 [running]:
07/15 11:22:47 ERR [xunlei-pan-cli] - main.Lockfile()
07/15 11:22:47 ERR [xunlei-pan-cli] - 	/xunlei-pan-cli/cmd/pan-cli-launcher/main.go:1099 +0x1cd
07/15 11:22:47 ERR [xunlei-pan-cli] - main.main()
07/15 11:22:47 ERR [xunlei-pan-cli] - 	/xunlei-pan-cli/cmd/pan-cli-launcher/main.go:1127 +0x125
07/15 11:22:47 INF [xunlei-pan-cli] readlog done
07/15 11:22:47 ERR [xunlei-pan-cli] exited err="exit status 2"
07/15 11:22:47 ERR [main] exited! err="exit status 2"
07/15 11:22:47 INF [chroot] exited!
07/15 11:22:47 INF [main] exited!

**Comment by konglh80** [comment]
我之前遇到过一次这个情况，是因为我在终端中进入了配置目录导致锁定了目录，关了终端再重启就好了。
你可以试试关闭访问相关目录的终端或者其他形式的访问后，再重启试试。

**Comment by shentar** [comment]
> 我之前遇到过一次这个情况，是因为我在终端中进入了配置目录导致锁定了目录，关了终端再重启就好了。 你可以试试关闭访问相关目录的终端或者其他形式的访问后，再重启试试。

好的，我也升级到了最新的镜像，看起来没问题了。

**Comment by cnk3x** [comment]
v3.20.0版本启动时创建的var目录是root的，重启后迅雷用户无法操作lock文件，所以失败了，在 v3.20.1 已修复。
