### ISSUE TITLE
能不能添加armv7l的支持

### ISSUE THREAD

**Issue by Cainfish** [cnk3x/xunlei#189]
如题所述，能否添加对32位armv7l的支持的发行版，感谢！

**Comment by nan-1111** [comment]
+1

**Comment by cnk3x** [comment]
不能，目前迅雷不支持

**Comment by Cainfish** [comment]
> 不能，目前迅雷不支持

好的，感谢您。手上的电视盒子都是百兆口的，玩客云是千兆口的，但是是armv7l的（32位）的，感谢回复！
