### ISSUE TITLE
二维码加载不出来，

### ISSUE THREAD

**Issue by xinmans** [cnk3x/xunlei#24]
rt

**Comment by blankhang** [comment]
一样的问题
报错 设备检验失败 请重新登陆 但二维码加载不出来
麻烦大佬有空看看

**Comment by blankhang** [comment]
> 一样的问题 报错 设备检验失败 请重新登陆 但二维码加载不出来 麻烦大佬有空看看

bridge 网络不行
改 host  ok了！
