### ISSUE TITLE
20220903-0444前端报错无法使用

### ISSUE THREAD

**Issue by pangcrow** [cnk3x/xunlei#26]
前端JS
/webman/3rdparty/pan-xunlei-com/index.cgi/assets/index.5c5a16a4.js
index.5c5a16a4.js:54:23114
Raven.config("http://8bc57e373d6640299b5802bb1156c9eb@sentry-xluser-ssl.xunlei.com/11").install()
这个 http://8bc57e373d6640299b5802bb1156c9eb@sentry-xluser-ssl.xunlei.com/11 地址访问不到了
现象是无法出现下载界面和登录页面
一直在 “为什么会出现未找到远程下载设备？” 这个页面无法使用
接口
/webman/3rdparty/pan-xunlei-com/index.cgi/assets/static/background 402 (Payment Required)
这个没有原始数据不知道是什么,在这次报 402

**Comment by xianren813** [comment]
执行启动的身份权限不足,我用root正常

**Comment by pangcrow** [comment]
是root启动的,docker默认环境.不会是权限问题,还是怀疑 http://8bc57e373d6640299b5802bb1156c9eb@sentry-xluser-ssl.xunlei.com/11 这个是个暗桩

**Comment by pangcrow** [comment]
是被墙了,这个地址代理后就可以了
