### ISSUE TITLE
x86 linux版权限矛盾

### ISSUE THREAD

**Issue by xianren813** [cnk3x/xunlei#27]
如果用root身份运行,那么运行迅雷和插件网心云是没问题的,但是迅雷下载的文件也是属于root,无法在smb情况下删除管理,
如果用nobody或其他非root身份运行,那么迅雷是没问题的,下载文件的smb管理也没问题.但迅雷所带的插件全都不能正常运行,
不知道应该用什么权限运行合适,即能方便管理迅雷下载的文件,也能正常使用迅雷带的插件

**Comment by ljw98** [comment]
一样问题，不知道是否可以添加权限

**Comment by aizhimou** [comment]
请问下是如何使用普通用户运行起来的，我用普通用户根本没法安装和运行，如果是 sudo 安装运行的话，进程还是 root 用户，所以下载下来的文件也是 root 权限的，很难搞，而且迅雷下载的文件都是自带可执行权限的，这个太不安全的。

**Comment by cnk3x** [comment]
有空我再试试

**Comment by shoaky009** [comment]
一样把容器运行用户改成自己的UID因为要从/etc复制些文件没有权限导致起不来

**Comment by xianren813** [comment]
暂时现在用root身份运行,然后定时运行脚本更新迅雷下载的目录权限,算是能正常使用.但现在新机器上安装新版本又出现不能访问web的问题了,希望能解决或放出历史版本

**Comment by runninglol** [comment]
> > 配置UID和GID容器没办法启动， 提示/etc文件没有权限
> 
> ```shell
> docker run --restart unless-stopped --name=xunlei --network host -v xunlei:/xunlei/data --privileged \
>   -e UID=$(id -u) -e GID=$(id -g) -v <下载路径>:/xunlei/downloads -d cnk3x/xunlei
> ```

 -e UID=$(id -u) -e GID=$(id -g) 这个 id -u -g 得到的是root的0吧
用命令 id yourusername 得到的数字直接填进去

**Comment by zhoujieshantou** [comment]
chmod 757 目录就可以放在smb的目录下面了，如果看不到 ，关闭selnx

**Comment by chevy222** [comment]
一样的问题，生成的文件是root的，访问用户是普通用户，无法修改文件。

**Comment by qwerty00007** [comment]
dockerhub里面的最新镜像已经解决了这个问题，直接设置 PUID 和 PGID 就可以运行了。权限没有问题，注意运行要用特权模式。

https://hub.docker.com/r/cnk3x/xunlei/tags

**Comment by chevy222** [comment]
能不能systemd版本也搞个UID 和 GID呀，跪求了。

**Comment by chevy222** [comment]
不行，我试了 sudo chown -R 777 /var/packages 也是systemclt restart xunlei报错。

**Comment by dragonflylee** [comment]
> 不行，我试了 sudo chmod -R 777 /var/packages/pan-xunlei-com 也是systemclt restart xunlei报错。

请先确认 `/etc/systemd/system/xunlei.service` 是否编辑正确，

```
[Service]
Type=simple
ExecStart=/var/packages/pan-xunlei-com/xunlei run
LimitNOFILE=1024
LimitNPROC=512
User=1000
```

类似这样

**Comment by chevy222** [comment]
编辑了，加了User=你的用户名

**Comment by chevy222** [comment]
有一个.driver的目录好像启动访问不了

**Comment by dragonflylee** [comment]
[xunlei-v3.5.1.linux.x86_64.zip](https://github.com/cnk3x/xunlei/files/10980887/xunlei-v3.5.1.linux.x86_64.zip)

**Comment by chevy222** [comment]
> [xunlei-v3.5.1.linux.x86_64.7z](https://github.com/cnk3x/xunlei/files/10980887/xunlei-v3.5.1.linux.x86_64.zip)

大神，这个怎么玩？还是sudo chmod -R 777 /var/packages/pan-xunlei-com？

**Comment by dragonflylee** [comment]
不要 777，把原来的卸载了 装新的
权限问题尽量用 chown 而不是 chmod

**Comment by chevy222** [comment]
好的，太感谢了

**Comment by chevy222** [comment]
> 不要 777，把原来的卸载了 装新的 权限问题尽量用 chown 而不是 chmod
> 
> ```shell
> sudo ./xunlei install -dir $HOME/downloads --uid $(id -u) --gid $(id -g)
> ```

`chevy@deepin:~/Desktop$ sudo ./xunlei install -dir $HOME/downloads --uid $(id -u) --gid $(id -g)
[安装] 释放文件
[安装]   [Extract] /var/packages/pan-xunlei-com/target
[安装]   [Extract] /var/packages/pan-xunlei-com/target/version
[安装]   [Extract] /var/packages/pan-xunlei-com/target/xunlei-pan-cli-launcher.amd64
[安装]   [Extract] /var/packages/pan-xunlei-com/target/xunlei-pan-cli-web
[安装]   [Extract] /var/packages/pan-xunlei-com/target/xunlei-pan-cli.3.5.1.amd64
[安装]   [Extract] /var/packages/pan-xunlei-com/xunlei
[安装] 释放完成
[安装] 
[配置] 网页端口: 2345
[配置] 下载目录: /home/chevy/downloads
[配置] 
[服务] /usr/bin/systemctl daemon-reload
[服务] /usr/bin/systemctl enable xunlei
[服务] Created symlink /etc/systemd/system/multi-user.target.wants/xunlei.service → /etc/systemd/system/xunlei.service.
[服务] /usr/bin/systemctl start xunlei
chevy@deepin:~/Desktop$ systemctl status xunlei
× xunlei.service - 迅雷远程下载服务
     Loaded: loaded (/etc/systemd/system/xunlei.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Wed 2023-03-15 23:44:26 CST; 26s ago
    Process: 6725 ExecStart=/var/packages/pan-xunlei-com/xunlei run (code=exited, status=203/EXEC)
   Main PID: 6725 (code=exited, status=203/EXEC)

3月 15 23:44:26 deepin systemd[6725]: xunlei.service: Failed to execute /var/packages/pan-xunlei-com/xunlei: Permission denied
3月 15 23:44:26 deepin systemd[6725]: xunlei.service: Failed at step EXEC spawning /var/packages/pan-xunlei-com/xunlei: Permission denied`
启动不了，是哪里错了吗

**Comment by dragonflylee** [comment]
> ```shell
> /var/packages/pan-xunlei-com
> ```

能 `ls -hl /var/packages/pan-xunlei-com` 看一下文件权限么，另外你用的 Deepin 具体是哪个版本

**Comment by chevy222** [comment]
> > ```shell
> > /var/packages/pan-xunlei-com
> > ```
> 
> 能 `ls -hl /var/packages/pan-xunlei-com` 看一下文件权限么，另外你用的 Deepin 具体是哪个版本

```
chevy@deepin:~$ ls -hl /var/packages/pan-xunlei-com
总用量 78M
-rw-r--r-- 1 root  root    63 3月  15 23:44 config.json
drwxr-xr-x 3 chevy chevy 4.0K 3月  15 23:44 target
-rwx------ 1 root  root   78M 3月  15 23:44 xunlei
```
deepin20.8

**Comment by dragonflylee** [comment]
你需要 运行一下
```bash
sudo chmod +x var/packages/pan-xunlei-com/xunlei
sudo systemctl restart xunlei
```

**Comment by chevy222** [comment]
可以了

> 你需要 运行一下
> 
> ```shell
> sudo chmod +x /var/packages/pan-xunlei-com/xunlei
> sudo systemctl restart xunlei
> ```

**Comment by simonchen007** [comment]
> [xunlei-v3.5.1.linux.x86_64.7z](https://github.com/cnk3x/xunlei/files/10980887/xunlei-v3.5.1.linux.x86_64.zip)

这个文件是怎么找到的？
