### ISSUE TITLE
可以将端口绑定网卡吗？

### ISSUE THREAD

**Issue by luckyroach** [cnk3x/xunlei#32]

**Comment by cnk3x** [comment]
自己改改呗

`
#https://github.com/cnk3x/xunlei/blob/docker/xlp/xlp.go#L127

-  s := &http.Server{Addr: fmt.Sprintf(":%d", port), Handler: mux}
+ ip := os.Getenv(ENV_WEB_IP)
+ s := &http.Server{Addr: fmt.Sprintf("%s:%d", ip, port), Handler: mux}
`
