### ISSUE TITLE
openwrt安装老是显示找不到文件

### ISSUE THREAD

**Issue by JF950908** [cnk3x/xunlei#34]
fork/exec /var/packages/pan-xunlei-com/target/xunlei-pan-cli-launcher: no such file or directory。明明这个目录也有这个文件啊

**Comment by cnk3x** [comment]
是的，能说说你的安装环境吗？

**Comment by dragonflylee** [comment]
因为 openwrt 是 musl 的 c 库环境，而 xunlei-pan-cli-launcher 依赖的是 glibc 的环境，
建议 `ldd xunlei-pan-cli-launcher` 看看依赖哪些 so 库，从 debian 复制过来补全

**Comment by Zy143L** [comment]
> 因为 openwrt 是 musl 的 c 库环境，而 xunlei-pan-cli-launcher 依赖的是 glibc 的环境， 建议 `ldd xunlei-pan-cli-launcher` 看看依赖哪些 so 库，从 debian 复制过来补全

补全没戏 补了/lib64/ld-linux-x86-64.so.2
然后主程序 又一堆报错 还是glibc的..
