### ISSUE TITLE
有计划支持armv7架构吗？

### ISSUE THREAD

**Issue by umifly** [cnk3x/xunlei#35]

**Comment by cnk3x** [comment]
得看迅雷本身支持不支持。

**Comment by gzxief** [comment]
已解决64位CPU安装armbian(armv7)安装迅雷下载的问题，盒子安装好armbian(armv7)再移植aarch64的系统，再安装docker就可以了，我在恩山写了教程了

**Comment by xiaoliziapp** [comment]
> 已解决64位CPU安装armbian(armv7)安装迅雷下载的问题，盒子安装好armbian(armv7)再移植aarch64的系统，再安装docker就可以了，我在恩山写了教程了

给个链接地址
