### ISSUE TITLE
wsl环境下，用host模式无法使用ip:2345模式访问

### ISSUE THREAD

**Issue by shua1zh** [cnk3x/xunlei#36]
系统是Windows 10，安装了WSL和Docker Desktop，使用host网路模式，无法使用ip:2345模式访问，改成Bridge可以，但是速度很慢。

**Comment by cnk3x** [comment]
wsl环境host网络本来就无法访问的。不管任何容器，wsl环境本来就不支持host网络

**Comment by Beginner-tl** [comment]
Bridge只有百兆的速度正常吗

**Comment by q1uxu** [comment]
wsl的网路模式选择"镜像"，然后再开启“主机地址环回”
![image](https://github.com/user-attachments/assets/af34eb84-c5f1-40e8-ac1a-d76ac45163dc)
