### ISSUE TITLE
我给迅雷docker添加了图标后突然就启动不了日志提示dev目录绑定失败

### ISSUE THREAD

**Issue by zicoad** [cnk3x/xunlei#38]
日志提示这个
2022/10/22 16:11:20 [syno] 绑定目录 "/dev" -> "/xunlei/dev" 失败: operation not permitted
就只有这个，我更新图标前都是正常运行的，后面重新安装都这样。

**Comment by cnk3x** [comment]
什么图标？ 这个提示应该是权限问题，请使用root账号并赋予 privileged 权限运行。

**Comment by hyy34** [comment]
> privileged

请问使用portainet如何赋予容器 privileged 权限？

**Comment by hyy34** [comment]
> 什么图标？ 这个提示应该是权限问题，请使用root账号并赋予 privileged 权限运行。

请问使用portainet如何赋予容器 privileged 权限？
