### ISSUE TITLE
最新docker镜像v3.0.2安装完之后提示v3.1.0新版本无法升级

### ISSUE THREAD

**Issue by cfscn** [cnk3x/xunlei#39]
最新docker镜像v3.0.2安装完之后提示v3.1.0新版本无法升级

最后重启提示请勿刷新浏览器  然后失败.

**Comment by cnk3x** [comment]
提示 "升级失败:健康检查不通过"

**Comment by cnk3x** [comment]
暂时不要升级吧，最近没什么时间跟进

**Comment by mela93** [comment]
是迅雷增加了什么检测机制吗😂😂😂

**Comment by kingjoydom** [comment]
> 暂时不要升级吧，最近没什么时间跟进

求大佬升级新版本，新版本的3.18可以配合迅雷TV在电视上使用。

**Comment by mela93** [comment]
> 

其实我倒是想要那个按时间段限速的功能😂😂😂

**Comment by mela93** [comment]
> > 暂时不要升级吧，最近没什么时间跟进
> 
> 求大佬升级新版本，新版本的3.18可以配合迅雷TV在电视上使用。

其实我倒是想要那个按时间段限速的功能😂😂😂

**Comment by mela93** [comment]
> > 暂时不要升级吧，最近没什么时间跟进
> 
> 求大佬升级新版本，新版本的3.18可以配合迅雷TV在电视上使用。

看这里：https://github.com/cnk3x/xunlei/issues/43#issuecomment-1335192557
