### ISSUE TITLE
请求更新

### ISSUE THREAD

**Issue by trombonist852** [cnk3x/xunlei#43]
大佬 3.13出来啦  能否辛苦更新一下呀？感激不尽！

**Comment by dragonflylee** [comment]
[xunlei-v3.1.5.linux.x86_64.tar.xz](https://github.com/cnk3x/xunlei/files/10141238/xunlei-v3.1.5.linux.x86_64.tar.gz)

**Comment by trombonist852** [comment]
> docker load -i [xunlei.3.1.8.amd64.tar.xz](https://github.com/dragonflylee/xunlei/releases/download/v3.1.8/xunlei.3.1.8.amd64.tar.xz) 导入镜像即可使用

感谢大佬！已经更新成功了
