### ISSUE TITLE
启动有三个报错看一下，最新版访问网页也经常出现502

### ISSUE THREAD

**Issue by Dellear** [cnk3x/xunlei#49]
![image](https://user-images.githubusercontent.com/22325851/206913954-15177317-0a54-4e11-873c-6270db910347.png)
502一般重建镜像可以正常，忘记截图了

**Comment by WillFindX** [comment]
我的启动后也是一样的日志，网页一直都是502打不开，重启、重装都不行。我的设备是我家云，有解决办法吗？
