### ISSUE TITLE
能否有ARM64支持？

### ISSUE THREAD

**Issue by Lorde627** [cnk3x/xunlei#5]

**Comment by zxjrainbow** [comment]
自己重新打包就行。我是自己重新打包了在树莓4B 上安装的。

**Comment by coolsnowwolf** [comment]
求打包好的 ARM64 BIN 测试

**Comment by zxjrainbow** [comment]
这个是我根椐说明编译的，可以试试。
链接: https://pan.baidu.com/s/1NZCoPuqkzlfmz7nClnZ3Xw?pwd=bvtn 提取码: bvtn 

下面是我实操的过程。

1.克隆源码
下载官方的对应架构的群晖版迅雷spk文件 https://docs.qq.com/doc/DQVJpbEVGZXV0anNa 里面有最新的文件下载地址
用解压软件解压spk文件
找到里面的 package.tgz, 再解压一次
找到里面的文件: xunlei-pan-cli-launcher, xunlei-pan-cli.版本号.amd64, index.cgi
找到里面的文件: 
同目录的 version 文件
与 xunlei-pan-cli.版本号.amd64 复制一份并改名为 xunlei-pan-cli.版本号
将 index.cgi 复制一份并改名为 xunlei-pan-cli-web
将 xunlei-pan-cli-launcher.arm64 复制一份并改名为 xunlei-pan-cli-launcher
将这些文件复制到源码target目录
改完要改的后编译。
改完名后是这样的： 

2.编译
复制整个目录到树莓派的某个目录下，如： /mnt/NAS/xunlei/
 
同时要注意要先安装 go 语言。
要先配置一下GO语言，
自动下载： go env -w GO111MODULE=on
设置环境为国内代理： go env -w GOPROXY=https://goproxy.cn,direct
然后执行： ./build.sh
等编译完成即可。


在生成的 bin 目录中，执行：
# 安装
./xunlei install --port=6700 --download-dir=/mnt/download
# 上面命令后面的参数 --port=后面接端口号, --download-dir=接下载文件夹，按自己的需求改
# 下载文件夹装好后没得改了，要改的话，卸载重装，或者用软链接
# 有时候安装失败，可以先运行卸载一次，再安装
# 启动后，浏览器访问你的设备地址+端口号绑定迅雷就可以了。 比如： http://192.168.1.2:6700
# 当前版本支持迅雷官方公测前的在线更新(不需要重新安装)

# 卸载
sh uninstall.sh

# 服务控制
# 启动
systemctl start xunlei
# 停止
systemctl stop xunlei
# 状态
systemctl status xunlei
# 查看日志(ctrl+c退出日志查看)
journalctl -fu xunlei

**Comment by Lorde627** [comment]
> 求打包好的 ARM64 BIN 测试

https://github.com/FuxkTME/xunlei-arm64/releases/tag/v2.5.0

[安装] 释放文件
[安装]   [Extract] /var/packages/pan-xunlei-com/target
[安装]   [Extract] /var/packages/pan-xunlei-com/target/version
[安装]   [Extract] /var/packages/pan-xunlei-com/target/xunlei-pan-cli-launcher
[安装]   [Extract] /var/packages/pan-xunlei-com/target/xunlei-pan-cli-web
[安装]   [Extract] /var/packages/pan-xunlei-com/target/xunlei-pan-cli.2.5.0.arm64
[安装]   [Extract] /var/packages/pan-xunlei-com/xunlei
[安装] 释放完成
[安装]
[配置] 网页端口: 2345
[配置] 下载目录: /mnt/sda2/Movies
[配置]
**open /etc/systemd/system/xunlei.service: no such file or directoryroot**

MR7350 跑出来的结果，大雕能帮忙看下吗？OpenWrt和Lunix配置文件夹好像不同。

**Comment by Lorde627** [comment]
> 

谢谢你的指导！~

**Comment by zxjrainbow** [comment]
你这个，只要修改一下里面的install.sh文件就行了。我的建议就是你自己编译。实际就是用主人家的编译脚本加上迅雷的执行文件来打成一个安装包。要相信自己，你可以的~

**Comment by Lorde627** [comment]
> 你这个，只要修改一下里面的install.sh文件就行了。我的建议就是你自己编译。实际就是用主人家的编译脚本加上迅雷的执行文件来打成一个安装包。要相信自己，你可以的~

我是直接下载编译好的二进制文件使用./xunlei install --port=6700 --download-dir=/mnt/download 命令运行的，我看build.sh里面好像没有可以修改配置目录的地方？真的是太小白了😂

**Comment by Lorde627** [comment]
> 你这个，只要修改一下里面的install.sh文件就行了。我的建议就是你自己编译。实际就是用主人家的编译脚本加上迅雷的执行文件来打成一个安装包。要相信自己，你可以的~

没想到刚刚完成了人生第一个编译工作哈哈哈！
但是问题又来了,OpenWrt好像没有systemctl的指令所以启动服务出问题了😭

[安装] 释放完成
[安装]
[配置] 网页端口: 6700
[配置] 下载目录: /mnt/sda2/movies
[配置]
[服务] systemctl daemon-reload
[服务] exec: "systemctl": executable file not found in $PATH
[服务] systemctl enable xunlei
[服务] exec: "systemctl": executable file not found in $PATH
[服务] systemctl start xunlei
[服务] exec: "systemctl": executable file not found in $PATH

**Comment by FunctionXJB** [comment]
> 这个是我根椐说明编译的，可以试试。 链接: https://pan.baidu.com/s/1NZCoPuqkzlfmz7nClnZ3Xw?pwd=bvtn 提取码: bvtn
> 
> 下面是我实操的过程。
> 
> 1.克隆源码 下载官方的对应架构的群晖版迅雷spk文件 https://docs.qq.com/doc/DQVJpbEVGZXV0anNa 里面有最新的文件下载地址 用解压软件解压spk文件 找到里面的 package.tgz, 再解压一次 找到里面的文件: xunlei-pan-cli-launcher, xunlei-pan-cli.版本号.amd64, index.cgi 找到里面的文件: 同目录的 version 文件 与 xunlei-pan-cli.版本号.amd64 复制一份并改名为 xunlei-pan-cli.版本号 将 index.cgi 复制一份并改名为 xunlei-pan-cli-web 将 xunlei-pan-cli-launcher.arm64 复制一份并改名为 xunlei-pan-cli-launcher 将这些文件复制到源码target目录 改完要改的后编译。 改完名后是这样的：
> 
> 2.编译 复制整个目录到树莓派的某个目录下，如： /mnt/NAS/xunlei/
> 
> 同时要注意要先安装 go 语言。 要先配置一下GO语言， 自动下载： go env -w GO111MODULE=on 设置环境为国内代理： go env -w GOPROXY=https://goproxy.cn,direct 然后执行： ./build.sh 等编译完成即可。
> 
> 在生成的 bin 目录中，执行：
> 
> # 安装
> ./xunlei install --port=6700 --download-dir=/mnt/download

你好，能在分享下打包好的arm64包吗？我自己打包用小星插件有问题，无法识别网络nat类型和upnp

**Comment by zxjrainbow** [comment]
链接: https://pan.baidu.com/s/1e4W-28iWKpIGTT0ZfhZ_qw?pwd=9ysf 提取码: 9ysf

**Comment by FunctionXJB** [comment]
> 链接: https://pan.baidu.com/s/1e4W-28iWKpIGTT0ZfhZ_qw?pwd=9ysf 提取码: 9ysf

感谢，测试了下，和我的一样，小星插件都是无法识别nat状态和upnp。o(╥﹏╥)o
