### ISSUE TITLE
大佬 折腾一天了还是启动失败

### ISSUE THREAD

**Issue by beilsn** [cnk3x/xunlei#50]
从群晖docker折腾到DEBIAN的DOCEKR都是启动失败，要不启动进去hiu网页丢失；
大佬能否帮忙看看是什么问题，多谢了！

**Comment by cnk3x** [comment]
能详细说说吗？

**Comment by cnk3x** [comment]
你这是安装网心云插件吗，插件支持有限，因为该迅雷原本设计不是在容器内运行的

不过你都使用docker了，为何不直接用网心云的容器魔方呢，不是更好一些么，
至少跟迅雷不互相影响。

**Comment by beilsn** [comment]
> 你这是安装网心云插件吗，插件支持有限，因为该迅雷原本设计不是在容器内运行的
> 
> 不过你都使用docker了，为何不直接用网心云的容器魔方呢，不是更好一些么， 至少跟迅雷不互相影响。

本意是要用大佬的docker纳思小星，不是容器魔方。

**Comment by cnk3x** [comment]
已更新底包3.7.1，现在可以尝试一下纳思小星了
