### ISSUE TITLE
插件能不能解决

### ISSUE THREAD

**Issue by taowazi007** [cnk3x/xunlei#51]
在用lede的自编译固件上可以使用,测速插件可以用,网心云插件无法启动,但就是为了用网心云插件

**Comment by cnk3x** [comment]
我没有用到插件，所以暂时不能保证会解决。

**Comment by xingkong2100** [comment]
网心云插件如果能够解决就真心太好了。一直找找不到能够用的

**Comment by cnk3x** [comment]
已更新底包3.7.1，现在可以尝试一下纳思小星了

> 网心云插件如果能够解决就真心太好了。一直找找不到能够用的
