### ISSUE TITLE
经常502显示，需要重启docker解决。

### ISSUE THREAD

**Issue by hyy34** [cnk3x/xunlei#55]
Portainer 创建docker，赋予了Privileged mode，但是过一段时间，大约一天，就无法打开web，显示502错误，需要重新stop再start几次镜像才可以。log里没发现什么异常、

**Comment by hyy34** [comment]
也是怪了，有个istoreos的路由器，那里面的docker安装的xunlei就没有这个问题，实在搞不懂，但是路由器是插件自动安装的，是不是我什么地方操作不对了，请教下大神，我应该怎么修改。

**Comment by hyy34** [comment]
现在的log如下，
![XCdMCmFOqk](https://user-images.githubusercontent.com/26433019/211017378-f32ffc4e-6747-48f4-9dbf-19e1d28b349a.png)

**Comment by cnk3x** [comment]
迅雷检查到有3.1.10自动更新，然后健康检查失败，再回滚3.1.8失败，就502了。 如果你istoreos是arm版的是没问题的，因为arm版的还没有官方更新。 这个问题已关注，有空跟进一下。

**Comment by hyy34** [comment]
> 迅雷检查到有3.1.10自动更新，然后健康检查失败，再回滚3.1.8失败，就502了。 如果你istoreos是arm版的是没问题的，因为arm版的还没有官方更新。 这个问题已关注，有空跟进一下。

istoreos 的cpu是N3700，应该也是X64的。出问题的机器是i5 8600T，安装的是OMV5 然后Portainer创建的docker。istoreos运行几天了，一点问题没有，OMV5的机器基本上每天都会出现这个问题。

**Comment by cnk3x** [comment]
我更新了底包到3.1.10，试试看。

**Comment by hyy34** [comment]
> 我更新了底包到3.1.10，试试看。 重新 pull ..../xunlei:latest 或者指定版本号 ..../xunlei:3.1.10

好的，我试试大佬，过两天反馈。感谢。

**Comment by cnk3x** [comment]
阻止更新理论上是有可能做到的，毕竟在容器里，暴力一点就直接在容器里进行dns拦截。

**Comment by hyy34** [comment]
> 阻止更新理论上是有可能做到的，毕竟在容器里，暴力一点就直接在容器里进行dns拦截。

反馈，这几天貌似没出什么问题。老大还是发布个阻断更新的镜像吧

**Comment by hyy34** [comment]
> 阻止更新理论上是有可能做到的，毕竟在容器里，暴力一点就直接在容器里进行dns拦截。

又更新了？？重新启动都不好使了，重新部署了下才好。

**Comment by imwower** [comment]
3.4.0 版本不好使了，启动后就显示502错误，有什么解决方案吗？
