### ISSUE TITLE
arm64本机服务运行3.1.10无法启动

### ISSUE THREAD

**Issue by zhang-ss1** [cnk3x/xunlei#56]
运行方式：本机服务运行
root账号运行：是
平台：arm64
迅雷版本：3.1.10
自行编译的，启动有错误，如下图所示。大佬能不能出个编译好的arm64版本？
![O{UUO}B{2E4YK0OS}G@09YB](https://user-images.githubusercontent.com/74695580/210163121-641b29ff-97b6-4a37-9380-ed0d8c5c6dd8.png)
![XPAC5%N_GKB4KA$TMY7_J46](https://user-images.githubusercontent.com/74695580/210163124-2c2fb9a5-a581-454e-bd11-4b97e4794842.png)

**Comment by zhang-ss1** [comment]
解决了，原来是自己弄错了个文件，感谢大佬的教程！！

**Comment by FunctionXJB** [comment]
你好，请问你用小星了吗？我的arm64版本小星无法识别网络类型和upnp

**Comment by zhang-ss1** [comment]
> 你好，请问你用小星了吗？我的arm64版本小星无法识别网络类型和upnp

一样的
