### ISSUE TITLE
迅雷systemd版本能否增加basic验证

### ISSUE THREAD

**Issue by chenxudong2020** [cnk3x/xunlei#60]
docker版本不能使用插件 为了使用插件使用了systemd版本 但是systemd版本下载页面没验证

**Comment by cnk3x** [comment]
systemd 版本好久没维护了。 我以为没人用了呃。。。

**Comment by chenxudong2020** [comment]
有用啊，可以用插件，unraid我用了就是挂网心但是unraid不能重启，纳斯小星收益比docker高 蛋疼





---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年1月12日(周四) 凌晨1:36
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [cnk3x/xunlei] 迅雷systemd版本能否增加basic验证 (Issue #60)




 
systemd 版本好久没维护了。 我以为没人用了呃。。。

**Comment by chevy222** [comment]
> systemd 版本好久没维护了。 我以为没人用了呃。。。

能不能更新一下systemd 版本啊。

**Comment by chenxudong2020** [comment]
求大佬更新下systemd 增加basic验证

**Comment by Shiyang-Wang** [comment]
跪求大佬更新下system版本。。。
