### ISSUE TITLE
打开网页登录弹出会员专享

### ISSUE THREAD

**Issue by endlingzyb** [cnk3x/xunlei#64]
大佬，x86_64 docker下ubuntu:18.04 root用户systemd版编译最新版本v3.1.10运行，登录后弹出会员专享，这个应该怎么解决呀?
![image](https://user-images.githubusercontent.com/52320305/213250383-dbc28396-b7e7-44bb-bf7c-b468bf528d5f.png)

还要最新版spk包内是xunlei-pan-cli-launcher.amd64，编译后打开网页502，改成xunlei-pan-cli-launcher后才能正常打开网页

**Comment by FunctionXJB** [comment]
非docker环境下不会要求会员
