### ISSUE TITLE
登录后只要知道IP和端口就可以直接访问

### ISSUE THREAD

**Issue by wishday** [cnk3x/xunlei#66]
登录后只要知道IP和端口就可以直接访问吗？
对于暴露公网ip或ddns的nas感觉很危险啊
不暴露公网ip又没法实现远程下载

**Comment by dragonflylee** [comment]
可以通过页面  https://pan.xunlei.com/yc/home/  远程控制

**Comment by wishday** [comment]
有远程方案，确实可以不开公网ip或DDNS了，
不过一般使用想用host模式或macvlan模式提高性能，同时也可以给docker分配ipv6公网ip提高下载速度和做种能力
建议能像TR一样增加登陆验证，而且能否不用特权容器模式启动，会更安全

**Comment by dragonflylee** [comment]
不是已经有 basic auth 了么，上个版本更新的

**Comment by wishday** [comment]
小白用户 请问如何在portainer设置basic  auth   :）
另外有没有可能不需要特权模式运行？

**Comment by dragonflylee** [comment]
环境变量 `XL_BA_USER` 和 `XL_BA_PASSWORD`: 给迅雷面板添加基本验证（明码）

**Comment by wishday** [comment]
感谢，basic auth已解决
特权模式看来很难去掉了，估计是要绑定/dev目录模拟群晖环境导致？
