### ISSUE TITLE
下载速度可以超过100m吗

### ISSUE THREAD

**Issue by Beginner-tl** [cnk3x/xunlei#68]
这个镜像我下载速度好像被限制在了100m，用docker装了测速软件看是可以跑500m的，应该不会是docker的问题吧，有没有解除限速的方法

**Comment by cnk3x** [comment]
100Mbps 还是 100MB/s？ 实测在源没问题的情况下，host网络下我600Mbps的宽带是可以跑满的。

**Comment by Beginner-tl** [comment]
可以跑600Mbps？我用里面的迅雷测速也最多测100M的速度，选择也是一样，用的源在官方的迅雷客户端是可以达到700M的速度的，是用的你这边host一键部署的

**Comment by Beginner-tl** [comment]
额，我看了下我是docker desktop ,只能 bridge 网络，所以 bridge 网络最多限制100M吗

**Comment by dragonflylee** [comment]
迅雷看到的 100M 是 100MB/s, 相当于 800Mbps

**Comment by Beginner-tl** [comment]
不是，测试了很多次不同设备，好像docker desktop wsl2 bridge 网络下速度最多13m/s，我也测试了一些资源，本地客户端下载非常快，到了这个镜像就一直0b/s，连windows热门镜像都最多5m，本地迅雷直接下载速度可以达到50m/s，不知道什么原因

**Comment by Beginner-tl** [comment]
同时尝试了迅雷会员和非会员登陆速度是一样的

**Comment by dragonflylee** [comment]
不明白的是，既然是windows为啥不直接用pc版的迅雷（也支持远程控制），还要绕一圈用 docker

**Comment by Beginner-tl** [comment]
windows版本的已经不支持远程了吧

**Comment by dragonflylee** [comment]
> 

![thunder](https://user-images.githubusercontent.com/6219280/218677148-99203c2b-6eb5-48a2-9201-cac0430441cc.png)

**Comment by Beginner-tl** [comment]
这是哪个版本的迅雷，是官方最新的吗

**Comment by dragonflylee** [comment]
是最新版

**Comment by qq461613840** [comment]
我测试最高达到110M/s哦 比较满意 比windows客户端的快
