### ISSUE TITLE
能更新下直装的版本吗

### ISSUE THREAD

**Issue by mtyzaq** [cnk3x/xunlei#70]
最近老是报错，不跑流量，这是啥情况
INFO detect lexar error:env ea94acab567b9cc724e943be3e4ac5c5 not exist
Feb 11 02:39:38 WXY xunlei[2353]: 2023-02-11T02:39:38.484287936+08:00 INFO detect docker error:stat /.dockerenv: no such file or directory
Feb 11 02:39:38 WXY xunlei[2353]: 2023-02-11T02:39:38.484303086+08:00 INFO detect zspace error:env a68b3d890b860d0165a8f6f66acc6d45 not exist
Feb 11 02:39:38 WXY xunlei[2353]: 2023-02-11T02:39:38.485130843+08:00 INFO detect platform: synology X9ibISwpIp8jQ4Ya nasid: labels: [withQrcodeLogin withOtherAuthLogin withP>

**Comment by cnk3x** [comment]
提供的信息不详。
