### ISSUE TITLE
在 Alpine 下运行，出现段错误

### ISSUE THREAD

**Issue by ctaoist** [cnk3x/xunlei#8]
讲道理，完全静态编译，禁用 CGO，在alpine里运行应该不会出错才对啊

```
Segmentation fault
```

>ps. 我是想在docker里运行

**Comment by ctaoist** [comment]
应该是 迅雷本身二进制文件依赖glibc库，拉闸

**Comment by cnk3x** [comment]
原则上busybox甚至scratch都可以跑起来，但你得琢磨把迅雷本身运行需要的链接库给找全了，x86下我试过是可以的，镜像体积能缩小到60多M，但是如果迅雷官方更新的话，他所需要的链接库可能会有变，如果把glibc全打包进去，相对Ubuntu镜像来说就没啥优势了，我测试过，busybox+glibc完整包只比Ubuntu18.04小10来M，没必要折腾了。arm没有机器所以不能确定他要的链接库，所以通用性和稳定性来说，用ubuntu基础镜像省事有稳定。

**Comment by Zy143L** [comment]
![ec3b57bf842b772c9a65c17a0e2402e](https://user-images.githubusercontent.com/21352718/213198432-12c986ee-6b64-4357-931b-8bbbab835381.png)

拉闸

**Comment by charlzyx** [comment]
我在 LXC alpine 里面找到一个解决办法, 应该是通用 
alpine:3.18
主要是两个依赖的问题 glibc 和 libstdc++

[glibc](https://github.com/sgerrand/alpine-pkg-glibc/issues/210) 这位老哥用爱发点自己build了一个比较新的版本

```bash
echo 'https://storage.sev.monster/alpine/edge/testing' | tee -a /etc/apk/repositories
wget https://storage.sev.monster/alpine/edge/testing/x86_64/sevmonster-keys-1-r0.apk
sh -c '
  apk add --allow-untrusted ./sevmonster-keys-1-r0.apk
  apk update \
    && apk add gcompat \
    && rm -rf /lib/ld-linux-x86-64.so.2 \
    && apk add --force-overwrite glibc \
    && apk add glibc-bin'
```

至于 libstdc++ 就简单了 , 直接
```bash
apk add libstdc++
```

之后就可以了

**Comment by charlzyx** [comment]
> 执念啊，增加了一个[busybox镜像](https://github.com/cnk3x/xunlei/blob/main/docker/busybox/Dockerfile)，比 alpine更小
> 
> ```
> docker pull cnk3x/xunlei:busybox
> docker pull cnk3x/xunlei:3.20.1-busybox
> ```
> 
> 其实跟ubuntu镜像占用空间差不了多少的，容器镜像的基础层是所有镜像共享。用ubuntu镜像会少出些问题
> 
> ![image](https://private-user-images.githubusercontent.com/2490599/355392501-a7efd1d1-62b0-43d1-8ab7-fa171443427f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5MzcwNTAsIm5iZiI6MTcyMjkzNjc1MCwicGF0aCI6Ii8yNDkwNTk5LzM1NTM5MjUwMS1hN2VmZDFkMS02MmIwLTQzZDEtOGFiNy1mYTE3MTQ0MzQyN2YucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDZUMDkzMjMwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzE1NTk2MGQwMTM4NTBlYmJkNGQzZGFiOGZiMDM1ZTUxOTc1NDI5Mjg0OGEyYjhhZWE4YjVjMjY0Y2QzYzU0YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.W4x_tUO33kdMnTItA0pYKWAHVoYI5v46BB8_Lw5Eydo)
> 
> > 我在 LXC alpine 里面找到一个解决办法, 应该是通用 alpine:3.18 主要是两个依赖的问题 glibc 和 libstdc++
> > [glibc](https://github.com/sgerrand/alpine-pkg-glibc/issues/210) 这位老哥用爱发点自己build了一个比较新的版本
> > ```shell
> > echo 'https://storage.sev.monster/alpine/edge/testing' | tee -a /etc/apk/repositories
> > wget https://storage.sev.monster/alpine/edge/testing/x86_64/sevmonster-keys-1-r0.apk
> > sh -c '
> >   apk add --allow-untrusted ./sevmonster-keys-1-r0.apk
> >   apk update \
> >     && apk add gcompat \
> >     && rm -rf /lib/ld-linux-x86-64.so.2 \
> >     && apk add --force-overwrite glibc \
> >     && apk add glibc-bin'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 至于 libstdc++ 就简单了 , 直接
> > ```shell
> > apk add libstdc++
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 之后就可以了

hhhhhh , 我倒是在解决别的 glibc 问题时候顺手解了, 就记录一下

**Comment by thhbdd** [comment]
> 我在 LXC alpine 里面找到了一个解决办法，应该是通用 alpine:3.18 主要是两个依赖的问题 glibc 和 libstdc++
> 
> [glibc](https://github.com/sgerrand/alpine-pkg-glibc/issues/210)这位老哥用爱发点自己打造了一个比较新的版本
> 
> ```shell
> echo 'https://storage.sev.monster/alpine/edge/testing' | tee -a /etc/apk/repositories
> wget https://storage.sev.monster/alpine/edge/testing/x86_64/sevmonster-keys-1-r0.apk
> sh -c '
>   apk add --allow-untrusted ./sevmonster-keys-1-r0.apk
>   apk update \
>     && apk add gcompat \
>     && rm -rf /lib/ld-linux-x86-64.so.2 \
>     && apk add --force-overwrite glibc \
>     && apk add glibc-bin'
> ```
> 
> 那么libstdc++就简单了，直接
> 
> ```shell
> apk add libstdc++
> ```
> 
> 之后就可以了

感谢提供的解决方法，我是不想在lxc下运行docker，然后用alpine一直报错hhhh，在3.21也能用
