### ISSUE TITLE
出问题了

### ISSUE THREAD

**Issue by liugeng518** [cnk3x/xunlei#83]
2023.2.22号开始突然失效了。没有办法登陆账号？

**Comment by cnk3x** [comment]
不知道你的具体情况，信息太少了，我这里测试是可以登录的，
另外，今天已经升级底包到 3.5.2了， 重新拉来试试，
实在有问题，可以尝试把迅雷账号数据目录删除然后重新创建容器。

**Comment by liugeng518** [comment]
安装没有问题，但是不想以前一样，登录界面一直显示“设备校验失败，请重新登录设备或刷新”，请教是不是我的个案，重新安装过了，还是一样！！！

**Comment by liugeng518** [comment]
二维码刷新不出来！账号密码登录界面也打不开？

**Comment by Kinsenlin** [comment]
我也遇到这问题了，之前用着好好的，现在重新拉取也没用了

**Comment by liugeng518** [comment]
> 我也遇到这问题了，之前用着好好的，现在重新拉取也没用了

找到问题了，不是迅雷的问题，是openwrt导致了网络不通！重装了新版的openwrt就解决了。

**Comment by atgcccn** [comment]
我没有安装openwrt 为什么也出现了无法登录的问题了   也是不出二维码
