### ISSUE TITLE
可以增加密码访问网页吗

### ISSUE THREAD

**Issue by mysoft999** [cnk3x/xunlei#84]
直接裸奔是不是有点危险？

**Comment by cnk3x** [comment]
https://github.com/cnk3x/xunlei/issues/57

**Comment by ssrvps** [comment]
> #57

大佬，正需要这个，请问在哪里增加呢？能麻烦出个教程吗？小白真不太明白，麻烦了

**Comment by cnk3x** [comment]
创建容器的时候添加环境变量 XL_BA_USER  和  XL_BA_PASSWORD
XL_BA_USER 就是访问的用户名， XL_BA_PASSWORD 是密码

**Comment by mysoft999** [comment]
感谢大佬，辛苦了
