### ISSUE TITLE
下载路径能否设置成局域网内其他设备的路径？

### ISSUE THREAD

**Issue by cheneylaw** [cnk3x/xunlei#86]
docker run -d --name=xunlei --hostname=3755u --net=host -v //192.168.123.127/mnt/disk/xunlei:/xunlei/data -v //192.168.123.127/mnt/disk/downloads:/xunlei/downloads --restart=unless-stopped --privileged registry.cn-shenzhen.aliyuncs.com/cnk3x/xunlei:latest syno

这样设置还是不正确，192.168.123.127是局域网内开启了smb协议的设备，PC访问该路径是没问题的，请问我该怎么修改命令才对呢？谢谢

**Comment by cnk3x** [comment]
先把局域网路由挂载到本地，然后就像本地路径一样使用了。

**Comment by cnk3x** [comment]
默认情况下docker 容器是不支持直接访问samba的。

**Comment by lx0758** [comment]
volumes:
  downloads:
    driver_opts:
      type: "cifs"
      o: "username={USERNAME},password={PASWWORD}"
      device: "//{IP}/{PATH}/Thunder/"
