### ISSUE TITLE
经常出现内容违规，不让下载

### ISSUE THREAD

**Issue by donething** [cnk3x/xunlei#91]
应该算正常资源，如 Windows7 、8 的镜像，电影《交通费》这些，在迅雷云盘是可以离线的

我看别的 NAS 迅雷 也没这些限制啊。。

**Comment by phcl1998** [comment]
获取云盘直链，用aria2下载，速度可能会慢大概1m~2m

**Comment by Gloryandel** [comment]
违规与否都是迅雷服务器判定的。与平台关系不大。至少我遇过刚添加时说应版权要求不给下，第二天就能启动继续下载了。。。。
