### ISSUE TITLE
很奇怪用了这么多的docker镜像，第一次遇到必须用这么高权限的

### ISSUE THREAD

**Issue by 0x11901** [cnk3x/xunlei#92]
一般来说设置一个普通权限的UID/GID就足够了，会不会有什么问题啊？特别是迅雷，以前还出过玩物下载挖矿这种事。
有点担忧给他root权限。

**Comment by cnk3x** [comment]
https://github.com/cnk3x/xunlei/issues/85#issuecomment-1499013570

**Comment by 0x11901** [comment]
UID/GID设置的是一个普通权限账号的，然后挂载的`/xunlei/data`和`/xunlei/downloads`目录该账号是有rw的权限的
不过这样启动会报错：
```
绑定目录 "/dev" -> "/xunlei/dev" 失败: permission denied
```
确实该账号是无法在我NAS的`/dev`创建任何目录的。但是我比较好奇的是难不成迅雷真的想访问我的`/dev`目录？他这是想干什么呢？
如果使用root账户就不报错，docker中使用高权限执行容器也能正常运行，在log中可以看到：
```
uid=1026,gid=100
```
说明参数应该是传进去了。

**Comment by 0x11901** [comment]
或者是否可以在47行
```
VOLUME [ "/xunlei/downloads", "/xunlei/data" ]
```
加一个可选的`/xunlei/dev`，不知道为什么迅雷要`/dev`的权限

**Comment by cnk3x** [comment]
迅雷不需要root权限，但为了模拟群规环境和避开迅雷对docker的检测，使用了chroot来实现的，chroot是需要root权限的。

**Comment by cnk3x** [comment]
> 或者是否可以在47行
> 
> ```
> VOLUME [ "/xunlei/downloads", "/xunlei/data" ]
> ```
> 
> 加一个可选的`/xunlei/dev`，不知道为什么迅雷要`/dev`的权限

迅雷用到了/dev/ttyN设备，所以是必须引用。

**Comment by DioHamilton2020** [comment]
我想用这个项目在docker desktop for windows上当作下载器，下迅雷网盘的资源，也报这个错误，必须读linux的/dev那就是没办法在win上用了？
