### ISSUE TITLE
systemd 分支可以增加登录验证吗？

### ISSUE THREAD

**Issue by qingtian110** [cnk3x/xunlei#93]
https://github.com/cnk3x/xunlei/tree/main

在公网上安装，如果打开防火墙直接通过ip 就进去了，目前使用了nginx 反代理的方式来增加验证，希望程序本身可以支持设置账号密码验证。

**Comment by gngpp** [comment]
> https://github.com/cnk3x/xunlei/tree/main
> 
> 在公网上安装，如果打开防火墙直接通过ip 就进去了，目前使用了nginx 反代理的方式来增加验证，希望程序本身可以支持设置账号密码验证。

可以用我的https://github.com/gngpp/xunlei，都支持面板认证
