### ISSUE TITLE
会员加速未开启

### ISSUE THREAD

**Issue by callmejoo** [cnk3x/xunlei#95]
同一个资源，windows的迅雷下载满速，此版本一直0速度，看了下桌面版速度都是来自会员加速，docker版似乎没开启加速，但我是会员
![image](https://github.com/cnk3x/xunlei/assets/18390127/b061012d-9a8c-422d-ad48-fc25055e055e)

**Comment by LiHang941** [comment]
同样

**Comment by gg5g** [comment]
同样，MAC DOCKER
