### ISSUE TITLE
日志显示已经启动，但是网页打不开。

### ISSUE THREAD

**Issue by WillFindX** [cnk3x/xunlei#96]
#49 和这个一样的日志，但是网页打不开。设备是我家云，处理器是arm64。一直没找到解决办法。

**Comment by cnk3x** [comment]
尝试加上启动环境变量 XL_DEBUG=1 开启完整日志模式，看看具体的输出详情

用以下命令临时启动查看日志，解决问题再正常设置参数启动

docker run --rm **--env  XL_DEBUG=1 --privileged** --net=host cnk3x/xunlei:latest

默认启动是屏蔽了所有的迅雷原本的日志（因为迅雷原本的日志太多了）。

**Comment by cnk3x** [comment]
issue closed.
