### ISSUE TITLE
试了一下不能加密，加密就无法启动

### ISSUE THREAD

**Issue by gujiangjiang** [cnk3x/xunlei#98]
环境变量 XL_BA_USER 和 XL_BA_PASSWORD: 给迅雷面板添加基本验证（明码）。

试了这个，只要添加了这两个变量，开启后10s内就会停止运行报错，但找不到日志。
群晖7.2 Docker20

**Comment by gujiangjiang** [comment]
加上了这两个变量就一直启动不了，启动了就报错停止，删掉这俩变量就没问题。
Container Manager 容器 xunlei 意外停止。请在容器页面上选择 xunlei，单击详细信息按钮，然后前往日志选项卡以了解详细信息。

目前用的hub.docker.com上的latest镜像

**Comment by cnk3x** [comment]
试是加上环境变量 XL_DEBUG=1，查看下具体的日志信息

**Comment by gujiangjiang** [comment]
@cnk3x 
我后来删掉了xunlei配置文件夹，删掉了真个docker重新下载，然后在cli阶段就加入了这两个变量，目前运行完好，密码可用。

我猜测是，原先如果没有开启密码，临时通过e加密码的就无法启动，只能在创建docker的时候就开启密码才行。

**Comment by cnk3x** [comment]
没有这个限制的，加验证是外壳的行为，影响不到迅雷的运行。我复现不了你的情况，所以无法做出判断
